### ISSUE TITLE
Warning when Node/Name Normalizer Down for the UI?

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#104]
Is there anyway to get a warning when this key component is down?  When it is down users cannot search using the UI.

UI team can tell which tool their architecture is dependent on.

**Comment by dnsmith124** [comment]
There is an error in the browser console that signifies this, just not in the actual UI. I went that direction because I thought the general consensus was for the user to not necessarily be aware of the systems behind translator. 

If a more descriptive error in the UI itself about what exactly is failing would be preferable I'm happy to add one!

**Comment by sierra-moxon** [comment]
From TAQA:
- we could do this in pieces, maybe for NN first.
- UI has a "sorry, something is broken", have to go to "web tools" and do an "inspect", the console will tell you which piece is down.

**Comment by sierra-moxon** [comment]
closing in favor of #108, which is an issue to implement an uptime monitor.
