### ISSUE TITLE
Paths Including Home Sapiens, Boys, Siblings

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#131]
Looks like this is primarily coming from ARAGORN, it may be because ARAGORN is the only ARA responding.

Steps:
1. In the CI UI select What chemical downregulates ECHS1 (i think its was the first choice but i can't really recall) https://ui.ci.transltr.io/results?q=3c728ec5-29fd-41e4-8f66-5de05d7694fb
2. Score is empty, the first pages all have 0 evidence in the first page expand Citalopram hydrobromide
![image](https://user-images.githubusercontent.com/38321826/220420589-65ae5668-8c08-4e56-a2d8-c0d9ead150f9.png)

3. Reverse sort on evidence, for result HPV, there's some evidence from HPV to Boys but not to ECHS1
![image](https://user-images.githubusercontent.com/38321826/220420892-c5fab200-471f-4a84-ad8e-d004f44038a4.png)

4. Entity search for Caffeine, Sibling is also a hop
![image](https://user-images.githubusercontent.com/38321826/220422311-549e3a86-281a-42b4-be99-058afb77c2ed.png)

6. In ARAX https://arax.ncats.io/?r=3c728ec5-29fd-41e4-8f66-5de05d7694fb, it looks like only ARAGORN is responding

7. Beta Carotene, all of the links say knowledge source is semmedb but no links to the pubs 
![image](https://user-images.githubusercontent.com/38321826/220421302-6474504d-2e23-43d4-aeb5-65f41f8fdf49.png)

8. I think there are several issues spread across different stakeholders
a. why are the other ARAs not responding?
b. is cohort an expected path? seems like we would get a lot of answers/errors 
c. should the UI represent cohort (ie the icon isn't quite right in the UI)
d. is the has part link really dependent on semmed?  we can't get that anywhere else?
e. where is ARAGORN's score?

**Comment by sstemann** [comment]
@sierra-moxon i'm not sure where to start with this one

**Comment by gglusman** [comment]
It would make sense for cohort to be metadata/EPC, as context of other assertions.

**Comment by cbizon** [comment]
I suspect that our newer rules in ARAGORN will not include this result, but will have to double check

**Comment by cbizon** [comment]
Thanks @sstemann .   The underlying problem is that the rule mining we are doing is agnostic about the classes of the intermediate nodes.  So we learn from the rule mining that if chemical A is part of chemical B and chemical C is part of chemical B also, AND chemical C treats a disease, then maybe A also treats that disease.   But in the implementation we write B as a Named Thing.  But once we move outside the training data, it turns out that other sources are saying junk like PROPOLOL part of HomoSapiens.   So we're going to tighten up the rule classes to avoid it (aragorn issue linked above).

Also - we got the ranking issues on CI fixed: https://ui.ci.transltr.io/results?l=Oculo-auriculo-vertebral%20Spectrum&t=0&q=6200df88-8ffe-4a55-9d8b-1d786fe2a651

**Comment by sierra-moxon** [comment]
@cbizon - leaving this ticket in "in progress" - let me know if it needs to be closed? :)

**Comment by sierra-moxon** [comment]
06/22/23 - retested on ci
I can no longer reproduce.  I am going to close as completed! :D
