### ISSUE TITLE
Scores are N/A

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#141]
In today's standup, we reviewed these answers

UI:  https://ui.ci.transltr.io/results?l=Fuchs%27%20Endothelial%20Dystrophy&t=0&q=30fa40cd-e74d-4532-ada1-9914c87db20a
ARAX UI:  https://arax.ncats.io/?r=30fa40cd-e74d-4532-ada1-9914c87db20a

ARAGORN and ROBOKOP return score N/A

![image](https://user-images.githubusercontent.com/38321826/221970709-93946319-ede7-4014-8b2c-83b7a95b85e7.png)
![image](https://user-images.githubusercontent.com/38321826/221971627-28b94492-8e01-4414-8dd7-f2ce9fcd9593.png)

**Comment by cbizon** [comment]
This problem does not seem to exist in dev, which is a few versions ahead of ci at the moment, so we will push dev to ci.

Note that this particular set of answers will actually vanish entirely.   In a recent update, we updated the treats rules to be more specific.  It looks like most/all of the results here are based on a "similar_to" relationship, and we have removed that rule in the newest release, since it gave a large number of false positives.

**Comment by sstemann** [comment]
thank you for looking into, looking forward to the update to CI

**Comment by cbizon** [comment]
Just as a further update - some digging by @YaphetKG found that the underlying culprit was not a bug in CI per se but a difficulty with the omnicorp install in that environment.  He and ITRB are working to resolve the issue.  We are going to do a push from dev to ci, which will change the answers as outlined above, but the missing scores turns out to be an independent issue.

**Comment by sstemann** [comment]
retested in CI, and scores are returned for ARAGORN and ROBOKOP for Meniere disease 

https://ui.ci.transltr.io/results?l=Meniere%20Disease&t=0&q=8593bb47-bd65-4504-bbe7-335268dc141a
https://arax.ncats.io/beta/?r=8593bb47-bd65-4504-bbe7-335268dc141a

**Comment by sstemann** [comment]
well in this other query i ran today, ARAGORN has no ranking:

https://arax.ncats.io/beta/?r=a4e24ccb-74f9-47e0-b0e8-53ed13636a08 

so now i'm not sure

**Comment by cbizon** [comment]
Thanks @sstemann I assume this was in CI?

**Comment by sstemann** [comment]
this looks resolved thanks!
