### ISSUE TITLE
UI: Some results are missing evidence

### ISSUE THREAD

**Issue by khanspers** [NCATSTranslator/Feedback#164]
Query: What may treat Duchenne Muscular Dystrophy? (run in https://ui.transltr.io/)
PK: [c0b054c9-381d-48a6-bfff-b534821f478f](https://arax.ncats.io/?r=c0b054c9-381d-48a6-bfff-b534821f478f)

7 of the top 20 results have no evidence given for the treats edge. Tracking down the top 4 results without evidence in ARAX, it looks like the only ara that's returning all 4 is **improving**. BTE also returns two of them (Drisapersen and Domagruzomab), and provides PMIDs for the edge, but this is not visible in the UI. 

![Screen Shot 2023-04-25 at 2 57 25 PM](https://user-images.githubusercontent.com/1442197/234413536-a8e2328b-39c0-49cc-b984-2924e7cc3f04.png)

**Comment by sierra-moxon** [comment]
from TAQA: 
Andy: yes they provide PMIDs, but they might not be using "biolink:publications" instead using "biolink:Publication"  -- tagged with the wrong biolink attribute. 
Gus: node binding subclass issue - not picking up certain diseases with publications associated with the edge.  Might be two or three reasons.

**Comment by gprice1129** [comment]
Looked into this issue and found the following ([link to query](https://ui.transltr.io/results?l=Duchenne%20Muscular%20Dystrophy&t=0&q=c81e8980-b612-41d6-9336-2b40a332e08d)):

**Drisapersen**
The evidence issue turns out to be that the CURIEs returned for Drisapersen by Improving Agent and BTE are different:
Improving Agent: [CHEMBL.COMPOUND:CHEMBL2108735](https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL2108735/)
BTE: [UMLS:C3886496](http://linkedlifedata.com/resource/umls/id/C3886496)

If you search for Drisapersen in the text search you can see two results with the same label. The second one has the included evidence from BTE.

**Domagrozumab**
Same as for Drisapersen:
Improving Agent: [CHEMBL.COMPOUND:CHEMBL3544991](https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL3544991/)
BTE: [UMLS:C5139888](http://linkedlifedata.com/resource/umls/id/C5139888)

**(8S,10S,13S,14S,16R,17R)...**
The underlying CURIE is [PUBCHEM.COMPOUND:122197544](https://pubchem.ncbi.nlm.nih.gov/compound/122197544). The CURIE only occurs in Improving Agent's answer and doesn't have any publications attached. The UI display that will be released next week should at least show that there is one piece of evidence which is the source (chembl).

**Ramatercept**
Same issue as for (8S,10S,13S,14S,16R,17R)... Underlying CURIE is [CHEMBL.COMPOUND:CHEMBL2108674](https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL2108674/)

Going to include @cbizon and @gaurav to look into possible resolver issue.

**Comment by gaurav** [comment]
Thanks for reporting this! We'll look into ways of improving our CHEMBL.COMPOUND connections at https://github.com/TranslatorSRI/Babel/issues/131

**Comment by Genomewide** [comment]
This appears to be an old issue that was due to the fact that we only showed publications as evidence. is resolved now.
