### ISSUE TITLE
What drugs may treat Pertussis: The word "impact" from abstract erroneously interpreted as IMPACT gene; strange scoring in the UI

### ISSUE THREAD

**Issue by khanspers** [NCATSTranslator/Feedback#174]
**Query: What drugs may treat Pertussis?** 

**Results:** Includes several positive controls (antibiotics), but has some issues:

- Top results is a chemical named "N-[(4-fluorophenyl)methyl]-1-[(1r)-1-naphthalen-1-ylethyl]piperidine-4-carboxamide", not sure what this is. No evidence given, just says its from Improving agent. This result has the same score (100.0) as the next 4 results, which are all known treatments, each with many pieces of evidence. 
- Several of the results have paths that include a biological entity node for the gene [IMPACT](https://www.ncbi.nlm.nih.gov/gene/55364), but it looks like its a mis-interpreting the word "impact" in the abstracts of papers for this gene. See screenshot below. Looks like its coming from BTE.

**ARS PK: c72e06ce-8d2a-4042-b068-0acc48f97972**

<img width="1255" alt="Screen Shot 2023-05-05 at 5 11 46 PM" src="https://user-images.githubusercontent.com/1442197/236587799-4a0b577d-43d5-4717-9486-a341b6d7ac9f.png">

<img width="1483" alt="Screen Shot 2023-05-05 at 5 17 42 PM" src="https://user-images.githubusercontent.com/1442197/236587826-e9e576dd-aa9b-4980-b982-a3ba0e9b6cfe.png">

**Comment by sierra-moxon** [comment]
from TAQA:
another miscategorization from SEMMEDDB
BTE
https://arax.ci.transltr.io/?r=320e98e0-3320-479b-a7fb-8aca6cb2a9e6

**Comment by khanspers** [comment]
Here's another one: 
"Glyphosate treats Atrial Fibrillation":
![Screen Shot 2023-07-11 at 10 19 23 AM](https://github.com/NCATSTranslator/Feedback/assets/1442197/cb6de6ff-1767-464a-ac4d-31b60254b13c)


https://ui.test.transltr.io/results?l=Atrial%20Fibrillation&t=0&q=849a9a98-f933-4c25-8f4b-d1de46518267
(Select "Agrochemical" from ChEBI Role Classification filter. Glyphosate is the herbicide in Roundup)

**Comment by andrewsu** [comment]
* `folate - affects - IMPACT gene` comes from this association: https://biothings.ncats.io/semmeddb/association/C0178638-STIMULATES-C1825598, which has `pmid_count: 1`. So this one will be filtered out with when a solution for #100 is implemented.

* `glyphosate - affects - IMPACT gene` comes from this association: https://biothings.ncats.io/semmeddb/association/C0061764-INHIBITS-C1825598, which has `pmid_count: 2`.  This one will also be addresed with #100.  

Going to close this issue since this example will be addressed in #100
