### ISSUE TITLE
Nothing to add beyond the above.

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#183]
## Steps to reproduce:
Selected "What chemical upregulates", typed 'sirtuin', waited for options, selected "SIRT1", clicked Search. Very quickly got "There was an error... Please try again."
Not seeing any clear indication of how to try again, I just clicked on Search again. This gave me the error message "No term selected" even though the query still shows as before.

**Comment by dnsmith124** [comment]
Tested this and was unable to recreate. Given the date of the ticket's creation I would imagine it has something to do with the transition to trapi 1.4, which appears to be resolved on CI. 

The above URL now returns results instead of the aforementioned error message. 

The second issue (clicking search on a results page where the search bar appears to be populated, only to have the 'no term selected' error show) is a known bug that I am working to address!

**Comment by sstemann** [comment]
searching from results has changed, this is OBE
