### ISSUE TITLE
Many results with curie as name

### ISSUE THREAD

**Issue by sierra-moxon** [NCATSTranslator/Feedback#185]
https://ui.transltr.io/results?l=MET&t=2&q=14da9c39-1dc2-41db-b60c-938ea98073e6

Result: Pubchem.compound:13017912
Name is shown here https://pubchem.ncbi.nlm.nih.gov/compound/13017912

[Geldanamycin](https://pubchem.ncbi.nlm.nih.gov/compound/Geldanamycin) is a [benzoquinone](https://pubchem.ncbi.nlm.nih.gov/compound/benzoquinone) antineoplastic antibiotic isolated from the bacterium Streptomyces hygroscopicus. [Geldanamycin](https://pubchem.ncbi.nlm.nih.gov/compound/Geldanamycin) binds to and inhibits the cytosolic chaperone functions of heat shock protein 90 (HSP90). HSP90 maintains the stability and functional shape of many oncogenic signaling proteins; the inhibition of HSP90 promotes the proteasomal degradation of oncogenic signaling proteins that may be over-expressed or overactive in tumor cells. (NCI04)

**Comment by sierra-moxon** [comment]
from TAQA:
doesn't seem to be a NN issue.

**Comment by andrewsu** [comment]
So in scanning the ARA-specific results at https://arax.ci.transltr.io/?r=14da9c39-1dc2-41db-b60c-938ea98073e6, it looks like most of the "curie as a name" examples are coming from improving agent (though there are also a few from BTE for pubchem compounds that the node norm does not recognize, e.g., [Pubchem.compound:91936104](https://nodenorm.transltr.io/1.3/get_normalized_nodes?curie=PUBCHEM.COMPOUND%3A91936104&conflate=true)) [Pubchem.compound:16187854](https://nodenorm.transltr.io/1.3/get_normalized_nodes?curie=PUBCHEM.COMPOUND%3A16187854&conflate=true)).  

But for the specific case above Pubchem.compound:13017912 which NN does resolve to a name (https://nodenorm.transltr.io/1.3/get_normalized_nodes?curie=PUBCHEM.COMPOUND%3A13017912&conflate=true), this is an issue for the ARS to look into, since ARS should be doing systematic name normalization prior to returning results to the UI.  Is my understanding correct here?

**Comment by cbizon** [comment]
@andrewsu my understanding is the same as yours.

**Comment by sierra-moxon** [comment]
from TAQA: 
the original issue is done! :)   We'll put the last bit here in a new ticket.
