### ISSUE TITLE
MVP1: downprioritize results that are of the type drug -- treats -- disease -- correlated_with -- disease

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#188]

**Comment by sandrine-m** [comment]
I would have expected this result first:
<img width="752" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/66342541/f0423f04-f9da-4be6-a452-fbe400c3c77b">

**Comment by sandrine-m** [comment]
Background: this issue comes because when I am searching HIV-associated nephropathy, drugsw that treat HIV should be at the end because that is not the disease I am primarily interested in (and those patients get already treated for HIV)

**Comment by sandrine-m** [comment]
More background (@rhubal): I am working on a disease (HIV associated Nephropathy) that is a rare disease affecting patients with HIV. When I ask Translator which compounds may treat that disease, all first pages are compounds used in treatment for HIV and the general reasoning behind is [drug]—treats—HIV—associated with/correlated with—HIVAN. However all those results might be actually compounds that trigger the disease.
 The reasoning tool in general does not correct for confounders/comorbidities which affects a lot my user experience. @Genomewide I would suggest to provide the user at least with a filter on highly correlated diseases so that the user could remove them if their hypotheses is similar than the one explained in this example.

**Comment by sandrine-m** [comment]
I checked now again and now it is much much better! Thank you! - Closing this issue
