### ISSUE TITLE
what drugs may treat AHC

### ISSUE THREAD

**Issue by gglusman** [NCATSTranslator/Feedback#198]
This may be redundant with a number of other tickets.

I asked Translator yesterday and today (on two different instances, today on CI) what drugs may treat Alternating Hemiplegia of Childhood (AHC). Got the initial response almost immediately - 300 results all coming from imProve Agent, the vast majority with the long IUPAC nomenclature, all of them with zero publication evidence and just the one source (imProving) with the single ‘futher info’ URL leading to the github page, which is extremely cryptic to the user. Of the 300 hits, 289 are FDA approved, all are Small Molecule, so those UI controllers don’t help much. Increasing the minimum number of evidence causes all results to vanish (since no publications support). The spinner kept spinning for nearly half an hour, after which it changed to the checkmark, with no further results from other ARAs. Drilling into each hit adds no further information - each small molecule is alleged to treat AHC by imProving Agent without further detail. The top 33 hits all had score 96.3, another dozen or so had scores decreasing to 87.7, after which scores drop to 49.8 all the way to page 27, and finally there’s a couple dozen much lower scores (12.0 and down).

I asked ChatGPT the same question, and the first answer was Flunarizine (correct). Used the UI ‘Entity Search’ widget to see if I could find Flunirazine among the 300 hits, and got ‘No results available’, suggesting it isn’t there (or it isn’t recognized vs. the IUPAC name).

(I initially submitted this report via the UI as 'comment' and no ticket was generated - the form simply got erased and there was no confirmation of it having been captured.)

[edited to fix typo Flunirazine -> Flunarizine]

**Comment by jaredroach** [comment]
Here is a link to the ChatBot session (recreated by me) that Gustavo referenced, including the flunarizine result:
https://chat.openai.com/share/b88bc79b-1b83-4fda-a08a-1bdb92466f70

Although 'flunarizine' is indeed the best single answer, other answers listed in the same ChatGPT session appear to be hallucinations, such as 'beta blockers'. For example, 
     "beta blocker" "alternating hemiplegia of childhood"
has no PubMed responses.

**Comment by jaredroach** [comment]
I am getting very unstable behavior when I try to replicate Gustavo's question on Translator. When I went to the main query page on Safari, I couldn't even type into the query box, perhaps because pop-up windows were blocked. When I went to the page on Chrome, I was able to type into the query box, and "Alternating Hemiplegia of Childhood" was clearly selected by me, but it looked like translator did a search of "Heart Disease" instead, which I didn't notice at first, and so was excited to see flunarizine in the results. But then I tried again, and translator clearly did the search as I inteneded, and I seemed to get the same list as Gustavo got (without flunarizine). Then without touching anything, I stepped away from my keyboard, and came back a few minutes later, and flunarizine was an answer. Not sure how to troubleshoot specific answers in Translator with an interface this wonky. 

https://ui.transltr.io/results?l=Alternating%20Hemiplegia%20Of%20Childhood&t=0&q=d271a54e-5527-478f-80de-e848e583926c

Showing 1-1 of 1 (348) Results
String: flunarizine
Flunarizine
2 Paths that may affect Alternating Hemiplegia Of Childhood
View All Evidence
Publications (5)
Sources (1)
86.7

**Comment by jaredroach** [comment]
h/t Gustavo. How did you find those articles? I couldn't find them with either PubMed or Google Scholar.
I guess that points to one issue with the ChatBots. They don't give citations, and when they do, they hallucinate the references. Even if they give true responses, in order to replicate them and be sure they are not hallucinations, requires rigorous scholarship. And if you are going to do the rigorous scholarship, maybe it was not worth your time doing the ChatBot in the first place. Except maybe this instance is a counterexample. If I never would have thought of beta blockers, then having the ChatBot response might make me look very hard for a link between beta blockers and AHC. But that would then seem to require someone even better than me at searching the literature to find. Beyond that, I am not sure what the implications are. Both Translator and ChatGPT seem to have a lot of promise, but neither seem to be "prime time".

**Comment by sandrine-m** [comment]
Testing CI ([PK](160e3c60-7479-4bdb-939f-97dea5dc08b5)), here is what I get:
<img width="941" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/66342541/dd243848-c68b-452e-ad83-b0e29f2fd62f">
Testing UI ([PK](1af44e82-8735-4a20-8fe1-281e071da3a1)), here is what I get:
<img width="767" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/66342541/e363e86a-b8da-4cbf-89da-73f5fa895bb9">

Rnaking seems to be dependent on the UI instance. What is really more concerning though is that the top result in the CI talks about acute hepatitis C (AHC) instead of the disease. @gaurav is that a NN issue?

Thanks

**Comment by sandrine-m** [comment]
SS related to my comment:
<img width="573" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/66342541/8ca7a11d-3fc1-4cd9-939f-cc54c0f35664">

**Comment by jaredroach** [comment]
David Koslicki suggested using Perplexity as a ChatBot. It provides the best response yet, with real links to real citations.
https://www.perplexity.ai/search/7a91e3f6-513e-4c16-8cdd-9654920783cb?s=u

**Comment by karafecho** [comment]
I was unaware of Perplexity. Will check it out.

But for the QotM exercise, I think we should stick with ChatGPT and/or GPT3, as this are the two ChatBots that the Editor suggested and ran one of our queries against.

**Comment by jaredroach** [comment]
I think that makes out response easy. ChatGPT hallucinates, so is dead in the water as a reasonable biomedical search engine. But if we decide to go with Perplexity, see the draft I wrote here in response to the editor, relying on Perplexity. 
     https://docs.google.com/document/d/1OvmsA0ENseqzeEuWi05esKp4a7pHyIPRHC8bhzIJbKg/edit
Perplexity's answers are scary good.

**Comment by jaredroach** [comment]
Also, GPT-4 was introduced in mid-March. It might be hard for most of us to find a running version of GPT-3.

**Comment by sandrine-m** [comment]
Summarizing my point of view on this topic on a slack discussion:
I totally agree on the "hallucinations" effects. My main question as a reviewer would be "how much can you tell they are hallucinations?" Like Gustavo mentioned in the ticket, you can find publications liking the drug classes cited to the disease.
The issue I guess is more to fight the people perception of it. And sadly enough, even among scientists, there is a wide usage of this tool without making proper benchmark.

Maybe not for that paper, but I really think we should work on a highly curated (by SMEs) benchmark (both at the data quality and user perception levels) in order to prove Translator worth and recruit new SMEs.

Also as a reviewer, one could ask "what is the difference between an hallucination and a prediction?" In the MVP1, the question is "what drugs may treat [disease X]?" that includes and promote creative answers therefore inferred knowledge. Can we prove our creative modes are more powerful than OpenAI generative system? 

ChatGPT answers in this example were on real legit compounds (concepts were real? is it what you meant). Translator top compound was a compound that were related to another disease (also with the same AHC acronym). So as a user and potential reviewer, Translator has yet to convince me. Moreover, the qualitative type of answer is very dependent on the journal you'll submit. It is not because you show me it worked on a particular example that I'll trust the system until you prove me it works 95% of the time. Benchmark could me another manuscript for sure (and that could be the answer to the reviewers).

On user perception (this is my inferrence from seing people interact with technology) but surely @Rosinaweber and @rhubal can comment here since they are the experts : 
As a user, if you give me a reference, you better have it right because I am going to click on the link to verify and if it is not, I will loose a lot in confidence in the system. BUT, if you do not provide me links there is less chance I will make the effort/take the time to verify but that won't necessarily affect my confidence in the system.

**Comment by sandrine-m** [comment]
@karafecho  re: answer to editors - I agree to the fact that the response should be geared towards what the reviewers asked. 
I think what would be a very successful answer is if we can change the reviewers' perception of Translator being another ChatGPT like: there are aspects in which Translator is unique and the features of the comparison should be (reason for which I have posted in the UCWG channel). 
One principal Translator strength to me as a user is its ability to give a reasoning and make it transparent to the user (not simply coocurrence of terms), there is also logical entailments from Biolink, highly curated data instead of web scraping (cf the new Clinical ARS that is more than just indications of drugs in a clinical trial)....etc
For example, in the precedent responses in this ticket, Acetazolamide (proposed by ChatGPT) could be a good candidate for treating AHC. Although ChatGPT hides behind apologies when you ask for referrences, Perplexity does explain you why it is a good candidate (appears together in a clinical trial). The question is why isn't it a good candidate for Translator (if my memory serves me well, does not appear on the top)? Is it that Perplexity/ChatGPT (as @sierra-moxon  pointed out all work with OpenAI data), rank high stuff that co-occur but completely disregard mechanistic approach (towards causal modeling). This argument to me is very similar to the comments I brought in Jared's testing document: it is not because we provide evidence for an edge that we provided evidence for a result (a subgraph with muti-edges). The Biolink help creative modes improve the system precision and remove noise from co-occurrence of terms that cannot mechanistically occur at the together. 
If we can use at least find an example on those QoTM of why Translator is better I think we will convince them.

**Comment by sierra-moxon** [comment]
from TAQA:
Checkmark with no new answers symptom: ARS has a set amount of time that it will wait, then if it times out, the UI says "no more answers to be had" and returns the checkmark of "done."  Then, however, the PK loaded later and new answers came in, then they will show up.  Just happens that in the first run, there was a timeout.
from Gus: I just ran this same thing and Flunarizine is the top result.
from Jared (SME testing): Running this 4 times in one day, all different answers first; some issues with the UI testing, autocomplete, etc.

**Comment by sierra-moxon** [comment]
TODO:
break down this ticket further.  
- performance target for each ARA
- performance target for each KP
- autocomplete, etc.

**Comment by sandrine-m** [comment]
(created a [separate issue](https://github.com/NCATSTranslator/Feedback/issues/201) regarding the node normalization issue)

**Comment by sierra-moxon** [comment]
@gglusman @karafecho @sandrine-m - what should we do with this ticket?  close?  Are the main problems highlighted in this use case covered by other, more narrowly focused issues?  (I think they are - we have performance targets for our components, we have known issues with returning more results after the UI says its done returning results (the five-minute timeout, etc.), folks are resubmitting the paper with chatgpt comparisons, etc.

**Comment by karafecho** [comment]
Agreed. This ticket is too packed to be useful, and I think the main issues are captured in other tickets, so closing this one.
