### ISSUE TITLE
Metabolic Pathways

### ISSUE THREAD

**Issue by cbizon** [NCATSTranslator/Feedback#2]
What type of data is missing?
Metabolic pathways.  Specifically things like https://www.pharmgkb.org/pathway/PA165964265/overview

What would those data allow us to do if we had it? A specific use case being helpful here.
For instance, on QotM3, we would like to know about reactive metabolites of valproic acid, and what further metabolizes them.  With this, we would be able to form hypotheses about VPA's liver toxicity.

What are the requirements for those data? (e.g must have chemical structure in SMILES format).
Ideally, these would relate chemical entities to the genes/proteins that metabolize them and the chemical entities that result.

**Comment by sandrine-m** [comment]
Not sure if this issue is still open:
FWIW, MolePro has currently 3 databases containing metabolic information: HMDB, BiGG models, and ChEMBL. Currently the modeling of metabolic reactions is split into different edges: compound--compound, compound--genes...etc. 
I'll try to see how easy it is to reconstruct a given metabolic reaction.
