### ISSUE TITLE
First results returned to treat "Nemaline myopathy 3" are drugs that treat muscle "rigidity" (rather than muscle weakness).  

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#20]

**Comment by sierra-moxon** [comment]
<img width="1495" alt="Screen Shot 2022-10-17 at 5 05 28 PM" src="https://user-images.githubusercontent.com/4561292/196305770-9d03e963-c292-4d3c-9611-6f4612426517.png">

<img width="1124" alt="Screen Shot 2022-10-17 at 5 05 43 PM" src="https://user-images.githubusercontent.com/4561292/196305784-11a4cfcf-314e-47fb-a8d3-8182fd4b7e7a.png">

**Comment by sierra-moxon** [comment]
Viewing the ARAX results for baclofen and botulinum:
<img width="1511" alt="Screen Shot 2022-10-17 at 5 06 56 PM" src="https://user-images.githubusercontent.com/4561292/196305850-d9824f32-dd0b-405d-be6e-7bf9c66a754a.png">

(both those drugs treat spasticity or rigidity, eg.: Baclofen is used to help relax certain muscles in your body. It relieves the spasms, cramping, and tightness of muscles caused by medical problems, including multiple sclerosis or certain injuries to the spine.)

ARAX evidence points me to SRI reference KG, and then to OMIM and HPO.  

It looks like there are two papers at OMIM (out of 55) that mention "rigidity" in patients with ACTA1 variant.  But the majority of phenotypes for this disease are those of "muscle weakness."

Should Baclofen and Botulinum Toxin be ordered lower than treatments for muscle weakness?  (A converse argument is that these are novel treatments.  In that case, would we need some sort of indication on the UI of the relative frequency of the symptom or phenotype that this drug is being used to treat?  
https://monarchinitiative.org/disease/MONDO:0008070#phenotype

**Comment by sierra-moxon** [comment]
Digging a little deeper here, with @kschaper 's help,  HPO does have the ability to add `Frequency` to their annotations and when available, `Frequency` is being passed along to the SRI reference KG.  `biolink:frequency_qualifier` is the biolink equivalent currently being populated by SRI reference KG.   @mbrush  - do we need to do anything further w/re to EPC metadata standardization for this property?

**Comment by sierra-moxon** [comment]
related: https://github.com/monarch-initiative/hpo-annotation-data/issues/808

**Comment by sierra-moxon** [comment]
from TAQA:
- lots of related issues to this one in terms of scoring - will talk about in O&O relay session tomorrow.
- questions: how to get "phenotypic frequency" into the score for these edeges.

**Comment by sierra-moxon** [comment]
note: beakers on phenotypes might not make sense (it could be a default in the UI).

**Comment by sierra-moxon** [comment]
from TAQA:
- retest.

**Comment by sierra-moxon** [comment]
Retesting after ARA ranking is in place in CI environment: Botulinum toxin is the 6th result (which isn't much of a difference). 

Also getting very strange additional results (likely from misidentified objects from SEMMEDDB)

![Image](https://user-images.githubusercontent.com/4561292/224787783-cdff88ea-f539-4724-b3eb-2400c4cec972.png)



![Image](https://user-images.githubusercontent.com/4561292/224788765-d93a67f2-7f16-4fdf-bf33-81ae37d66782.png)



![Image](https://user-images.githubusercontent.com/4561292/224788747-59a803e8-c283-47b9-b19a-154dd9341f20.png)

**Comment by sierra-moxon** [comment]
Sierra: get teh URL for the ARAX results.
