### ISSUE TITLE
unclear why some genes are yellow buttons and some don't have buttons

### ISSUE THREAD

**Issue by sierra-moxon** [NCATSTranslator/Feedback#237]
https://ui.ci.transltr.io/results?l=Glyphosate&t=3&q=cde0083a-e465-4c5c-afea-47a86ea7f94a
<img width="1156" alt="Screen Shot 2023-06-05 at 12 50 33 PM" src="https://github.com/NCATSTranslator/Feedback/assets/4561292/bafa32c9-59d8-4880-bc2b-4b13d5e1c4f0">

@dnsmith124 :)

**Comment by dnsmith124** [comment]
In the current design for the path view the starting nodes are always yellow and the end nodes are always blue! 

Earlier this year in order to emphasize edges and deemphasize intermediate nodes we changed the design so that those intermediate nodes would have no background or border on them. 

So in paths that are greater than 1 hop, any nodes that are not the start/end node will have no background color
