### ISSUE TITLE
Answer doesn't align with the question.

### ISSUE THREAD

**Issue by gloriachin** [NCATSTranslator/Feedback#242]
<img width="1221" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/2994757/a0f0b169-3c89-4577-9d6a-4e5a528d88f8">

**Comment by gloriachin** [comment]
https://ui.test.transltr.io/results?l=NPM1&t=1&q=94e7ca54-3b03-476f-b2a9-15aca0de0f98

**Comment by cbizon** [comment]
I don't think that this is actually a problem - it's perhaps a bit confusing, but the "response decreased by" is not saying that doxorubicin downregulates NPM1.  Instead it's saying that NPM1 is responsible for decreasing the response to doxorubicin.  It's in here because ARAGORN/ROBOKOP has a rule that this kind of edge tends to be associated with the chemical upregulating the gene.   It's based on the stats but I think it makes sense from a negative feedback sort of mechanism.

**Comment by cbizon** [comment]
Feel free to reopen if that doesn't make sense.

**Comment by gglusman** [comment]
Would it make sense to present the result as "doxorubicin _may upregulate_ NPM1", giving the rule and "doxorubicin response decreased by NPM1" as underlying support?

**Comment by cbizon** [comment]
Maybe - but this is the case for any inferred edge.   So I think it's a question of how do we in the UI denote an inferred edge and its support, right?
