### ISSUE TITLE
Too few results returned for "what drugs may treat fentanyl overdose?" when compared to ChatGPT; also only SEMMEDDB results are returned

### ISSUE THREAD

**Issue by karafecho** [NCATSTranslator/Feedback#246]
I'm not sure how helpful this feedback will be, but a query of _what drugs may treat fentanyl overdose?_ yielded two answers. The first one was naloxone, which is correct, but it had only three supporting publications (all three were correctly derived from SemMedDB). The second answer was for antidote, which is not very helpful and had the same three supporting publications (two of three were correctly derived from SemMedDB). 

PK=2b894aaa-5834-4547-a3db-5e88aece9e9a

Additionally, I'll note that if we removed SemMedDB, then Translator would not be able to provide a response to the querty.

Moreover, when I asked ChatGPT the same question, here is the response:

![image](https://github.com/NCATSTranslator/Feedback/assets/26254388/5066e7f5-2686-4eab-a5ac-828f4090f83f)

**Comment by sierra-moxon** [comment]
from TAQA:
gold standard is returned which is great; but very few other results. 
Eric: we see Aragorn returning lots of results now. 
Andy: sometimes when the UI hits an ARA timeout, it returns that everything is "done" but if you go back the next day it will show all the results that are coming back past the timeout.
Sarah: one of many tickets like this; if the architecture is that things can take longer than 5 mins, then we have to just show nothing in the UI?

**Comment by saramsey** [comment]
It appears that the Node Normalizer is mapping the query concept text "fentanyl overdose" to CURIE `UMLS:C0572088`. The problem is that only four vocabularies in UMLS contain that CUI:

<img width="760" alt="Screen Shot 2023-06-06 at 7 36 04 AM" src="https://github.com/NCATSTranslator/Feedback/assets/5562107/a301f3da-f43f-4197-94f0-a8ab0c0e8b0e">

and RTX-KG2 doesn't currently ETL any of them.  As for SNOMED CT, the license for that vocabulary source in UMLS has the "Category 4" restrictions:

https://uts.nlm.nih.gov/uts/license/license-category-help.html

As for the vocabulary source SCTSPA, that is the Spanish translation of SNOMED CT.

which I read and felt prohibited our being able to ETL that source into RTX-KG2.  I will look into CHV (Consumer Health Vocabulary) and RCD (Read Codes); perhaps we can ETL one or both of those.

**Comment by saramsey** [comment]
Read Codes (RCD) was last updated in 2000, so it's even older:
<img width="670" alt="Screen Shot 2023-06-06 at 7 42 42 AM" src="https://github.com/NCATSTranslator/Feedback/assets/5562107/1fb49dea-a3ac-4130-a7f6-f1688c18864b">

**Comment by saramsey** [comment]
I've created an [RTX-KG2 issue (280)](https://github.com/RTXteam/RTX-KG2/issues/280) to add the UMLS CHV vocabulary into the RTX-KG2 ETL process.

**Comment by sierra-moxon** [comment]
we no longer able to query on TEST  fentanyl overdose. Is this the correct solution to this issue?

**Comment by sstemann** [comment]
OBE you can't search for Fentanyl Overdose via MVP1
