### ISSUE TITLE
Add facet for primary information source

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#251]

**Comment by swandle06** [comment]
I would like to be able to filter the results by the primary information source as opposed to the ARA. Would it be possible to add an additional facet option to filter using the "Sources"?

**Comment by Genomewide** [comment]
Added the feature request tag to this. 

@swandle06 Can you share your reason for wanting this feature so that we can respond to this?

**Comment by gprice1129** [comment]
@swandle06 can you give some clarification on what exactly is being requested? Examples would be extremely helpful!

**Comment by swandle06** [comment]
Sorry about that.  Here is some additional detail.

When sorting through results, I have the following options on the left-hand side:
![image](https://github.com/NCATSTranslator/Feedback/assets/3343201/bc840114-13a7-4be1-811e-eed824816bf0)

It would be more helpful to me, if I could filter by Knowledge Source (https://github.com/biolink/biolink-model/blob/master/infores_catalog.yaml) rather than by ARA (i.e. could users have the option to do either/both).

**Comment by gprice1129** [comment]
@swandle06 thank you! That is very helpful.

**Comment by Genomewide** [comment]
Let's close this and add it to clickup features?
