### ISSUE TITLE
What does bupropion downregulate?

### ISSUE THREAD

**Issue by cbizon** [NCATSTranslator/Feedback#254]
I would expect dopamine receptors, which are in the high 90's.  But HDAC1 and FEV are 100's, which is unexpected?

**Comment by gglusman** [comment]
This looks like unexpected results, not necessarily 'opposite from expected'.

HDAC1 is now getting a score of just 20.6.

FEV is still at 100. Noting that the paths for FEV include "FEV downregulated by DRD1/DRD2 interacts with bupropion". Not immediately finding literature supporting the FEV/DRD link. Since the support for the edge is text mined, I'm wondering whether it's a misidentification of FEV(1) (sometimes FEV1, meaning forced expiratory volume in 1 second), which co-occurs in the literature with DRD1.

**Comment by cbizon** [comment]
Agreed with Gwenlyn that this is not particularly opposite.  Also that at least some of the FEV links seem suspicious.  For instance, this result from unsecret:

<img width="1620" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/10744350/cc83ab20-e43c-47d7-a32d-3eeb8ea46572">

The supporting text doesn't seem to map to either version of FEV that I see:
Silencing either the Drd1a/Pet1 or the Drd2/Pet1 subset of serotonergic neurons resulted in increased displays of aggressive behaviors in adult male mice, suggesting a model in which vesicular neurotransmission from these specific neuron subtypes, either during development and/or adulthood, is required to achieve normative, tempered levels of aggression in the adult.

**Comment by sierra-moxon** [comment]
FEV is no longer returned on TEST - is this the correct fix for this issue?  https://ui.test.transltr.io/main/results?l=Bupropion&i=PUBCHEM.COMPOUND:444&t=3&r=0&q=c0974f0b-008a-40c8-9125-faed9686c263

closing as complete!  but please reopen if I got this wrong.
