### ISSUE TITLE
UI Results - Checkbox for Results finished without load new results 

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#267]
In fishbowl, many users were waiting for the Translator ARA Results to return.  

In this video (which was 10 minutes but trimmed), I ran MVP2, what chemicals may downregulate EGFR.  I received a couple of "load new results" until I was at 1453 results.

https://drive.google.com/file/d/1oGPBe3z8TvC_wuHc5OOXx5NbN_B2-jZZ/view?usp=sharing

Towards the end (around 40 seconds into this video) the UI shows a "checkbox" and 1453 was the final count.  I refreshed via Chrome and 1562 was the total, but the UI never prompted "load new results"

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/913876db-e214-4ee4-9ccc-a0e9d141fe38)

**Comment by gprice1129** [comment]
We believe this is due to the timeout in the ARS. The ARS lets the UI know that the query is "done" because of a timeout, however there is no way for the ARAs to know that they should stop trying to find new results.

So if you reload the result or come back to it later, it is possible that ARAs that had previously timed out have now finished and so you get new results.

**Comment by sierra-moxon** [comment]
from TAQA:
Mark/Shervin/ARS is working on a fix for this: the background process continues here and adds to the PK saved at the ARS level.  Finishes after the cutoff?  then it will no longer be received by the ARS and the contents of the PK won't change.  timeout is 5 mins atm, but there are a few cases where things are sneaking through.
