### ISSUE TITLE
search button off-stage right

### ISSUE THREAD

**Issue by remontoire-pac** [NCATSTranslator/Feedback#269]
What drugs may treat …

“MODY”
![image](https://github.com/NCATSTranslator/Feedback/assets/2120526/19ba1951-7f2e-4aab-bd3e-08535a730a9b)

 
(1) Put “Search” button under the box (left of “Need help”) so it doesn’t get pushed off the screen to the right.

**Comment by dnsmith124** [comment]
I'm going to address this specific issue, but it should be known that due to the nature of the design for graphs and paths the screen width that we can support reliably without scrolling can only be so small before usability starts to take a hit. We're already trying to cram a lot of information into a relatively small space, and constraining the width beyond a certain point causes some of the elements to break down.   

I'd be curious to know the resolution of your screen @remontoire-pac?

**Comment by remontoire-pac** [comment]
I was initially just talking about the front screen with the query/box
before any results are displayed; I don't know enough about how re-flowing
pages works, etc., to advise more properly on that front.

I am 2736 x 1824 (Microsoft Surface 7+ with Windows 10-Pro) using Chrome or
Firefox browsers at 110% default zoom.

**Comment by dnsmith124** [comment]
That is really interesting, I was definitely expecting your screen to be a much smaller resolution! I don't think I've worked with the site at anything above the default zoom value, I'll do some testing and adjust the styling on the front page to accommodate.

**Comment by dnsmith124** [comment]
I've resolved this issue locally and pushed a fix to our develop branch. That fix has been deployed to dev!

Closing this one out.
