### ISSUE TITLE
hide irrelevant facet browsing options

### ISSUE THREAD

**Issue by remontoire-pac** [NCATSTranslator/Feedback#273]
(7) Do we really need facet checkboxes on the right when they don’t have a chance to do anything? For example, in my “MODY” query, most of the checkboxes say “10” meaning that they are true for 10 of 10 results – so selecting them filters nothing, ergo why have them as options at all?

![image](https://github.com/NCATSTranslator/Feedback/assets/2120526/3de3c097-bcc4-47b8-9957-0bda6f038d2b)

**Comment by remontoire-pac** [comment]
This problem should be addressed dynamically, ideally, i.e., once I make a selection, the entire facet bar should be rebuilt -- but not doing this will need a "reset" button for the facets (individually or all -- "clear filters")

**Comment by Genomewide** [comment]
this could be addressed by the facet server, but I am not sure I would change it.  

This is something that we could send out to the broad group testing. We ask what number they expect to see in the facets based on some simple examples.

**Comment by remontoire-pac** [comment]
It sounds like you feel my suggestion might increase cognitive load for the
user rather than decreasing (my intent). This one may be worth a
discussion, since there are multiple ways to accomplish this besides my
suggestion.

**Comment by dnsmith124** [comment]
For that particular facet this is more likely to occur because it only requires a particular biolink type to exist anywhere in a result. When you're dealing with such a small result set (10 items) this can happen, but I don't really see it happening often with larger result sets (which in my experience are far more common). 

Regardless those facets being present still present value to the user, despite their counts being the same, because they clearly display that those biolink types exist within the results. By removing the items with identical counts we'd be telling the user that the only type available within the result set is 'Biological Entity', even though that would not be the case. There could be a user interested in proteins and if we hide those facets they may assume there aren't any protein nodes within the result set.  

I do agree that the facets will have a problem with regards to cognitive overload, particularly once we add more, and we're looking into a few different ways we can address that!

**Comment by remontoire-pac** [comment]
How about greyed out check boxes with the check ON when the facet is
already true for all current results?

**Comment by gprice1129** [comment]
After some internal discussion we do not believe this is a good idea to implement. Closing, but if anybody feels strongly that we should implement this please reopen so we can discuss.
