### ISSUE TITLE
visually align shared items across paths

### ISSUE THREAD

**Issue by remontoire-pac** [NCATSTranslator/Feedback#276]
(10) Preserve alignment in the paths whenever possible; in this example, one could do this with a “long line” on the first row, making the first instance of miglitol appear on the far left.

![image](https://github.com/NCATSTranslator/Feedback/assets/2120526/dc87a536-2d6f-4452-8db6-1a19cfb7225f)

**Comment by dnsmith124** [comment]
Definitely worth testing!

**Comment by sstemann** [comment]
@desiyopp has this been tested?

**Comment by Genomewide** [comment]
Where would treats go in the example above?

**Comment by desiyopp** [comment]
This has been user tested! https://app.usabilityhub.com/tests/43dd66ff5d55/results/da8e799f73e7
It seems that users prefer the paths to be left aligned rather than right aligned. @sstemann @Genomewide @dnsmith124

**Comment by dnsmith124** [comment]
Given the response from Desi's user testing, I think the right move is to align paths on the left rather than the right. This is a pretty simple change, so if we get feedback from more qualified users than those on usability hub that refutes our findings, we can revert it very easily. 

I'll implement it now, and update the ticket once it's been deployed

**Comment by mbrush** [comment]
My understanding of the suggestion was more of an 'end-justified' view, where the start node is pinned to the left and hte end node is pinned to the right, e.g. something like:

![image](https://github.com/NCATSTranslator/Feedback/assets/5184212/e5478ed0-abd0-45c3-8cb7-8190f43f7cd4)

**Comment by dnsmith124** [comment]
@mbrush you're absolutely right, I should have clarified our stance earlier in the ticket. As a team we determined that the 'end-justified' view in the original request was less effective than a more columnar-focused one due to the variation in structure inherent to such a view, particularly because the paths list is already a potentially overwhelming area with regard to the amount of information and text it contains.

**Comment by dnsmith124** [comment]
Paths are now left-aligned on CI per the user testing results linked above. Here's an example: https://ui.ci.transltr.io/demo/results?l=Bethlem%20Myopathy&i=MONDO:0008029&t=0&q=7968cb7f-1697-445e-85c2-dbaf5ab638f9

Closing.
