### ISSUE TITLE
larger range of display items "per page"

### ISSUE THREAD

**Issue by remontoire-pac** [NCATSTranslator/Feedback#277]
![image](https://github.com/NCATSTranslator/Feedback/assets/2120526/d3e0d85b-fee8-42c6-83f0-84655cb17a2d)

Include a larger range -- i.e., 40, 80, 160 in addition to what is there...

**Comment by Genomewide** [comment]
yeah, lets have a 100 as well? 
Would we need to auto close graphs that are open?

**Comment by remontoire-pac** [comment]
regular steps (either linear or log)?

**Comment by remontoire-pac** [comment]
Dynamic and data-driven choices?

**Comment by remontoire-pac** [comment]
Actually I think I am trying to address two problems: need for a larger
choice and desire to have the math behind the choices be not jarringly
arbitrary (which is why initially suggested 40, 80, 160, choices that
naturally followed 5, 10, 20).

**Comment by dnsmith124** [comment]
I agree that a larger range of options, but I don't think that having those values be determined dynamically is the right move. It's standard when implementing pagination to provide a set list of values the user can select among, with the only dynamic option being perhaps an 'all' option.

Ultimately the approach we end up going with will be informed by user testing, and I'm absolutely open to having my mind changed, but as of now I don't think being inconsistent with what options are available to the user in terms of how many results to display is a good idea. 

I'm leaning toward changing it to `10, 20, 50, All`, as I think this lines up best with the established standard, but again we'll test it with users and see what the results are.

**Comment by remontoire-pac** [comment]
I like "all" especially with 5, 10, 20. Maybe just add to what you have?
10, 20, 50 while maybe common, exemplifies jarringly arbitrary. Steps are
not regular in linear or logarithmic sense.

**Comment by Genomewide** [comment]
Agree we should stick with standard #’s.

From: David Smith ***@***.***>
Date: Tuesday, June 6, 2023 at 4:27 PM
To: NCATSTranslator/Feedback ***@***.***>
Cc: Andy Crouse ***@***.***>, Comment ***@***.***>
Subject: Re: [NCATSTranslator/Feedback] larger range of display items "per page" (Issue #277)

I agree that a larger range of options, but I don't think that having those values be determined dynamically is the right move. It's standard when implementing pagination to provide a set list of values the user can select among, with the only dynamic option being perhaps an 'all' option.

Ultimately the approach we end up going with will be informed by user testing, and I'm absolutely open to having my mind changed, but as of now I don't think being inconsistent with what options are available to the user in terms of how many results to display is a good idea.

I'm leaning toward changing it to 10, 20, 50, All, as I think this lines up best with the established standard, but again we'll test it with users and see what the results are.

**Comment by remontoire-pac** [comment]
I'm still not sure I'm communicating my suggestion carefully. Apologies.

I want to make sure we are all saying the same thing before I can decide
whether we agree or not. I'm definitely willing to concede (and probably
also willing to be difficult), but I don't want to do either by accident.

What do you mean by "*standard*"?

I'm actually saying that I'm generally *not* satisfied by the types of
choices that I see everywhere on websites (and which therefore might be
considered "standard"), like 10, 20, 50. *I do not see a pattern in 10, 20,
50.* The closest easy pattern for me would be 10, 30, 50 (see below), and
the fact that I would be happy with 10, 22, 50 might be illustrative.

I'm advocating using what I might call "standard*ized*" choices (even if
most people or groups wouldn't do it):

10, 20, 40 (logarithmic, doubling each time)
10, 20, 30 (linear, adding N each time)

Let me know what y'all think ...

Best,
Paul

**Comment by dnsmith124** [comment]
I believe I'm following you Paul, I just think we disagree on the importance of the values following a mathematical sequence.

I appreciate that it would be more satisfying if they did, but ultimately the goal of the feature is to provide the user with the means to customize the number of results per page in a way that is most effective, meaning a number of options that satisfy as many users as possible while not providing so many options that the decision space becomes overwhelming. 

The values themselves should be chosen based on their ability to satisfy that goal, not based on whether they follow a mathematical sequence. A logarithmic sequence (10, 20, 40) doesn't provide a high enough value at the top end to provide a substantially different experience for the user, which is doubly true for a linear sequence. 

While the sequence `10, 20, 50, All` doesn't follow a pattern, it serves as a more effective means of allowing the user to determine a wide range of options for results per page than defaulting to following a mathematical sequence. 10 serves as a functional minimum, since if fewer results than that are shown the height of the UI isn't fully utilized due to the more static height of the sidebar. 20 is substantially more than 10, and 50 is substantially more than 20, with all three of those options providing a noticeably different browsing experience. All is the wildcard option that most will not use, but it's important for it to be available for the minority of users who will use it.  

At the end of the day @desiyopp will test several sets of values with our users, and whatever the consensus is there is likely what we'll go with.

**Comment by remontoire-pac** [comment]
Very good. Thanks for your explanation. More than anything I wanted to make
sure we were talking about the same issue in the same terms. As I said, I'm
willing to concede the point, but I didn't want to do either by accident.
Let me know if you want me to suggest any sets of values for @desiyopp to
test with users. Best, Paul

**Comment by remontoire-pac** [comment]
Given that I think I see what general range(s) we are trying to
accommodate, I offer the following 4 choices for consideration:

"4, 16, 64, All"
"4, 20, 100, All"
"2, 10, 50, All"
"3, 15, 75, All".

**Comment by Genomewide** [comment]
I like the idea of a number progression that has a numeric pattern. However, we looked at a number of options, and there is a standard that people are used to. We ran out of time to test if the alternate pattern was more favorable. So, we are going to have 5, 10, 20, 50. We could revisit this later. I think it would be interesting to know what our audience thinks because they will not be the same representation as say an Amazon user.   I am closing this for now though.
