### ISSUE TITLE
Inconsistent use of chemical roles (e.g. 'statin') between data sources leads to inconsistent results in the UI

### ISSUE THREAD

**Issue by Genomewide** [NCATSTranslator/Feedback#28]
Results for Huntington's disease included multiple statin drugs.  Fluvastatin has the predicate 'subclass_of' statins.  The other statins did not have this predicate, but they are subclasses of statins.

**Comment by Genomewide** [comment]
Why would FLUVASTATIN be a subclass of Statins and the remaining stating not be? Results include Rosuvastatin and Pravastatin. These two did not have 'subclass of'. The remaining statins were not there.  


Link to what treats Huntington's Disease:
ui.transltr.io/results?q=3176389f-9e75-4e2e-9beb-bed32055de13



![Image](https://user-images.githubusercontent.com/55069176/213814883-6379488d-cd74-4f44-84a0-4ff11eb52582.png)



![Image](https://user-images.githubusercontent.com/55069176/213815058-81b8a6f8-c4bb-4826-ae63-cf6976553572.png)

**Comment by Genomewide** [comment]
Fluvastatin is in the ARAX results rank 21.
The remaining statins came from other ARAs.

**Comment by sierra-moxon** [comment]
From TAQA:
Aragorn/BTE - rule-based approach: if the chemical I'm looking for is a subclass of a family, then we can use that path in the rule.  But if a ML approach by pathfinding, then if the black box approach finds one drug in one case and another drug in another case, it's not using statins, so no expectation that it would use statins
filling in of the paths is the second step to fill in the statin path, so it wouldn't do this
Not intuitive from the UI, coming from ARAX.  - pops out because this has "statin" in the name, might not be that prevalent or unintuitive in most cases. Ok closing until next report/etc. :)
