### ISSUE TITLE
Hyperbaric oxygen treats Sexual And Gender Identity Disorders

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#298]
## Steps to reproduce:
So many things wrong with this one

**Comment by dkoslicki** [comment]
#287 #286 #288

**Comment by sierra-moxon** [comment]
Noting that `gender identity disorder` is a MONDO term: https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0001500&lang=en&viewMode=PreferredRoots&siblings=false
but we'd eliminate hyperbaric oxygen from these results if we used MONDO terms and synonyms in autocomplete only.

@suihuang-ISB - can you take a look at the results for this query and see if they make sense (I see improving agent in the sources field) https://ui.test.transltr.io/results?l=Fetal%20Alcohol%20Spectrum%20Disorder&t=0&q=18898dee-e026-4d63-810b-9541da4187db.  I don't know how to judge if these results are some that you can suppress or otherwise better elucidate in terms of evidence?

**Comment by sierra-moxon** [comment]
https://github.com/monarch-initiative/mondo/issues/6366
https://github.com/monarch-initiative/mondo/issues/6365
https://github.com/monarch-initiative/mondo/issues/6364
https://github.com/monarch-initiative/mondo/issues/6363

**Comment by gaurav** [comment]
"gender identity disorder" (MONDO:0001500) has now been added to the Blocklist (https://github.com/NCATSTranslator/Blocklists/blob/c899296eb31c9f5c580990d884c54a45972403d2/blocklist.yaml), but I'll keep this open until we close https://github.com/NCATSTranslator/Blocklists/issues/1, which will allow us to block all child terms of "gender identity disorder" as well.

**Comment by gaurav** [comment]
`gender` no longer matches anything on https://ui.ci.transltr.io/, closing.
