### ISSUE TITLE
wonky name-matching policies in autocomplete

### ISSUE THREAD

**Issue by remontoire-pac** [NCATSTranslator/Feedback#312]
and not reproducible

**Comment by sierra-moxon** [comment]
following up with @remontoire-pac  - this is another instance of:
"autocomplete results change on each addition of a new letter, but suggestions, after the new letter is added, are a completely different set of results."

**Comment by remontoire-pac** [comment]
important new nuances:
* the "new letter" added might even be a space
* deleting the new letter does not bring back the original results

**Comment by dnsmith124** [comment]
It sounds like the issue here is twofold: 
1. The suggestions returned by the autocomplete are significantly different when a search term changes by only a single letter
2. Suggestions are not consistent when the same input string is searched more than once. 

Is that correct? If so I think the former problem should be resolved by the biolink type selection feature planned for the name resolver. The latter sounds like a problem not with the UI but with the Name Resolver or Node Normalizer not consistently returning the same terms for a given input string.

**Comment by remontoire-pac** [comment]
I have seen both of those behaviors separately and (I think) together. I
can try to experiment more carefully if that would be helpful.

**Comment by gaurav** [comment]
Tracking at https://github.com/TranslatorSRI/NameResolution/issues/64

**Comment by gaurav** [comment]
This should be fixed once UI switches over to the new NameRes (with the possible exception for genes, but we're trying to fix that now). I'll close once we can confirm that this is the case. We now have some testing tools available to make sure this works correctly in NameRes.

**Comment by remontoire-pac** [comment]
I was unable to reproduce the earlier behavior, and poking at the
auto-complete just now left me with the impression that it is behaving more
"naturally". PAC
