### ISSUE TITLE
Searching for Long Covid-19, different results depending on which matched query name is chosen

### ISSUE THREAD

**Issue by cartmanbeck** [NCATSTranslator/Feedback#321]
https://ui.test.transltr.io/results?l=Long%20Covid-19&t=0&q=1c937be0-508c-48c0-9603-a2ed87062e87 
(Long COVID-19)

and 

https://ui.test.transltr.io/results?l=Post-acute%20Covid-19%20Syndrome&t=0&q=444c343a-aab1-4732-9d46-8ca2b91581a0
(Post-acute Covid-19 Syndrome)

From what I can see, the results from these two searches should all be returned for both searches. These two concepts should be considered equivalent.

**Comment by dnsmith124** [comment]
This particular issue should be _sort of_ resolved by the recent change to only return MONDOs in 'what drugs may treat' queries, as the first example (Long COVID-19) is a UMLS, and the second example is a MONDO. 

Not sure where the merging needs to occur on these two terms, but since they have different identifiers they return different results.

**Comment by andrewsu** [comment]
I'm pretty sure the observed behavior is because Node Normalizer doesn't equate those entities, presumably because there is no source that provides the mapping between them.  

https://nodenorm.transltr.io/1.3/get_normalized_nodes?curie=MONDO:0100233 -- no equivalent identifiers to `MONDO:0100233`
https://nodenorm.transltr.io/1.3/get_normalized_nodes?curie=UMLS:C5433293 -- maps `UMLS:C5433293` to `MESH:D000094024`, `MEDDRA:10085503`, `MEDDRA:10085504`, `NCIT:C179263`

I don't think this is a Node Norm or Translator bug per se, but a current deficiency in the underlying knowledge sources (which is something Translator should always assume will be imperfect).  I think one solution is to create an issue or pull request in https://github.com/monarch-initiative/mondo to add the mappings...

**Comment by sierra-moxon** [comment]
I agree we should assume the mappings will be imperfect, and I think we should limit the autocomplete to the imperfect but curated set of terms in MONDO or HP (or their synonyms) for this particular MVP for September.  If we do that, we would limit the choices in the autocomplete and the user would have to choose the MONDO term (or one of its official synonyms), but this also means they would find consistent results returning from their search.

**Comment by sierra-moxon** [comment]
https://github.com/monarch-initiative/mondo/issues/6341 - MONDO issue for this.

**Comment by gaurav** [comment]
- [ ] We definitely want to combine these two COVID-19 identifiers. It looks like MONDO has fixed this: @gaurav to check that this change has been imported into NodeNorm and NameRes.

**Comment by cartmanbeck** [comment]
I have confirmed that this has been fixed in CI. closing now.
