### ISSUE TITLE
create a list of known chemicals that make known diseases worst

### ISSUE THREAD

**Issue by sierra-moxon** [NCATSTranslator/Feedback#329]
from TAQA:  
Chris B: I wonder if there's a general strategy in running treats for a bunch of things that can be adverse events and making sure we don't provide results that make things worse.

the ask here is to get a set of test cases for Richard/Testing.

**Comment by sandrine-m** [comment]
Is this related to adverse events (see #147)? Could this list become a gold standard for benchmarking ADE knowledgebases?
I did a quick data scouting on adverse events from SIDER:
Re: adverse events suggestion
upon suggestion from @cbizon , MolePro is exposing knowledge of adverse event data from [SIDER](http://sideeffects.embl.de/). Question araised during TAQA meeting about data value of such dataset (aka how noisy it is?).
Here is what I could find about data value for this dataset (from litterature):

not benchmarked extensively ([source: papercode](https://paperswithcode.com/dataset/sider))
large knowledge base, NLP-based ([source: sider paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4702794/))
"the obtained lists [from SIDER] typically mix rare and common ADEs alongside those caused by misuse or abuse of drugs [..] determining what constitutes a “true” effect of a drug may be unclear, and from a functional perspective – may depend on the context in which this question is asked, as well as the drug use patterns and prevalence of the adverse effect. For example, in comparing SIDER and OFFSIDES, Cheng et al.[7](https://www.medrxiv.org/content/10.1101/2021.11.01.21265741v2.full-text#ref-7) found relatively little overlap between them (7,741 common pairs, out of 418,532 OFFSIDES pairs and 120,236 SIDER pairs) suggesting that it is common for ADEs described in package inserts not to be reported to FAERS, and vice versa." ([source: Medrxiv 2021 paper](https://www.medrxiv.org/content/10.1101/2021.11.01.21265741v2.full#ref-6))
Conclusions on data value:

SIDER will suffer NLP biases for complex contexts (dosage, frequency, clinical context... etc.)
SIDER has poor overlap with FAERS data
SIDER provides data only on marketed medicines
current benchmarks are mainly measuring overlap/reproducibility between NLP extracted knowledgebases or/and predicted ADE from algorithms (no gold standard curated list - though the Medrxiv paper could be interesting to look at when/if published).

**Comment by sierra-moxon** [comment]
we now have over 600 P/F tests.  closing as complete.
