### ISSUE TITLE
What drugs may treat primary ciliary dyskinesia? returns results for paraneoplastic cerebellar degeneration (PCD)

### ISSUE THREAD

**Issue by karafecho** [NCATSTranslator/Feedback#337]
This issue is presumably due to a match to a shared acronym: PCD. Moreover, "treats" is being applied incorrectly; there is no primary knowledge source; and two identical papers are returned as supporting evidence.

PK = fe1e5e8e-0958-44c7-b6e4-4fec8fb866b7

![image](https://github.com/NCATSTranslator/Feedback/assets/26254388/e8d49760-359e-4886-9ac1-0e9786ce94c9)

**Comment by sstemann** [comment]
i believe this is from TMKP and BTE

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/452b7dfe-b1a4-4fac-be8a-7fe77e8b5ef0)

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/265054ce-f487-4a99-921e-80a1ea1c45d8)

@bill-baumgartner could you take a look?

**Comment by bill-baumgartner** [comment]
Thanks. This is an ongoing issue with how we use (or don't use) abbreviations. I've linked this to one of our internal tickets.

With regard to the same paper showing up twice in the supporting documents, I think this might be because we return 3 sentences (wrongly) supporting this assertion. One of them is in the abstract and is returned with a PMID. The other two come from the body of the document and are returned with PMC IDs. So my guess is that the PMC ID gets converted to the PMID somewhere, but the UI maybe doesn't check for duplicates after the conversion?

**Comment by bill-baumgartner** [comment]
A related question (which should probably go in a different issue perhaps) that I have is, when the supporting evidence is from a text-mined source, should the snippet that is shown in the evidence tab be the snippet of text that was mined? Currently, the snippet always seems to be the beginning of the abstract. This is demonstrated in the screenshot of the evidence tab at the top of this issue.

**Comment by bill-baumgartner** [comment]
A general solution to the acronym issue described in this issue has been implemented and was included in a past release. The duplicate publication issue has also been resolved in a past release. Closing this issue as all aspects have been addressed.
