### ISSUE TITLE
what we would like to see in the CJD "rare" disease query

### ISSUE THREAD

**Issue by sierra-moxon** [NCATSTranslator/Feedback#338]
from Jared Roach: 

This is the kind of result from Translator that would get a plaudit from me for CJD:
1. CJD is a problem with a misfolded protein.
2. AD is a problem with another misfolded protein.
3. Antibodies agains the AD misfolded protein have been tentatively approved for treatment of AD.
4. Maybe an antibody against the CJD misfolded protein would be similarly effective for CJD.

**Comment by sierra-moxon** [comment]
@jaredroach 

I ran this on CI today:
https://ui.ci.transltr.io/results?l=Creutzfeldt%20Jacob%20Disease&i=MONDO:0005357&t=0&q=dffe2edf-4f50-4d8f-85b2-763902c5dd13

you're interested in seeing papers like this in at least some results?  https://www.thelancet.com/article/S1474-4422(22)00082-5/fulltext  ? 

What would be the chemical here, that would lead to this paper (sorry, not a biologist here :D )

**Comment by gglusman** [comment]
@sierra-moxon Perhaps https://meshb-prev.nlm.nih.gov/record/ui?ui=D000911

**Comment by sierra-moxon** [comment]
Is this a case where we want to see generic results? :)

**Comment by jaredroach** [comment]
I guess we can call "Immunoglobulins, intravenous: 25 Paths that may treat Creutzfeldt Jacob Disease" a win. But "Immunoglobulins, intravenous" shows up with a score of 16.0/100 on page 67/79 pages of 784 results. And even then, the 25 paths that are generated are based on vague similarities of phenotypes (e.g., b/c Immungolobulins treat some brain dzs, they might also treat CJD). There is not logic based on the fact that CJD is a misfolded protein (or if there was, it didn't leap out at me). So Translator gets the right result here because it is cluster bombing the user with hundreds results, and then cluster bombing again with dozens of vague explanations for each result. One could use such data to confirm many hypotheses. To actually land on an answer one did not already know of — is another issue.

**Comment by cbizon** [comment]
Should this be converted into a test asset?

**Comment by sierra-moxon** [comment]
@jaredroach - any chance we could recruit you to add this is as a test asset here: https://docs.google.com/spreadsheets/d/1wAQaFEtFqAvp2fbTZIe-2ObF9zUU_cmXILfU8SzUWe0/edit

reach out if you need a primer on curating that spreadsheet @jh111

**Comment by jaredroach** [comment]
Done. = Asset:627

fwiw, here is a report of PRN100, a monoclonal antibody used to treat CJD. 
PMID: 35305340
Also in the news: https://www.nihr.ac.uk/news/world-first-treatment-for-cjd-shows-promising-early-results/30248
I could not find PRN100 in the current UI autofill, so maybe the generic "monoclonal antibody" is the best we can do.

I set it to "Acceptable" answer. As there didn't seem to be a choice for "near top 10". But it might actually be top 10. I think we need a 1.5 intermediate between 1_TopAnswer & 2_Acceptable. I remain unsure whether "Acceptable" means a bad answer that will not be penalized, or a good answer that just is not in league with the best answers.

Monoclonal antibody is a good answer. It loses points because it is not as specific as PRN100. And since PRN100 is not in the knowledge graph, maybe it should not be dinged. But maybe with only one PubMed article without followup in the past decade on just a few patients, it is kind of a weak clinical suggestion. But I think it is a strong research idea that could spark further research.
