### ISSUE TITLE
MVP2, What genes does Adalimumab downregulate

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#340]
https://ui.test.transltr.io/results?l=Adalimumab&t=4&q=f75c891d-5c6b-43fc-bee9-1dee56b7b059

https://arax.ci.transltr.io/?r=f75c891d-5c6b-43fc-bee9-1dee56b7b059

These are all of the results:
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/ab154746-461c-4ed7-9964-76e265d6e113)

Looks like they are all ARAX/chembl
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/2c4fa426-1aa8-4fbf-bd5b-169d58448300)

**Comment by edeutsch** [comment]
Although no problem is specifically mentioned, I infer that the problem is that there are multiple results that are all TNF? If that's the problem, here's what I found out:

1. All 8 of these results are coming from molepro:
![image](https://github.com/NCATSTranslator/Feedback/assets/12707718/a029a470-1407-440f-acf5-56fdc1c34fc3)

2. Our previous implementation of our NodeSynonymizer would have merged all these because all these TNFs would have been merged based on name: https://arax.ncats.io/?term=ENSEMBL:ENSG00000228849 But this behavior in general generated complaints in the past.

3. However, our latest version of our NodeSynonymizer is now designed to honor all SRI Node Normalizer clusters. i.e. NodeSynonymizer will now not merge that which is not merged in SRI Node Normalizer.

4. All these entries appear to be separate clusters in SRI Node Normalizer, so we now treat them as separate entities.
https://arax.ci.transltr.io/?term=ENSEMBL:ENSG00000228849

So I think the answer here is: all 8 of these things are different concepts in the eyes of the SRI Node Normalizer (and therefore presumably MolePro) (and therefore ARAX), and so therefore these are 8 different things (that all have the same name) (and maybe should be merged but are not)

So I don't think there's anything for ARAX to fix. If we decide that these are the same thing, and SRI NN is updated to merge these into the same cluster, then the next build of NodeSynonymizer will follow suit.

**Comment by sierra-moxon** [comment]
@gaurav - any chance you could give us an idea of which mappings are missing in Babel/NN?

**Comment by cbizon** [comment]
It looks like this is because ensembl gives the same gene name (TNF) to the "same" gene on different haplotypes.  TNF is living in an MHC region, and in each haplotype it gets a different identifier.  So presumably we're missing a within ensembl mapping of some kind associating these gene identifiers.

**Comment by gaurav** [comment]
It looks like we might be using NCBIGene's mappings from NCBIGene to Ensembl, which only has a single Ensembl identifier. It looks like Ensembl's mappings (downloaded from BioMart) might have these additional mappings in it. I'm following this up on this at https://github.com/TranslatorSRI/Babel/issues/153.

**Comment by cbizon** [comment]
@edeutsch just to check, is there a data source that is actually providing edges for all of these ensembl id's?

**Comment by edeutsch** [comment]
> @edeutsch just to check, is there a data source that is actually providing edges for all of these ensembl id's?

yes, MolePro.

**Comment by cbizon** [comment]
It looks like MolePro is getting these from Chembl.  @vdancik does chembl use all of these identifiers?   Or is  MolePro doing an expansion of some kind?

**Comment by sstemann** [comment]
cannot replicate this specific issue, since adalimumab is not supported in [pubchem](https://pubchem.ncbi.nlm.nih.gov/compound/Adalimumab), it cannot be used to query 

resveratrol can be used in this query, it also may down regulate TNF.  From what I can tell this issue is resolved by [insert all of the work from June 2023 to Feb 2024]

https://arax.ncats.io/beta/?r=59f2eea3-eb5b-4bf6-b0c1-90fb2b94a5e0

https://ui.test.transltr.io/main/results?l=Resveratrol&i=PUBCHEM.COMPOUND:445154&t=4&r=0&q=59f2eea3-eb5b-4bf6-b0c1-90fb2b94a5e0
