### ISSUE TITLE
Answer is not correct given the evidence provided for the test UI.

### ISSUE THREAD

**Issue by gloriachin** [NCATSTranslator/Feedback#351]
The query is: What gene is upregulated by venetoclax?

<img width="1212" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/2994757/02cc2277-a66d-4295-afe6-2b108604c7a7">
All evidence shows BCL2 has decreased activity caused by venetoclax, but the answer is wrong, which shows up-regulation. 

link to the query: https://ui.test.transltr.io/results?l=Venetoclax&t=3&q=8de98c9f-05f2-4bec-bb64-39de4a49b7b1

**Comment by Genomewide** [comment]
From the arax UI - this appears to be from ARAX - don't know who to send this to.

In speaking to other ARAs about what is up with these, it was mentioned that training after the qualified predicates cause some issues.  So, previously, when the predicate was 'regulates' that could mean up or down. However, now the predicate 'regulates' with modifier 'decreases'  should never be used as 'could upregulate' in the model. Not sure if that is the issue here, but it was for some. 


<img width="1616" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/55069176/1f408a33-a37a-4ff6-aa31-3f0fe8e02c12">

**Comment by edeutsch** [comment]
If I understand the issue correctly, this may be due to results from MolePro. I think the original query is this:
```
{
  "edges": {
    "t_edge": {
      "attribute_constraints": [],
      "knowledge_type": "inferred",
      "object": "on",
      "predicates": [
        "biolink:affects"
      ],
      "qualifier_constraints": [
        {
          "qualifier_set": [
            {
              "qualifier_type_id": "biolink:object_aspect_qualifier",
              "qualifier_value": "activity_or_abundance"
            },
            {
              "qualifier_type_id": "biolink:object_direction_qualifier",
              "qualifier_value": "increased"
            }
          ]
        }
      ],
      "subject": "sn"
    }
  },
  "nodes": {
    "on": {
      "categories": [
        "biolink:Gene"
      ],
      "constraints": [],
      "is_set": false
    },
    "sn": {
      "categories": [
        "biolink:ChemicalEntity"
      ],
      "constraints": [],
      "ids": [
        "HMDB:HMDB0247760"
      ],
      "is_set": false
    }
  }
}
```

ARAX gets answers from MolePro that include this:
```
        "e10-VgcB6Eozsq": {
          "attributes": [
            {
              "attribute_source": "infores:ctd",
              "attribute_type_id": "biolink:OrganismTaxon",
              "attributes": [],
              "description": "Homo sapiens",
              "original_attribute_name": "TaxonID",
              "value": "NCBITaxon:9606"
            },
            {
              "attribute_source": "infores:ctd",
              "attribute_type_id": "biolink:relation",
              "attributes": [],
              "original_attribute_name": "Relation",
              "value": "results in decreased activity of",
              "value_type_id": "string"
            },
            {
              "attribute_type_id": "biolink:publications",
              "value": [
                "PMID:26214592"
              ],
              "value_type_id": "linkml:Uriorcurie"
            }
          ],
          "object": "NCBIGene:596",
          "predicate": "biolink:affects",
          "qualifiers": [
            {
              "qualifier_type_id": "qualified_predicate",
              "qualifier_value": "biolink:causes"
            },
            {
              "qualifier_type_id": "object_aspect_qualifier",
              "qualifier_value": "activity"
            },
            {
              "qualifier_type_id": "object_direction_qualifier",
              "qualifier_value": "decreased"
            }
          ],
          "sources": [
            {
              "resource_id": "infores:ctd",
              "resource_role": "primary_knowledge_source"
            },
            {
              "resource_id": "infores:molepro",
              "resource_role": "aggregator_knowledge_source",
              "upstream_resource_ids": [
                "infores:ctd"
              ]
            }
          ],
          "subject": "HMDB:HMDB0247760"
        },
```

So I'm thinking:
1. MolePro isn't answering the question that ARAX asked of it correctly
2. ARAX doesn't check to see if the answers accurately reflect the question and just proceeds with the answers it received, assuming they are correct.

So I'm thinking that the original issue is in MolePro
https://arax.ncats.io/devED/?r=144298

**Comment by vdancik** [comment]
@edeutsch indeed, the issue is in how MolePro handles qualifier constrains. The next version should handle such queries correctly.

**Comment by cbizon** [comment]
End of July. Move to Milestone B

**Comment by cbizon** [comment]
@vdancik can you comment on the progress here?

**Comment by sandrine-m** [comment]
RETEST today on [CI](https://ui.ci.transltr.io/results?l=Venetoclax&i=CHEMBL.COMPOUND:CHEMBL3137309&t=3&q=9e2758cc-13bf-42da-8396-1209042eecea) (with new MolePro release):
I could not reproduce, the only paths on BCL2 are:
<img width="1031" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/66342541/11eb01f7-ffcb-4f46-8309-0b6fba7cfbd7">
I ran the oposite direction question ([PK](https://ui.ci.transltr.io/results?l=Venetoclax&i=CHEMBL.COMPOUND:CHEMBL3137309&t=4&q=600f6b5f-6c50-4ad2-9d79-214707642011)):
so that @gloriachin you can check as well the literature there to verify. It looks like we can close the ticket, what do you think @gloriachin ?

**Comment by gloriachin** [comment]
I think the results now make more sense. I am going to close the issue.
