### ISSUE TITLE
Add ability to send feedback on specific results

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#352]
The feedback form is at the high level.  Requesting the ability to send feedback on specific results/paths/edges.

**Comment by gprice1129** [comment]
@sstemann would there be a significant improvement to the bug report versus just sharing a screenshot?

**Comment by Genomewide** [comment]
One issue that would help this is to have it open on a new tab. This would be a small easier change. @sierra-moxon Would that solve the original issue?

**Comment by dnsmith124** [comment]
Implementing this would require a fairly significant increase in the complexity of how sending feedback works, and before we commit to doing it I want to make sure it's worth the amount of work required per Gus' question.

We would need to implement:
1. A selection mechanism of some sort for the user. This means design time to figure out how to add in a send feedback button to the places that don't already have one. Thankfully we already have a button for this on the result level, but for paths and edges we would need to figure out how to display this to the user without taking up too much screen real estate. Would we support the user being able to select multiple entities, or just a single entity? 
2. An updated form that displays to the user what exactly they've selected as the specific entity they want to have included in their feedback submission. This could be relatively simple like: _Result:  **blank**_ or _Edge: **blank treats blank**_. 
3. A solution for how to store the selected result/path/edge and communicate that to github, which is then expanded and displayed in the ticket. Not a huge deal, but worth noting as it would require coordinating with Max to update the endpoint that we send feedback requests to in order to have them turned into tickets here.

**Comment by gprice1129** [comment]
This isn't a priority for the UI team this release cycle.

**Comment by sierra-moxon** [comment]
@gprice1129 - shall we close?  or is there an opportunity for work here?  I am closing, please reopen if I got this wrong.
