### ISSUE TITLE
Improve context when large networks/displays may confuse the user what "page" they are on

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#354]
If you've scrolled in a network or set of paths and click the browser Back you may actually be wanting the modals or paths/networks to be collapsed but there's no clear way of doing that right now.

In a screen like this, a user may click Browser Back to get back to the list of results, but really they are on the list of results but dont know how to collapse 
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/96a38935-c7da-4746-ac3b-33da4f3f738f)

**Comment by sstemann** [comment]
this needs to be re-tested with Christine.

**Comment by sierra-moxon** [comment]
@sstemann - is this closable now? :)

**Comment by dnsmith124** [comment]
@sierra-moxon I believe the presence of the "are you sure you want to leave this page" modal that pops up when you hit the back button on the results page is enough of a solution to close this ticket, but the UI is also currently planning an overhaul of the browser back button in order to further address this issue (and a few others).
