### ISSUE TITLE
mesh subject heading pages not as helpful as wikipedia, cdc.gov, drugbank, etc in defining action, usage of the drug returned

### ISSUE THREAD

**Issue by sierra-moxon** [NCATSTranslator/Feedback#355]
https://ui.ci.transltr.io/results?l=Cerebral%20Palsy&t=0&q=8cd99a3c-0b5f-4c1f-a52c-efc27de2b316 

Filgrastim - https://id.nlm.nih.gov/mesh/D000069585.html 
No real information on this page about what this is typically used to treat, how it works, etc.

better description choices: 
https://www.cdc.gov/nceh/radiation/emergencies/neupogenfacts.htm
https://www.cancer.gov/publications/dictionaries/cancer-terms/def/filgrastim
https://medlineplus.gov/druginfo/meds/a692033.html
https://en.wikipedia.org/wiki/Filgrastim
https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL1201567/

**Comment by gaurav** [comment]
Drugbank has a pretty good description of this drug as well: https://go.drugbank.com/drugs/DB00099

NodeNorm has the Drugbank identifier as a secondary identifier for [MESH:D000069585](https://id.nlm.nih.gov/mesh/D000069585.html): https://nodenormalization-sri.renci.org/1.3/get_normalized_nodes?curie=MESH%3AD000069585&conflate=true

**Comment by sandrine-m** [comment]
@gaurav : one way to fix this is to choose the order of IDs in NodeNorm
@cbizon : hard to be done by release
@gaurav : could we use the attribute server?

fixes:
1. filter at UI level
2. use attribute server
3. ingest wiki data

**Comment by sandrine-m** [comment]
@newgene when do you think fix 1 is feasible: pre-release (August) or post release?
Thank you!

**Comment by sstemann** [comment]
@newgene is this something the annotator will provide?  Filgrastim is still linking out to MeSH in Prod UI
https://id.nlm.nih.gov/mesh/D000069585.html

**Comment by newgene** [comment]
Did we already have a nice description of `Filgrastim` from NCIT:

https://biothings.ncats.io/annotator/CHEMBL.COMPOUND:CHEMBL1201567?fields=unii

We currently don't have the description from Drugbank and MESH. Mesh description is on our radar to add (after Oct). Drugbank can also be added once the license issue for Translator use is cleared.

**Comment by gprice1129** [comment]
Sorry for being late to the party on this. But this link is generated from the [prefix-map on biolink github repo](https://github.com/biolink/biolink-model/blob/7893e8763dcc508d5ba39104c2dea98b3d547ce3/prefix-map/biolink-model-prefix-map.json)

We agree that these link outs are hit or miss depending on the CURIE provided. The UI team does potentially have enough information (sometimes) to make better choices if we get the list of normalized CURIEs.

The reason we haven't addressed this issue on the UI is because we're not sure where the "priority CURIE resolving" should happen. Is this something that should be happening at the Node normalizer level? If so we don't want to put a lot of effort into making our own CURIE priority list only to have it be thrown away later.

@gaurav @sierra-moxon do you have opinions on this?

**Comment by gaurav** [comment]
> The reason we haven't addressed this issue on the UI is because we're not sure where the "priority CURIE resolving" should happen. Is this something that should be happening at the Node normalizer level? If so we don't want to put a lot of effort into making our own CURIE priority list only to have it be thrown away later.

That is correct: Babel should strictly use the CURIE priority list from the relevant Biolink class, except for biolink:ChemicalEntity (which Filgrastim is), where Babel should use the prefix order from biolink:SmallMolecule (see https://github.com/TranslatorSRI/Babel/issues/68 for some explanation). In this case, something is going wrong: we're using the UNII prefix instead of the higher-ranked CHEMBL.COMPOUND prefix, which -- as @newgene points out -- we do have a good description for. I'm tracking this bug at https://github.com/TranslatorSRI/Babel/issues/215

**Comment by gaurav** [comment]
UNII is now the [most preferred prefix for ChemicalEntity](https://biolink.github.io/biolink-model/ChemicalEntity/#valid-id-prefixes), so in the future filgrastim will continue to be referred to as `UNII:PVI5M0M1GW` -- as it was previously, but that's no longer something we need to fix :). The only preferred label I'm seeing for filgrastim is "filgrastim" with various capitalization. Is there anything else that needs to be fixed from a NodeNorm perspective?

(Sadly, NodeNorm doesn't itself have any descriptions for any of these identifiers, even with drug-chemical conflation turned on.)

**Comment by gaurav** [comment]
@sierra-moxon Is this ticket good to close or did I miss anything in my previous comment?
