### ISSUE TITLE
Camp vs. cAMP vs. CAMP

### ISSUE THREAD

**Issue by gglusman** [NCATSTranslator/Feedback#360]
https://ui.test.transltr.io/results?l=Shigellosis&t=0&q=94e1349e-f466-4e0e-a8c3-5a59fe86f519

Asking Translator what drugs may treat shigellosis, one relevant answer is forskolin (FSK).
Two paths are offered: a direct FSK-treats-Shigellosis with 1479 papers 'supporting' (I haven't evaluated them!), and a second path that states:
Forskolin --regulates-> [gene] Camp --associated_with-> Shigellosis

'Camp' has a DNA double-helix symbol indicating it's a gene, and it links out to http://identifiers.org/ncbigene/820. That is the page for CAMP, aka cathelicidin antimicrobial peptide... which initially sounds great as this gene is downregulated in shigellosis by bacterial endotoxins, and some treatments involve upregulating it with butyrate(*). So this satisfies the CAMP --associated_with-> Shigellosis bit.

The problem is that FSK doesn't regulate the CAMP gene. It regulates cAMP, i.e., cyclic AMP.

I'm not sure at which point the disconnect arises. The "Forskolin Regulates Camp" bit comes from semmeddb. The linkout to semmeddb doesn't really help identify the provenance of this edge.

(*) Incidentally, there's another answer positing that 'Sodium butyrate --treats-> Shigellosis', coming from ChEMBL. Again, the linkout to ChEMBL doesn't help find further provenance/support. (And right now ChEMBL gives me a 500 error when accessing the card for sodium butyrate, so I can't dig further into this.)

**Comment by sierra-moxon** [comment]
@andrewsu - is it possible that either our PMID filter or the d/r constraint filter will weed this misparse (CAMP vs. cyclic AMP) out of the results?

**Comment by andrewsu** [comment]
The forskolin answer looks like it's coming from the [unsecret agent results](https://arax.ci.transltr.io/?r=2d241a3c-25f1-498a-9eab-ff618f65b68c) (result number 2). It's tough for me to evaluate the effects of the PMID_count filter or the d/r constraint filter because I can't find an edge between forskolin (`UMLS:C0917964`) and the CAMP gene (`UMLS:C1413106`) in the [Service Provider SemMedDB API](https://biothings.ncats.io/semmeddb) (presumably unsecret is getting semmeddb results from the RTX2 Semmeddb KGX dump?), and it doesn't look like the UI is showing the specific publications that semmeddb is citing in support of this edge (which is odd). So unfortunately I can't comment much more on this issue...

**Comment by andrewsu** [comment]
since I _think_ this is specific to unsecret agent's use of semmeddb, I'm tagging @webyrd and unassigning myself...

**Comment by gglusman** [comment]
Upon [retesting](https://ui.ci.transltr.io/results?l=Shigellosis&i=MONDO:0019345&t=0&q=5f975098-78fd-4a58-8eee-26b007ec36aa), this issue seems to be resolved.
