### ISSUE TITLE
Cap on number of results and intermediary node

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#388]
## Steps to reproduce:
What drugs may treat Type 2 diabetes miletus
test environment

**Comment by sandrine-m** [comment]
All shown pages show only 1 edge path with treat edge. For a scientist trying to investigate the mechanism of a drug or group of drugs, this is not useful at all.
Current cap biases results toward treatments instead of grouping by intermediary nodes which reduces the capability to explain biological mechanisms involved.

**Comment by sandrine-m** [comment]
From 07/06/2023 DM call (focused on testing): grouping by intermediary node is a milestone post September

**Comment by sharatisrani** [comment]
Agreed with this.  Connected to https://github.com/NCATSTranslator/Feedback/issues/385 ??

**Comment by sandrine-m** [comment]
Yes @sharatisrani connected to #385 . This issue adds the need to consider grouping before the UI: the cap on totalnumber of results matters.

**Comment by sierra-moxon** [comment]
@sharatisrani  - of this ticket is helpful for the grouping work, please reopen, else closing as grouping is on your radar and your highest priority for the next release.
