### ISSUE TITLE
Parsing error on inherited obesity subclass_of fatal familial insomnia

### ISSUE THREAD

**Issue by sierra-moxon** [NCATSTranslator/Feedback#398]
on TEST - 0382963c-b5e8-43c7-9fc3-e1132e3e456a - Fatal familial insomnia

from Andrew S. via testing session at DM call today:

"inherited obesity - subclass of - fatal familial insomnia" in the "bromocriptine mesylate" answer is coming from ARAX via RTX-KG2. I think this might be an error in parsing? Should be flagged for the ARAX team IMO..." https://arax.ci.transltr.io/?r=77fb975f-20bb-43e2-a12a-f7c5c95c9684

**Comment by saramsey** [comment]
OK I will take a look. Am traveling back to Oregon so it might be a day before I can have a look.

**Comment by cbizon** [comment]
Just to note that this is an example, but it's not limited to this single case.  There are lots of similar edges in those answers, so it looks like FFI has lots of subclasses (according to MONDO, I don't think it has any).  In most (all?) cases there are both subclass-of and manifestation-of edges.

**Comment by saramsey** [comment]
OK, I went to the result https://arax.ci.transltr.io/?r=147026 in the ARAX UI and clicked on the second result in the list, namely, BROMOCRYPTINE MESYLATE, and then clicked on the link for "Analysis Support Graphs" in the ARAX UI. I see a `biolink:subclass_of` edge from "inherited obesity" to "fatal familial insomnia", from `infores:omim`. Looks like the original source relation is `OMIM:has_manifestation`. I believe this has been fixed in the code (specific commit is [here](https://github.com/RTXteam/RTX-KG2/commit/e7bb6ce5323376d98efefbe55efbc1ad8313343c#diff-8d7db61865028ce2ff761df31c6a1d2cb19f2e353d358b5bddba14919d2081aeL4030)) and it should be rolled out in KG2.8.3.

**Comment by saramsey** [comment]
The tentative date for roll-out of KG2.8.3 is Wednesday July 26.

**Comment by saramsey** [comment]
KG2.8.3 has been rolled out to `arax.ncats.io`. Roll out to ITRB instances of ARAX planned soon.

**Comment by saramsey** [comment]
KG2.8.3 has been rolled out to `arax.ci.transltr.io`.

**Comment by sandrine-muller-research** [comment]
Cannot replicate on [retest](https://ui.test.transltr.io/main/results?l=Fatal%20Familial%20Insomnia&i=MONDO:0010808&t=0&q=c3d14a23-a772-43dc-8218-2ea90a2cc7cc)
@saramsey could you please confirm the fix has been pushed to test as of today thank you.

**Comment by saramsey** [comment]
Sandrine, as far as I know, the fix for RTX-KG2 was pushed to test months ago. The  bromocriptine result in the [retest query response](https://ui.test.transltr.io/main/results?l=Fatal%20Familial%20Insomnia&i=MONDO:0010808&t=0&q=c3d14a23-a772-43dc-8218-2ea90a2cc7cc) that you linked to, seems to come from BTE not from ARAX,

![Screenshot 2023-10-24 at 10 31 40 AM](https://github.com/NCATSTranslator/Feedback/assets/5562107/c5d41904-10b4-4ef6-8d40-7affc8f375d2)

 and the underlying result graph in BTE does not seem to involve "inherited obesity", as shown here:

![Screenshot 2023-10-24 at 10 33 08 AM](https://github.com/NCATSTranslator/Feedback/assets/5562107/969aaa36-48d4-4114-8df3-23524853d928)

If there is evidence available that suggests that the bug is still present in ITRB TEST, please let me know. From what I can see, the originally-reference bug no longer exists on ITRB TEST (which makes sense to me because AFAIK the fix rolled out to PROD just prior to the August code freeze, i.e., at the end of the summer dev cycle).

**Comment by saramsey** [comment]
@sierra-moxon OK to close?
