### ISSUE TITLE
No results for What drugs may treat Atherosclerotic Heart Disease With Ischemic Chest Pain

### ISSUE THREAD

**Issue by khanspers** [NCATSTranslator/Feedback#410]
Tested on https://ui.test.transltr.io/

Query: What drugs may treat Atherosclerotic Heart Disease With Ischemic Chest Pain? (matched from searching for Ischemic Chest Pain)
https://ui.test.transltr.io/results?l=Atherosclerotic%20Heart%20Disease%20With%20Ischemic%20Chest%20Pain&t=0&q=6ffeaff6-de8b-4cc2-bf27-545cdad6ef13

Results: 0

- Ischemic chest pain is a synonym for angina, so it is weird that the only thing that comes up in the interface when typing in "Ischemic chest pain" is "Atherosclerotic Heart Disease With Ischemic Chest Pain". 
- Also, it seems like a bug that there are no results for "Atherosclerotic Heart Disease With Ischemic Chest Pain", as there are many medications for this very common condition. 

Switching the query to search for "Angina pectoris" one of the synonyms is Stable Angina, which does give many results.

**Comment by gaurav** [comment]
I'm not sure why this is the case, but this is definitely a Name Resolver issue. This appears to be fixed in the new version of the Name Resolver (we plan to deploy this next week!) no longer gives me "Atherosclerotic Heart Disease With Ischemic Chest Pain" ([UMLS:C2882167](https://uts.nlm.nih.gov/uts/umls/concept/C2882167), which is a pretty narrowly defined identifier that we don't connect to other identifiers), but rather [MONDO:0006805 "intermediate coronary syndrome"](http://purl.obolibrary.org/obo/MONDO_0006805), which MONDO defines as "Angina pectoris (or equivalent type of ischemic discomfort) which has recently changed in frequency, duration, intensity, or occurs at rest.". This term does [have results](https://ui.test.transltr.io/results?l=Intermediate+Coronary+Syndrome&t=0&q=75ff6aff-42a5-4d99-9ab0-8d509735e10b)! With the improved filtering in the next version to DiseaseOrPhenotypicFeature, we will also return [HP:0001681 "Angina pectoris"](http://purl.obolibrary.org/obo/HP_0001681), which HP defines as "Paroxysmal chest pain that occurs with exertion or stress and is related to myocardial ischemia.".

I'll leave this ticket open until this is implemented and testable in UI Test.

One question on terminology: if we return either "Angina pectoris (matched on Ischemic chest pain)" or "intermediate coronary syndrome (matched on chest pain ischemic)", is that clear enough with the search query of "Ischemic chest pain" to understand why these results have been returned?

**Comment by khanspers** [comment]
Thanks! In terms of your question, I think its clear enough.

**Comment by sierra-moxon** [comment]
retested on CI this morning:
[intermediateCoronoary.zip](https://github.com/NCATSTranslator/Feedback/files/12293331/intermediateCoronoary.zip)
[anginaPectoris.zip](https://github.com/NCATSTranslator/Feedback/files/12293332/anginaPectoris.zip)

I think this is fixed for September, per Gaurav's notes.  Past September, it would be great to include autocomplete matches on synonyms in MONDO and HP as "angina pectoris" returns no matches for "intermediate coronary syndrome."

@khanspers - ok to close?  If not, please reopen of course. :)
