### ISSUE TITLE
acronym conflation error... in EFO

### ISSUE THREAD

**Issue by gglusman** [NCATSTranslator/Feedback#428]
https://ui.test.transltr.io/results?l=Ehlers-danlos%20Syndrome,%20Dermatosparaxis%20Type&i=&t=0&q=4a24ced8-2097-4322-abdd-299e1699afcb
disease: Ehlers-danlos Syndrome, Dermatosparaxis Type
3rd result is alendronic acid (score 99.8)
One path: Alendronic Acid Treats Marchiafava-bignami Disease Phenotype Of Ehlers-danlos Syndrome, Dermatosparaxis Type

Trying to understand the evidence for the 'treats' part, sources are ChEMBL, semmeddb and Text Mining Targeted Association API.
43 publications are listed, with lots of content about bone stuff... not seeing anything relevant to neurodegeneration/demyelination (as expected for [Marchiafava-bignami Disease](https://rarediseases.info.nih.gov/diseases/6971/marchiafava-bignami-disease)).

Noting that [EFO claims](https://www.ebi.ac.uk/ols/ontologies/efo/terms?short_form=EFO_1001809) that synonyms of 'Marchiafava-bignami Disease' include... 'metabolic bone disease' and 'metabolic bone disorder' (all MBD!) so perhaps that's the source of the text mining issue.

Loaded the PK onto ARAX interface, viewed BTE results, alendronic acid is #2 there. Viewed the result graph; one of the three biolink:treats edges from alendronic acid to MBD offers text mining provenance, which indeed leads to 'metabolic bone disease'.

**Comment by andrewsu** [comment]
While semmeddb NER issues usually underlie examples like this, in this case it appears that the root cause lies in Node Norm incorrectly combining Marchiafava-Bignami Disease (`MONDO:0016370`) and Metabolic Bone Disorder (`UMLS:C0005944`): https://nodenorm.transltr.io/1.3/get_normalized_nodes?curie=UMLS:C0238265. Not sure if it relates to the EFO synonyms that @gglusman notes above...

@cbizon, perhaps something for your team to look at?

**Comment by cbizon** [comment]
Yes, thanks @andrewsu
