### ISSUE TITLE
ARAGORN results - can't seem to load in ARAX UI

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#435]
https://ui.test.transltr.io/results?l=Meniere%20Disease&i=MONDO:0007972&t=0&q=700503d9-14e3-4b37-a2fb-71a4a110dc8a

According to the UI there are 424 ARAGORN results, i wanted to look at them in ARAX.  ARAX says there are 500, but I just get a gray screen when i try to look at the results list

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/432635bf-bd20-4437-a0d3-74e0f950e6cc)

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/b8921681-279e-4691-999d-961db3c6bb1c)

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/66e79b45-e3c3-4734-8270-8663577368eb)

Other examples of this behavior include:
- https://ui.test.transltr.io/results?l=Alzheimer%20Disease&i=MONDO:0004975&t=0&q=ea463b48-d662-4f5c-bf6b-638deb2b89bb
- https://arax.ci.transltr.io/?r=ea463b48-d662-4f5c-bf6b-638deb2b89bb

**Comment by edeutsch** [comment]
Whenever the ARAX GUI does this, it is almost always due to invalid TRAPI

![image](https://github.com/NCATSTranslator/Feedback/assets/12707718/be9f72e7-9e56-488e-b893-ee6238dc3650)


This result is also very large, over 20 MB, which will cause most browsers a problem. The whole 20 MB message must be loaded into the Javascript of the browser and this is sometime problematic. Firefox seems to withstand this maltreatment better than Chrome.

**Comment by sstemann** [comment]
@uhbrar can you please take a look?

**Comment by uhbrar** [comment]
Like Eric said, the results aren't showing up because the message is too large to load. We're working on a possible fix to make the message smaller.

**Comment by edeutsch** [comment]
okay, to close this issue, @sstemann ? 
It seemed to be just an issue of your browser's inability to digest an enormous message.

**Comment by cbizon** [comment]
This more recent run looks like ARAGORN just didn't return any results?

**Comment by sstemann** [comment]
yep, OBE
