### ISSUE TITLE
Show match text, or show designation of matching on a synonyms in addition to the "real" disease name in the UI autocomplete

### ISSUE THREAD

**Issue by sierra-moxon** [NCATSTranslator/Feedback#44]
see issue #10 for examples of this.  
basically when a user types in something like Addison's Disease (which is no longer the primary label for the MONDO disease), the autocomplete returns the new, formal name of the disease, but there is no indication to the user that the returned name is the official name matched because Addison's Disease (the user's input) is a synonym in MONDO.  

There are some examples of other biological resources that have a more complex autocomplete to queue the user into the match and how it was made in the #10

**Comment by sierra-moxon** [comment]
for @Genomewide to distribute to UI team :) thanks Andy!

**Comment by sierra-moxon** [comment]
Hi @dnsmith124 :)  - I think I saw an update on another issue that you were reworking the autocomplete?  Can I group this into your changes or would you like me to keep it here for a future release or future work?

**Comment by dnsmith124** [comment]
@sierra-moxon  This sounds like a great change! I'll add it to my list, but it may require a more extensive rework than some of the other changes, it all depends on what we get back from the Name Resolver and Node Normalizer. I'll have to review the data to find out if this is something we can currently support.

**Comment by dnsmith124** [comment]
As of now I'm not certain that identifying when a search term is synonymous with a returned autocomplete term is something the UI has the ability to support, or that the tools we're using to retrieve those terms are capable of that either, but I could be wrong.

**Comment by sierra-moxon** [comment]
In another instance similar to these but slightly different (noticed by Alex and @cbizon):  "Castleman Disease" is entered in the UI and the autocomplete changes the question bar to "What drugs may treat Angiolymphoid Hyperplasia".  But it looks like all the answers say "Castleman Disease".  "Castleman Disease" is the proper MONDO term name, and I don't see a MONDO synonym of "Angiolymphoid Hyperplasia" -- but there are a lot of xrefs to UMLS, etc on that MONDO term, so "Angiolymphoid Hyperplasia" could be a name on one of those sources.  I will try to find it.

**Comment by cbizon** [comment]
I think that this is probably the same issue, but when I run "Castleman Disease" it changes the disease name to Angiolymphoid Hyperplasia.  As far as I know that's not a synonym?

**Comment by sierra-moxon** [comment]
@karafecho also noted this issue in #53 
"the answers that are returned for primary ciliary dyskinesia are for ciliary motility disorders, even though I selected "primary ciliary dyskinesia" from the drop-down menu as the disease of interest."

**Comment by karafecho** [comment]
I've encountered the issue that I conflated under #53 a few times. For the PCD example, "ciliary motility disorders", "Kartagener's syndrome", etc. were returned in answers, but "PCD" was not, but yet the drop-down menu included numerous choices for variants of PCD. I'm thinking this may be a Name Resolver issue?

**Comment by Genomewide** [comment]
We discussed possible actions in the short and long term.  This issue comes up when the canonical name in name resolver is different than the name of the mondo term.  

Short term, if there is no mismatch between the mondo name and canonical we will not do anything.  If the mismatch occurs that would cause the search term to we will show a message that indicates that the mondo name is different rather than just changing it.  

Long term, this should change when the name resolver/normalizer/annotator that Chris is saying they are developing is ready.  that should eliminate the issue because the node name for the mood term will have the canonical value (assuming we understand what the annotation tool will do). I need to confirm this with Chris.

**Comment by sierra-moxon** [comment]
from TAQA:
- sometimes the names come back with species annotation ("FGF8 - human"), but this is a fragile assumption to build on.
- HGNC in the curie, then we can say Human, but its UniProtKB/NCBIGene etc.
- centralize the name/symbol/species of genes in a KG (name resolver could evolve towards this?) 

Does TMKP assume its human if there is a gene symbol?  does this lead to false positives?  (Bill: this is essentially true, use the PO to extract the concepts at the _species agnostic_ level - not human specifically.  The fix to this, is to "assume human", definitely errors introduced here.)

Does SEMMEDDB do this as well?  - they use NCBIGene identifiers (species-specific) 

Do orthologs get conflated in creative mode?  No, and geneticists would not want to conflate them via simple text match.
Tyler: If we don't have the species from the KP, why not?  - this should be part of the attributes collection in any node. 
Andy: they might be coming back from the nodes, but maybe not from the NameResolver? 
Tyler: what does NameResolver return?
Gaurav: shows a list of names, that are identical to their sources and no "curation" step in the NameResolver.  UniProt metadata does have the organism in it.  SRI is coming up with the "node properties" service.   Maybe while we wait for that, we do something dumb, and just extract the "mouse" from the name.  
Andy: That was what I was suggesting as well - as a short-term fix, but not a long-term fix. 
Tyler: NameResolver is based on a KG, right?  A flattening of the KG at least.
Gaurav: yep
Tyler: Is this something NameResolver can do? 
Andy: "homolog to mouseX" is the issue with parsing the name as text
Tyler: yep, I think using the metadata directly is safer.
Matt: does mygene.info have this info in an API we can hit?  Is it a name property on a node?
Sarah S: one thing to note, we also get duplicate disease names as well as chemical entity names for those queries in the UI
Andy: will take back to my group to investigate.

**Comment by gaurav** [comment]
We're tracking this as NameRes at https://github.com/TranslatorSRI/NameResolution/issues/38

**Comment by gaurav** [comment]
To organize this ticket a bit, based on our discussion from yesterday, it sounds like there are two distinct issues here:
- [ ] Sometimes searching for something (e.g. "Addison's disease") will result in an unintuitive, very different result ("adrenal insufficiency").
  - This is because searching for Addison's disease in NameRes results in a CURIE, but looking that CURIE up in NodeNorm results in a very different canonical label.
  - Plan: The UI will return both parts of this search to the user (maybe something like "Addison's disease is a synonym of adrenal insufficiency") so they understand how they got there.
- [ ] Sometimes the labels returned by both NameRes and NodeNorm are insufficient to fully understand which concept is being referenced.
  - e.g. searching from "FGF8" matches synonyms of "FGF8" in NameRes, all of which have a canonical name of "FGF8" in NodeNorm, but no information on which species this protein is from.
  - Eventually, the property server will help with this, by being able to provide additional metadata on each identifier ([identifier] found_in: [mouse], say).
  - As a short-term fix, UI will attempt to get this information from mygene.info or another Biothings service.
  - If this doesn't work, NodeNorm might need to reprioritize our canonical labels so that we choose one that includes a taxon ("Mmus", "Mouse") or even just look for brackets so we know that the label will be informative about some sort of subset (e.g. "FGF8 - Human", "FGF8 (Hsap)", etc.). This is a very fragile way of doing this, so we don't want to try this until we've tried everything else first.

Is that right? Am I missing anything?

**Comment by cbizon** [comment]
Can we break this into 2 tickets so that we can properly assign owners?

**Comment by sierra-moxon** [comment]
#127 - UI will attempt to get info from mygene or other Biothings service task
#128 - For investigating prioritization of taxon-labeled results from NodeNorm.

**Comment by sierra-moxon** [comment]
I am going to close this issue in favor of the two split-out issues above that have actionable components.  Please of course reopen if you disagree. :)
