### ISSUE TITLE
results are stating another output disease than the one I look for

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#445]
## Steps to reproduce:
1) MVP1 on FSGS
2) filter for Basiliximab
submitted by @sandrine-m

**Comment by sandrine-m** [comment]
<img width="1025" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/66342541/967c4859-c406-4f6e-ab13-09c7b78762e5">
The result states 3 Paths that may treat Crouzon Syndrome-acanthosis Nigricans Syndrome instead of FSGS (originally queried)
UI states that the result comes from Unsecret and improving agents confirmed on ARAX for unsecret but not for improving. The output statement does not answer the question (but queried disease in intermediary node). 
Unsecret:
<img width="1144" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/66342541/57b5c2b6-f20b-43d8-bb64-095e4076ff33">
Improving:
<img width="1144" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/66342541/9b20b099-7c5a-4ab8-9172-2499d61ce6d9">

Because of the discrepency of the 2 output statements between the 2 ARAs directing this to UI team as well for a second opinion.

**Comment by sandrine-m** [comment]
Same with this result:
<img width="1025" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/66342541/1d68f748-a8b3-4ea1-b7f5-c32418b804f4">

**Comment by gglusman** [comment]
Related to https://github.com/NCATSTranslator/Feedback/issues/422 ?

**Comment by sandrine-m** [comment]
Yes! Thank you for pointing me to this! 
I am going to triage it the same way as the other issue.

**Comment by cbizon** [comment]
It may be systematic but the other one was apparently an ARAGORN issue while this seems to be unsecret....

**Comment by suihuang-ISB** [comment]
A possible reason for why a "wrong disease than queried" comes up in imPROVING, I suspect, possibly is a consequence of one of the algorithm of inference that imPROVING uses: The two diseases (one in the query, the other not) are in the graph vicinity of each other, connected by a 2-hop path via the drug that treats both. Allowing for  the possibility of  multiple drugs that treat the same disease  may have led to allowing the inverse multi-fan graph motif: same drug connected to multiple diseases.... (alternative indications due to similar mechanism)... 
We should able to fix that.

(@brettasmi - can we discuss this at our next  meeting?)

**Comment by brettasmi** [comment]
Sorry, I'm not sure that I understand, is imProving returning the wrong disease here? It looks like our results point to FSGS, which was the queried disease, correct?

**Comment by suihuang-ISB** [comment]
@brettasmi: Yes, FSGS was the queried disease, but not the Crouzon Syndrome which also show up in the answer graph.  
While Crouzon Syndrome is a syndrome that may also display (rarely) glomerulonephritis,  thus make it related to FSGS the query should not return **_multiple_** diseases - instead of multiple drugs.

**Comment by sierra-moxon** [comment]
@cbizon - will this be fixed post-September?

**Comment by sandrine-m** [comment]
FYI, RETESTED today on [CI (UI)](https://ui.ci.transltr.io/results?l=Focal%20Segmental%20Glomerulosclerosis&i=MONDO:0100313&t=0&q=d85461f7-fbfd-480a-8124-d6f5b77d63b1) : does not return, sadly, any outputs (confirmed on ARAX UI).
RETESTED on [ARAX ](https://arax.ci.transltr.io/?r=98e5ad3f-6188-4198-96ff-e8aa9c658022) to double check: 
```{`
   "edges": {
      "e00": {
         "subject":   "n01",
         "object":    "n00",
         "predicates": ["biolink:treats"]
      }
   },
   "nodes": {
      "n00": {
         "ids":        ["MONDO:0005363"]
      },
      "n01": {
         "categories":  ["biolink:ChemicalEntity"]
      }
   }
}```
There are lot of results here so it seems there is an issue with NameRes (assigning David and Gaurav for checking this out):
<img width="1254" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/66342541/78170ead-45a9-48d7-ad25-76e17ceea303">

Unsecret does not return any results anymore and improving only returns FSGS. I have checked all KG for each ARA for this query and found out that:
- ARAGORN returns Crouzon syndrome-acanthosis nigricans syndrome with _pentetic acid_ :
<img width="1142" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/66342541/9971348e-acba-4aac-bd96-5a1eb47b5880">
But unlike issue #422, MolePro **does not return** _pentetic acid_ and is the only KP returning results to Translator.
- ROBOKOP is similarly affected (see example with _Medroxyprogesterone acetate_ ):
<img width="1144" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/66342541/3ba9d89e-ffe1-4374-bc3c-3a83dfc4d118">

**Comment by sierra-moxon** [comment]
From TAQA:
we see that there is a subclass_of relationship between these two diseases (in MONDO).  
we don't see subclass_of relation (because it swamps the graph). 
we could use some indication in the UI for the subclass of relation
we have a plan to show this in a special way in TRAPI, but punted until Fall.

**Comment by sandrine-m** [comment]
Maybe @suihuang-ISB can comment on that, in the same reasoning idea, it might be important to take into consideration how often the diseases co-occur and the direction of the reasoning here.

**Comment by sandrine-m** [comment]
I looked at the MONDO ontology and found this (that could help to illustrate the point of directionality in the answer:
<img width="722" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/66342541/e431bd69-20a7-4c18-866f-62a1b3d21d11">
Several mendelian diseases _can cause_ FSGS. FWIW, I am not ultra familiar with Crouzon's syndrome (a MONDO child of FSGS under mendelian diseases) and it is not clear whether it is a subpart or associated with predicate. However, I do work on HIV associated nephropathy (another MONDO child of FSGS under mendelian diseases) and the penetrance of the variant is far from 100%. I would agree of such a reasoning for a predicate `biolink:subclass_of` if penetrance was 100% but I am not so sure otherwise. I am not working in clinics so maybe @suihuang-ISB, Jen H., @gglusman can comment?
To me, it looks like a liberal use of predicae perhaps?

**Comment by cbizon** [comment]
This picture shows that Crouzon syndrome is a subclass of FSGS.  i.e. every instance of Crouzon is also an instance of FSGS, just as every instance of a rectangle is also an instance of a square.

Perhaps I misunderstand, but I don't think penetrance is relevant here.  It gets confusing, but I think MONDO handles issue like that by putting susceptability in a different branch from diseases.

**Comment by cbizon** [comment]
OK, working with @sandrine-m and @sierra-moxon we've come to this conclusion:  Translator is basically working as expected in this case because to the best of our current data, Crouzon is a subclass of FSGS.

That said, this subclass_of is an error in MONDO, which has subsequently been fixed, and which now needs to be propagated into ubergraph and beyond.  Tagging @balhoff and @EvanDietzMorris .

**Comment by balhoff** [comment]
@EvanDietzMorris this fix is now included in the latest Ubergraph release.
