### ISSUE TITLE
When choosing neutropenia, one of the top results is "Cytotoxic agent". Clearly this should be a "causes" instead of "treats" relationship.

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#45]

**Comment by sierra-moxon** [comment]
ARA- ARAX results: https://arax.ncats.io/?r=773b374b-737b-4340-a3dd-b20179fc220e
<img width="1472" alt="Screen Shot 2022-11-30 at 5 11 34 PM" src="https://user-images.githubusercontent.com/4561292/204941827-21af5f6f-1de8-43e6-af51-123a78f2020e.png">

Noting there are 44 paths that suggest that Cytotoxic Agent treats neutropenia according to the UI, and there are 2133 pieces of evidence. 
<img width="1116" alt="Screen Shot 2022-11-30 at 5 09 17 PM" src="https://user-images.githubusercontent.com/4561292/204941574-7ca65811-232a-49c9-9450-4cb51737ef7b.png">

**Comment by dkoslicki** [comment]
@sierra-moxon in the answer you highlight, note the low ranking of this answer. The hope was that this low score associated with this answer would cause it not to show up in the top 10.

Also, since it appears that ARAX is the only one returning Cytotoxic Agent as an answer (something we will need to fix), how are the 2,133 "pieces of evidence" being calculated? Seems overly generous to count _every_ path as evidence. Indeed, just because Cytotoxic Agents are Pharmaceutical Preparations, some of which treat Neutropenia (what one of the "lines of evidence" translates to), doesn't imply that Cytotoxic Agents treat Neutropenia.

**Comment by sierra-moxon** [comment]
From TAQA:
count every paper on every edge that is unique and that is the result.
We know its an issue, we can just keep working on this from a UI POV and architecture.

**Comment by sierra-moxon** [comment]
I took this ticket for a test run on the new ranking implementation on the test UI server, and cytotoxic agent now is ranked very low, it occurs past 97 pages of results. In addition, the number of lines of evidence are also far fewer (~20 vs. 2000)

![Image](https://user-images.githubusercontent.com/4561292/214955443-4bdca515-1b96-4bf2-8bb1-43e74116f2f3.png)

I think we can close for now; @Genomewide please reopen if you think we need to eliminate cytotoxic agent from the results completely?
