### ISSUE TITLE
Give better chemical labels to returned responses

### ISSUE THREAD

**Issue by jh111** [NCATSTranslator/Feedback#462]
Search What drug may treat Multiple Sclerosis.
https://ui.test.transltr.io/results?l=Multiple%20Sclerosis&i=MONDO:0005301&t=0&q=bf9d0342-0966-4cec-8122-8d87187b1ef3

One of the answer that comes up is Monoclonal antibody an100226.

This is the early name/number for natalizumab. It will be much more helpful for users to have this normalized to the current name, natalizumab.

Options:

1. A search in PubChem for Monoclonal antibody an100226. brings up natalizumab, and a list of depositor-supplied synonyms: https://pubchem.ncbi.nlm.nih.gov/substance/481101759 
2. The evidence for treat includes many papers from PubMed that clearly have natalizumab in the title. Perhaps there's a way to get SemMedDB results to provide natalizumab as an answer, or to map SemMedDB DB answers.

**Comment by sierra-moxon** [comment]
@gaurav - is this something for Name Resolver?

**Comment by sandrine-m** [comment]
Tagging the ace team David and Gaurav.

**Comment by gprice1129** [comment]
It isn't clear what the UI team can do about this issue. Is the idea of a "canonical name" available in the attribute server? @newgene

**Comment by sandrine-m** [comment]
I think Jenn means that the returned results were not normalized properly. I used Jenn's PK to load back the results using [ARAX CI UI](https://arax.ci.transltr.io/?r=aae2bdeb-7908-431f-a487-d56fd9c98734) (note this is an "old" query and the ARAS are falling the validation):
<img width="761" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/66342541/a2582978-316d-4251-ae52-db5a007f3445">
I found that BTE was responsible for this result:
<img width="1139" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/66342541/c36be026-3b8b-40cb-8974-3cd887b3d2d4">

I [RETESTED on test today](https://ui.test.transltr.io/main/results?l=Multiple%20Sclerosis&i=MONDO:0005301&t=0&q=a3dbc1f9-8f68-465e-a9fc-eee1fb984073) and the non-normalized name is still popping up:
<img width="1046" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/66342541/87ae81f8-6c00-4a00-9cf1-24a89824161d">
and appears twice (one with the [meshID](https://id.nlm.nih.gov/mesh/C107925.html) and one with the [UMLS ID](http://linkedlifedata.com/resource/umls/id/C0665297) . Apparently both BTE and RTX-KG2 are returning that result.

I looked at [RENCI name resolver for monoclonal antibody AN100226 ](https://name-resolution-sri-dev.apps.renci.org/lookup?string=Monoclonal%20antibody%20an100226&offset=0&limit=10) and found that the 2 identifiers instances gets properly pooled together. 

Natalizumab is part of the synonyms but is not the label. I do not know what is the rule for deciding the drug label, but my guess is that the drug label is decided at the Node Norm stage, so that is a NodeNorm issue?

**Comment by gprice1129** [comment]
@sandrine-m the UI does not do any normalization, we use the normalization the ARS provides. The ARS relies on the node normalizer so most likely it is an issue with that service @gaurav @cbizon

**Comment by sandrine-muller-research** [comment]
From conversation through slack:
@cbizon : The label is probably coming from nodenorm, which is where we are choosing the 'best' label.  We currently have an approach that has not always been well received 
@gaurav aurav Vaidya (SRI)
I've added "Investigate strategies for improved preferred labels for cliques." to our priorities. I know we have some tickets with individual examples we can start working on, but if people have ideas about improving this at scale -- if a particular chemical provider has really good labels, say -- please let us know!

**Comment by gprice1129** [comment]
I think we should move away from tickets with open ended definitions of success. "Give better labels" is way too broad and basically can never be finished. It would be better to create tickets with a finite set of items that should be corrected.

**Comment by jh111** [comment]
@gprice1129 If I understand correctly, I think what you're pointing out is that we can't implement this until we define what output is expected, and whether it's possible to do it.

- What is the relative importance of improving this user experience? Can we decide now, or do need time to get user input?
- How much do users care whether the name is familar to them? Does it need to be on top, or would be ok to be able to click to get a list of synonyms?
- Is there one canonical name for biomedical chemicals that are already used as drug ingredients, or do different users have different expectations?
- What is the technical feasibility improving this user experience? How will we test it?

**Comment by jh111** [comment]
I have put on a better title, to reflect the problem/opportunity with experience for specific users, and the fact that some users might like different names. There are several different technical options for how this could be addressed.

For the INN, I think RxNorm ingredient is the right level of detail.  For example, inFLIXimab (as opposed to inFLIXimab-abda. I don't think we need to use the uppercase (which is designed for prescription safety).

**Comment by cbizon** [comment]
Another example of suboptimal labeling is using the name "Activated Charcoal" for carbon: 

https://nodenorm.test.transltr.io/1.4/get_normalized_nodes?curie=PUBCHEM.COMPOUND%3A5462310&conflate=true&drug_chemical_conflate=false&description=false

The rule that's being applied is to get the name from each source and then rank them by the same source priority as used in biolink to pick which curie is the best one.

**Comment by sandrine-muller** [comment]
When you say source, do you mean original sources or each team within Translator? Would it be useful then to collect the name that each source provides and learn a rule (=set of weights) that best predict the user liking (=the desired result in the test asset sheet?)

**Comment by gaurav** [comment]
To deal with the simpler issue first, [CHEBI:27594 "CHARCOAL, ACTIVATED"](https://nodenorm.test.transltr.io/1.4/get_normalized_nodes?curie=PUBCHEM.COMPOUND%3A5462310&conflate=true&drug_chemical_conflate=false&description=false) still has the wrong label (should be "carbon"). This is because we [prefer CHEMBL.COMPOUND labels over others](https://github.com/TranslatorSRI/Babel/blob/1650282025f9b3aa099dc1598fc2dda9571b24a8/config.json#L73-L84). I think I've seen other examples of CHEMBL labels being suboptimal; I wonder if we should promote CHEBI above it and see if that improves this situation (it should definitely fix this bug). I'm going to look for other reports of this before deciding whether to try this. 

Now for the more complex issue: [UMLS:C0665297](https://uts.nlm.nih.gov/uts/umls/concept/C0665297) is [present twice in NodeNorm Test](https://nodenorm.test.transltr.io/1.5/get_normalized_nodes?curie=MESH%3AC107925&curie=UMLS%3AC0665297&conflate=true&drug_chemical_conflate=true&description=false) -- once in a UMLS-only Protein clique, and once in a UMLS+MESH ChemicalEntity clique. These should really be merged into a single clique, but proteins and chemicals are currently produced by independent modules, so there isn't any way to merge those cliques given how NodeNorm is currently architected.
- I don't think fixing this is reasonable to do within this round of Translator funding, as we'll need to rethink how Babel works.
- However, I would like to see how often this happens, which shouldn't take too much effort. I'm going to schedule that part of this work for Hammerhead, but I'll see if I can do it any sooner than that.

**Comment by Genomewide** [comment]
Is there a way we can gather all of the examples together to look at the flavors we are talking about? 
Charcoal, activated is wrong for different reasons than _A synthetic peptide of 20 amino acids, comprising D-Phe, Pro, Arg, Pro, Gly, Gly, Gly, Gly, Asn, Gly, Asp, Phe, Glu, Glu, Ile, Pro, Glu, Glu, Tyr, and Leu in sequence. A congener of hirudin (a naturally occurring drug found in the saliva of the medicinal leech), it a specific and reversible inhibitor of thrombin, and is used as an anticoagulant._

@gaurav Do you have a dart board or a stress ball where you keep all of our complaints (or other place). I would be interested in seeing how to break these down and then look at the some examples from each group.

**Comment by sandrine-muller-research** [comment]
@Genomewide I started [this sheet](https://docs.google.com/spreadsheets/d/1ktEpubHv-zGovxO_ytkkVCJrHL_Izl_yE2SEiV8xjTQ/edit?usp=sharing) on my side (to become perhaps a set of tests in future for @gaurav ) it does not contain all examples and surely Gaurav has a lot more

**Comment by Genomewide** [comment]
How do I find what to put for Molpro? I added asset # 25

**Comment by sandrine-muller-research** [comment]
[Here](https://translator.broadinstitute.org/molecular_data_provider/assets/lib/swagger-ui/index.html?url=/molecular_data_provider/assets/openapi.json#/compounds/post_compound_by_id) is how you can query MolePro where you put as an input ["CID:75007581"] (MolePro has internally a different set of CURIES. 
However, MolePro does not know about this ID (we are tracking why at the moment) but [does know about collagenase](https://translator.broadinstitute.org/molecular_data_provider/collection/XOdgIPyex5). To query by a name, use the "by_name" endpoint.
I do see it on the PubChem page that it got modified beginning of July (2024-07-20) so that is perhaps a change of ID. We are investigating. I'll keep you posted.

**Comment by gaurav** [comment]
> @Genomewide I started [this sheet](https://docs.google.com/spreadsheets/d/1ktEpubHv-zGovxO_ytkkVCJrHL_Izl_yE2SEiV8xjTQ/edit?usp=sharing) on my side (to become perhaps a set of tests in future for @gaurav ) it does not contain all examples and surely Gaurav has a lot more

Thanks, @sandrine-muller-research! My list is [actually much shorter](https://docs.google.com/spreadsheets/d/1DOD5Dn-as4P4Kz3xKzaLUXrqwwa4-avUasXEdr_xOlk/edit?gid=0#gid=0) :) I'll start moving your entries over in Hammerhead.

**Comment by colleenXu** [comment]
Just putting these here in case people are unaware of other convos:
* https://github.com/NCATSTranslator/Tests/issues/62
* https://github.com/NCATSTranslator/Tests/issues/64
* https://github.com/NCATSTranslator/Tests/issues/69

**Comment by sandrine-muller-research** [comment]
Thank you Colleen!
Putting this query [here](https://ui.test.transltr.io/main/results?l=Lactose%20Intolerance&i=MONDO:0100345&t=0&r=0&q=48940ea5-1c7b-4a53-b058-e833e921e323) as it has a good amount of extremely long names. I will need to see whether we have better chemical name, and update the test asset  sheet. Will come back to this.

**Comment by sstemann** [comment]
The original example is resolved, Natalizumab is displayed, nothing is returned for text search monoclonal or antibody

https://ui.test.transltr.io/results?l=Multiple%20Sclerosis&i=MONDO:0005301&t=0&r=0&q=4f9e38a4-e3ef-46d6-b04a-bad322b5526e

I ran a query which has Activated Charcoal in it, and there's only one result, not all of the other forms.  So these examples look resolved, there are other tickets for other symptoms.  Closing this one for Hammerhead
https://ui.test.transltr.io/results?l=VPS13B%20(Human)&i=NCBIGene:157680&t=1&r=0&q=d18fd174-59c2-4032-94de-2a7a5c83a66e
