### ISSUE TITLE
duplicate results with disjoint curie sets, from the same publications

### ISSUE THREAD

**Issue by gglusman** [NCATSTranslator/Feedback#464]
Upon retesting _what drugs may treat [Familial Pityriasis Rubra Pilaris](https://monarchinitiative.org/disease/MONDO:0008251)_ ([on test](https://ui.test.transltr.io/results?l=Familial%20Pityriasis%20Rubra%20Pilaris&i=MONDO:0008251&t=0&q=753b6d16-7537-4938-bad5-f5a6f3f2ce5c), [on ci](https://ui.ci.transltr.io/results?l=Familial%20Pityriasis%20Rubra%20Pilaris&i=MONDO:0008251&t=0&q=1fe9cae2-1531-44c9-9053-6fdb52b500e3)):

Some results appear to be duplicated in ci, with different curies, scores and support.
* For example, [methotrexate](http://identifiers.org/pubchem.compound/126941) with score 99.4, 6 paths, 7 sources, 146 publications, but [methotrexate](http://identifiers.org/drugbank/DB00563) with score 0, 1 path, 1 source (Text Mining KP), [1 publication](https://pubmed.ncbi.nlm.nih.gov/17386290). The same publication supporting the weak result also supports the direct path for the strong result. 
* More perplexingly [(-)-epigallocatechin gallate](http://identifiers.org/pubchem.compound/65064) with score 82.7, 4 paths (one of which is via [CARD14](http://identifiers.org/ncbigene/79092)), 5 sources, 21 publications, but [(-)-epigallocatechin gallate](http://identifiers.org/drugbank/DB12116) with score 0, 1 path (via [CARD14 by a different name](http://purl.uniprot.org/uniprot/Q9BXL6)), 2 sources, 5 publications. Interestingly the two publications supporting the edge "(-)-epigallocatechin Gallate Causes Increased Activity Or Abundance Of Card14" in the stronger result are exactly the same as the two publications supporting "(-)-epigallocatechin Gallate Affects Increased Activity Or Abundance Of Car14_human Caspase Recruitment Domain-containing Protein 14 (sprot)" in the weaker result, and both come from Text Mining KP. **Which seems to imply that the same association is being derived from the same papers, but using two distinct sets of curies for subject, predicate and object.**
* The current 'test' version has just one result for each of methotrexate and epigallocatechin gallate, with the same curies as the strong results in ci, but the weaker evidence for methotrexate.

**Comment by sierra-moxon** [comment]
from testing session:
- we think the node ids are being merged in NameResolver
- we noticed that the predicates here are a little strange - we need "causes" in the "affects" predicate
- we would like to identify where the ids aren't being normalized - all the ones Gaurav checked (RENCI NameResolver DEV) in the meeting seem to be merging.
  - we need to confirm that ARS merging is "collapsing"/"merging" the nodes here. 

@bill-baumgartner - this is an interesting case where TMKP is providing two completely different edges (diff node IDs, predicates) from the same pub for the same knowledge statement.

**Comment by mbrush** [comment]
re: 
> we need "causes" in the "affects" predicate

The display of a predicate like `affects increased activity or abundance of` predicate in the UI should never happen, and is one of several specific issues exposed in this ticket that TMKP may be able to address.

![image](https://github.com/NCATSTranslator/Feedback/assets/5184212/9f1df531-4db5-4b69-8d5b-d85bd6260ddf)

When qualifiers describing an increase or decrease in the activity or abundance of something are present in an edge in the data, the primary predicate for this edge should be `affects` and the qualified predicate should always be `causes`. 

````
subject: chemical Z
predicate: affects
qualified_predicate: causes
object: Gene Y
object_aspect_qualifier: activity or abundance
object_direction_qualifier: increased
````

The UI should use the qualified predicate `causes` when stitching together a predicate from the qualified representation into a simple triple of the form "X - *causes* increased activity or abundance of - Y".  (The UI should never display something like "X - *affects* increased activity or abundance of - Y")

I think the upshot here is that:
- if TMKP is including the `causes` qualified predicate in their data, then this is a UI issue (@Genomewide) - they are using the primary `affects` predicate instead of the qualified `causes` predicate when stitching together the predicate they show in the UI.  
- if TMKP is NOT including `causes` as a qualified predicate in their data, this is an issue for them to address (@bill-baumgartner).

**Comment by kaiwenho** [comment]
The (qualified) predicate issue is from Unsecret. It has been fixed, but the duplication still exists.
<img width="1128" alt="Screenshot 2023-08-10 at 3 04 51 PM" src="https://github.com/NCATSTranslator/Feedback/assets/67288473/82312a9c-302d-461b-a6cb-48862387f7b3">
The screenshot is from [here](https://ui.ci.transltr.io/results?l=Familial%20Pityriasis%20Rubra%20Pilaris&i=MONDO:0008251&t=0&q=00ab62c3-0378-4490-894f-e8efef9be149).

**Comment by bill-baumgartner** [comment]
Thanks @kaiwenho! @edgargaticaCU see above regarding the qualified predicate issue being fixed.

With regard to the not-conflated drugs pointed out by @gglusman , I'm wondering if this is a NodeNorm issue. 

In `test` the drugs above appear to be properly cross-referenced in NodeNorm in order to be conflated.
```
curl -X 'POST' \
  'https://nodenorm.test.transltr.io/1.3/get_normalized_nodes' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "curies": [
    "PUBCHEM.COMPOUND:126941",
    "DRUGBANK:DB00563",
    "PUBCHEM.COMPOUND:65064",
    "DRUGBANK:DB12116"
  ],
  "conflate": true
}'
```
In `ci`, however, NodeNorm doesn't seem to return any results for these drugs, so the ARS would not be able to conflate them.

```
curl -X 'POST' \
  'https://nodenorm.ci.transltr.io/1.3/get_normalized_nodes' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "curies": [
    "PUBCHEM.COMPOUND:126941",
    "DRUGBANK:DB00563",
    "PUBCHEM.COMPOUND:65064",
    "DRUGBANK:DB12116"
  ],
  "conflate": true
}'
```

Also, in `test`, the BTE result is showing a TRAPI 1.4 validation error so I think it is excluded by the UI. This may explain why only the weaker evidence for methotrexate is shown. The weaker evidence seems to come via Unsecret Agent, while the stronger evidence is from BTE.

**Comment by gglusman** [comment]
@MarkDWilliams pushed a fix in the last hour that seems to have resolved the main issue I reported here.
