### ISSUE TITLE
fibrinogen treats heart disorder - not

### ISSUE THREAD

**Issue by gglusman** [NCATSTranslator/Feedback#477]
What drugs may treat heart disorder, [CI August 12](https://ui.ci.transltr.io/results?l=Heart%20Disorder&i=MONDO:0005267&t=0&q=95f9a185-8f65-4690-85eb-315a5a0aec5a), 4th result with score 100:
![image](https://github.com/NCATSTranslator/Feedback/assets/3977332/04d3d868-8090-46ec-ae91-405238179467)

Zero publications, one source -> just a link to ChEMBL.

Plenty of literature about fibrinogen being a risk factor for heart disease, e.g., https://pubmed.ncbi.nlm.nih.gov/9717059/, https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4692188/, https://cardiab.biomedcentral.com/articles/10.1186/s12933-021-01335-1, https://www.mdpi.com/1422-0067/23/1/193, and much more.

**Comment by gglusman** [comment]
Seems to come from spoke:
![image](https://github.com/NCATSTranslator/Feedback/assets/3977332/b6ba4e9c-88e8-4542-99ff-ca3e83e3dd40)

**Comment by suihuang-ISB** [comment]
The imPROVING result "fibrinogen treats Cardiovascular Disease" comes from the use of fibrinogen in cardiac surgery instead of fresh-frozen plasma (Fibrinogen helps in homeostasis but also promotes clotting and hence is a risk factor for chronic heart disease, as @gglusman indicated).    This "treatment" is part of an effort to replace plasma transfusion in post-cardiac surgery care with one of its key components ... to prevent bleeding ... of which one is fibrinogen to prevent.
see: https://pubmed.ncbi.nlm.nih.gov/26893405/ 

There was a trial on whether fibrinogen uis useful in this setting to replace fresh plasma

The imPROVING agent had pulled tis out from SPOKEs edges that capture clinical  trials. 

This is one more example of the problematic use of the verb/predicate "treats" - which is so ambiguous that it is actually not used in medicine.  More precisely: Fibrinogen is USED as part of the management of patients in cardiac surgery.

**Comment by sandrine-m** [comment]
Could it be linked to #444 ?

**Comment by gglusman** [comment]
@sandrine-m Based on Sui's explanation I see this as a different issue. As Sui put it, _the problematic use of the verb/predicate "treats" - which is so ambiguous._

**Comment by sandrine-m** [comment]
I believe this issue is linked with #123 
@gglusman my understanding was that every biolink predicate was precisely defined and [predicates mapping](https://github.com/biolink/biolink-model/blob/master/predicate_mapping.yaml) should be done based on biolink definition of treats. This error is due to the interpretation of the ChEMBL indication table that should not be a `biolink:treats`. Indeed, the ChEMBL drug indications table is a merging of multiple ressources (a large number from clinical trials.gov). The ChEMBL indication comes from "chemical intervention" from clinical Trials.gov (to see a clear example of this semantic shift, please have a look at the [use case of _Ferumoxytol_](https://docs.google.com/presentation/d/1oAPSfiUUUoWWtwzvb92fDrhxLkquHERx/edit#slide=id.g2235a12e802_0_7) presented to the Predicate meeting. This use case was discussed with some of the clinical KP folks. There has been several discussions going on regarding this issue in the Predicates WG and the current proposal can be find [here](https://github.com/biolink/biolink-model/pull/1328).

**Comment by cbizon** [comment]
Re-review when treats refactor in place.

**Comment by sierra-moxon** [comment]
@gglusman - this is fixed with CTKP, right?  Can I close it?
