### ISSUE TITLE
EGFR - Only Rat in CI

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#481]
For MVP2, downregulators, in CI, if i put in EGFR, I don't have one option for Rat, but in Test there are many options, can we get the human match back?

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/64c3398c-7983-400e-8641-713917a0ffce)

**Comment by sierra-moxon** [comment]
Note: I also tested EGFR1 -- and with that string, I got `egfra (zebrafish)`  back in CI.  I think this might be similar to or the same problem as noted in: https://github.com/NCATSTranslator/Feedback/issues/446

**Comment by sstemann** [comment]
same for AQP1, in Test i get all sorts of species, in CI I only get mouse

**Comment by sstemann** [comment]
when i type in Eg it says no results
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/a58c9e74-3190-44ba-b862-691a266bfbef)

egf, no results
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/345ca0d4-7233-4755-9ae2-22010f0539dc)


egfr, rat
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/f7a05db9-fd99-4b98-a6f4-12a1b36877c8)

**Comment by kingsj208** [comment]
UI Prod now lists Human, mouse, and rat

![image](https://github.com/NCATSTranslator/Feedback/assets/94942393/34331f1c-5237-4270-bdfb-a9035d382f22)

**Comment by gprice1129** [comment]
Can this be closed now? I would also suggest we do not test things in CI.

**Comment by gprice1129** [comment]
@sierra-moxon @sstemann please provide guidance.

**Comment by gaurav** [comment]
I agree with Guthrie that this is ready to be closed.

> Note: I also tested EGFR1 -- and with that string, I got `egfra (zebrafish)` back in CI. I think this might be similar to or the same problem as noted in: #446

Nope, different problem :) -- the [only two results for EGFR1 as a gene](https://name-resolution-sri.renci.org/lookup?string=EGFR1&offset=0&limit=10&biolink_type=Gene) from NameRes Dev are [NCBIGene:778955](https://www.ncbi.nlm.nih.gov/gene/778955) (egfr1 in _Ciona intestinalis_) and [NCBIGene:378478](https://www.ncbi.nlm.nih.gov/gene/378478) (egfra in _Danio rerio_ (zebrafish)). Since we only display genes from a small list of model organisms in the UI, the first entry is filtered out. [Gene EGFR](https://www.ncbi.nlm.nih.gov/gene/1956) doesn't have an "EGFR1" synonym, but it does have a synonym of "ERBB1", which works as expected on UI Prod.

**Comment by sierra-moxon** [comment]
@gaurav - if I type in `egfr` should I also get "_egfra_ (zebrafish)" back as a suggestion?

**Comment by gprice1129** [comment]
Closing this as complete. If you feel strongly this issue has not be resolved please re-open. If you have a different issue open a new ticket.
