### ISSUE TITLE
duplicate 'tretinoin' nodes that need merging

### ISSUE THREAD

**Issue by gglusman** [NCATSTranslator/Feedback#485]
Re-testing PRP again on [CI 8/17](https://ui.ci.transltr.io/results?l=Familial%20Pityriasis%20Rubra%20Pilaris&i=MONDO:0008251&t=0&q=205e899a-1be5-441a-9f2c-d349c0de8f22).

[Tretinoin in pubchem](http://identifiers.org/pubchem.compound/444795) treats neoplasm with just a chembl link as support. Result scores 99.8 thanks to other paths.
[Tretinoin in UMLS](http://identifiers.org/umls/C0040845) treats neoplasm with 29 papers supporting. Result scores just 19.9.

**Comment by gaurav** [comment]
Is the issue that PUBCHEM.COMPOUND:444795 and UMLS:C0040845 weren't being cliqued together? If so, good news: they are now [being normalized to the same identifier on NodeNorm Dev](https://nodenormalization-sri.renci.org/1.4/get_normalized_nodes?curie=PUBCHEM.COMPOUND%3A444795&curie=UMLS%3AC0040845&conflate=true&drug_chemical_conflate=false&description=false) (PUBCHEM.COMPOUND:444795). If there's something else here please let me know, otherwise I can close it once NodeNorm Dev has been pushed to ITRB.

**Comment by gglusman** [comment]
Resolved as of [2024/1/10 testing](https://ui.test.transltr.io/main/results?l=Pityriasis+Rubra+Pilaris&i=MONDO%3A0100017&t=0&r=d6982bc4&q=cfcdc63b-f49f-4ebd-bda1-c2510bd353f1), closing.
