### ISSUE TITLE
Causes problem, offered as treatment (plus conflated meaning of ASM)

### ISSUE THREAD

**Issue by IritR** [NCATSTranslator/Feedback#488]
While evaluating results for ASM ( [ci 8/17](https://ui.ci.transltr.io/results?l=Aggressive%20Systemic%20Mastocytosis&i=MONDO:0020333&t=0&q=a14b1302-5384-4ec1-a691-d94a751879f9) )

Result: Histamine treats Aggressive Systemic Mastocytosis

The supporting papers were all about Airway Smooth Muscle (ASM), and in all of them Histamine was used as a positive control for allergic response.

**Comment by sandrine-m** [comment]
Here are some tips to permit easier triage of the issues by adding more information. Adding more info allows a more efficient triaging and issue solving.

There are several reponses in this query that suffer the same issue: wrong acronym.

I dug in the response and here is what I found as examples:
(1) first returned result on ASM is **a single edge treats graph** from ARAX and Unsecret:
<img width="448" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/66342541/bab71742-f8cb-4c7a-841f-e7617610791b">
[Corresponding associated paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6966559/) is wrongly associated to due to a common acronym while the paper talks about _acid sphingomyelinase (ASM)_.
A deeper look at the response graphs returned from ARAX returns a TMKP edge `tmkp:5d18e822622abd60d3373922f79c019cfce35f79b322eeb99461da7f3459e495`
(2) The wrong response the testers refers to here is result 19 in ARAX from TMKP KG edge `tmkp:7a69934995605da672c56252a6f3efe2c2da050216ddc24e84450c11ed50e751`
`tmkp:1be3815d0a933d89de1829ed04db3d1fe2d9af8e875f9c257f768863ed12a72c`

From my experience, most of those edges come from single edge treats type of responses. There could be a quick stop-gap measure to filter out those results, like what is done with SEMMEDDB (discussed with @andrewsu on another ticket I can't seem to find again).

**Comment by gglusman** [comment]
#479 covers the acronym issue
Beyond the misidentification of the disease, the paper talks about histamine as being causal, but it's interpreted here as a treatment.
