### ISSUE TITLE
Ambiguous acronym

### ISSUE THREAD

**Issue by IritR** [NCATSTranslator/Feedback#504]
While seeking drugs that treat [Aceruloplasminemia](https://ui.ci.transltr.io/main/results?l=Aceruloplasminemia&i=MONDO:0011426&t=0&q=348ce982-848b-424b-9746-de2caaeadeb6)  I was offered Methyldopa, AKA Alpha-methyldopa (AMD). This drug is irrelevant, it was suggested by Text Mining Targeted Association API, likely because one of the symptoms of Aceruloplasminemia is age-related macular degeneration (AMD).

**Comment by sandrine-m** [comment]
This is know issue, I link it with #201  for follow up but I amnot quite sure we are onto the samer kind of issue here.
The treats edge publications reports:
<img width="443" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/66342541/0880b8f5-1c41-474a-b459-ab9534f1b71d">

On the UI CI environment are listed 3 agents reporting this result and potentially affected:
<img width="895" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/66342541/7e0d697b-a582-479a-acea-c332e2597f9c">

**Comment by gglusman** [comment]
I just verified (via ARAX interface) that all three ARAs are deriving this association from TMKP.

**Comment by sandrine-m** [comment]
Thank you @gglusman !

**Comment by bill-baumgartner** [comment]
The TMKP acronym issue reported here has been fixed in a past release. Methyldopa is no longer returned as an answer for @gglusman's original query, and AMD is correctly mapped to age-related macular degeneration in the documents shown in @sandrine-m's screenshot (and methyldopa is no longer present in those documents). Closing this issue (and removing the `Next Phase` tag).
