### ISSUE TITLE
Semicircular Canal Dehiscence Syndrome returns two identical results in the autocomplete, but different results on search

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#51]
## Steps to reproduce:
Semicircular Canal Dehiscence Syndrome returns two identical results in the autocomplete.

**Comment by sierra-moxon** [comment]
If you select the first Semicircular Canal Dehiscence Syndrome in the autocomplete, you get 0 results.  If you select the second in the autocomplete, you get 1 result.

**Comment by cbizon** [comment]
I think that this is partly correct - the NN is not merging these entities and that leads to the two sets of results.  But the question is whether they should be merged - if you expand the equivalent identifiers for each it looks like:
![image](https://user-images.githubusercontent.com/10744350/205380120-d95fe91c-a7a7-44dc-b076-bc20e1fdf7ba.png)

So the MONDO does merge with a UMLS, just not the one above.   Looking into why there are two UMLS terms, it's because there are two SNOMED terms (also included in the cliques).   Looking in SNOMED, it considers the one that merges with MONDO to be a subclass of the other one.

So what to do?
1. The UI needs to somehow differentiate between different things.  The labels here are potentially different, so they can show up using the labels.  Or using the preferred identifiers if that's what's needed.   I thought I heard @Genomewide say that only things with MONDO id's were being used?  If that's the case then maybe we're missing something else.
2. Maybe we should be doing some more merging of entities?  I hesitate to do that willy-nilly though.  Maybe we include some similarity links or some conflation or something?  But this would require more thought.

**Comment by sierra-moxon** [comment]
From TAQA: two results with different names returned from NN, but merged together in the UI?  How to fix, we need to know why the UI would combine? 

UI -> name resolver -> node norm is our process.  Is there something wrong with Name resolver? 
Joint issue between UI and NN

**Comment by gaurav** [comment]
> UI -> name resolver -> node norm is our process. Is there something wrong with Name resolver?

We have been having some odd issues with some of the NameRes instances, but I don't think this is part of that -- from Chris' description above, it looks like we're missing a link between the two UMLS identifiers. I've added this to the Babel issue list at https://github.com/TranslatorSRI/Babel/issues/102

**Comment by sierra-moxon** [comment]
@gaurav - do you think this issue can be closed if this is being fixed via Babel?  Or would it help to keep this open? :)

**Comment by cbizon** [comment]
I think that this issue is fixed. When I look at the CI UI autocomplete, I think that Semicircular Canal Dehiscence and Semicircular Canal Dehiscense Syndrome are showing up as different entities so it's no longer surprising that you end up with different results.   @sierra-moxon is this closable in your opinion?
