### ISSUE TITLE
Workspace - Evidence Download - CSV Content is "ï»¿"

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#516]
Steps to recreate:  

1. In CI > Login > Run MVP1 > Bookmark a couple of results
2. Go to Workspace
3. For the Result, click the "box with arrow down" download button
4. Open the CSV file in Excel
5. View the Content

<img width="952" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/f3942425-aa07-4708-960c-f3f6d82487a0">

6. Compare with the same result in the Result list > download

<img width="947" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/b9702794-140a-4404-9d8a-4b7a1e37be24">

[Workspace EPC Download metformin.csv](https://github.com/NCATSTranslator/Feedback/files/12549504/Workspace.EPC.Download.metformin.csv)

[Result EPC Download metformin (1).csv](https://github.com/NCATSTranslator/Feedback/files/12549509/Result.EPC.Download.metformin.1.csv)

**Comment by dnsmith124** [comment]
I have pushed a fix that resolves this issue, which was a side effect of the compression of results data to be able to support the workspace. 

The fix is live on ci now, here's an example: https://ui.ci.transltr.io/main/results?l=Cartilage%20Cancer&i=MONDO:0000639&t=0&q=bcfc4ae7-b066-4e7d-8fb6-20ca32a77445 

Sort by evidence, bookmark **Dexamethasone**, then click the csv download icon on the results page and the workspace page. 

[Results dexamethasone.csv](https://github.com/NCATSTranslator/Feedback/files/12550592/dexamethasone.csv)
[Workspace dexamethasone (1).csv](https://github.com/NCATSTranslator/Feedback/files/12550593/dexamethasone.1.csv)

**Comment by dnsmith124** [comment]
Note: this fix should make it to our push to test today, and into prod as well provided that deployment is allowed to go through also.

**Comment by dnsmith124** [comment]
Confirmed resolved on prod, closing.
