### ISSUE TITLE
tooltips for icons

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#525]
- preferences
- bookmark
- note
- download
- ChEBI Role - to indicate it'll filter
- share
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/55ea1a87-0c07-4735-8f61-ae14320b9778)

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/0fe6d7a5-3a17-42ad-bc0a-299f376e4964)

**Comment by dnsmith124** [comment]
related to #243

**Comment by dnsmith124** [comment]
From #243: 

> I've done a fair bit more research on this since I spoke about that in TAQA @sierra-moxon, and I think I may have been incorrect with regard to tooltips being inherently inaccessible. Provided that we're very diligent with our aria labeling and keyboard navigation, and ensure that tooltips do not obscure other content I think adding more of them should be fine.

I'm going to implement tooltips for the following: 
- preferences
- bookmark
- note
- download
- share

@sstemann I'm leaving out a tooltip for ChEBI roles because there's nowhere to put the tooltip that doesn't obscure potentially critical content (namely result names and descriptions) which raises accessibility concerns.

**Comment by dnsmith124** [comment]
Added tooltips to the following: 
- preferences
- bookmark
- note
- download
- share
- open query in new tab button in workspace

Will close once it's been deployed.

**Comment by dnsmith124** [comment]
The above bookmarks are showing in CI, @sstemann would you care to review before we close?

**Comment by gprice1129** [comment]
Closing issue. Please reopen if it requires more discussion.
