### ISSUE TITLE
Do ARAs explain the conflation gene/protein in the response

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#542]
Related to #423 

If so, it could be nice to show, if not, then it could be nice if ARA could give the information.  

In general, it could be nice to have a marker if the response is at the gene or protein level and perhaps splitting results coming from different levels....

Could the ARAs answer if this is already in the response?

**Comment by andrewsu** [comment]
Node Norm by default conflates genes and proteins. So for ARAs (or at least BTE), it would be tough to explicitly note the gene-protein relationship in the TRAPI response.  I think it would be reasonable to discuss whether we still want to do that conflation by default in Node Norm.  Personally, I think we do until we see evidence that a substantial proportion of use cases requires teasing those apart, or that a substantial proportion of users (in user interviews) expect to see that relationship explicitly stated.

**Comment by uhbrar** [comment]
I would like to point out that using the `conflate=false flag`, you can prevent NodeNorm from automatically conflating. The flag defaults to true, which is why conflation is the default. ARAGORN also does not explicitly note the conflation, besides having both categories listed on the node. 

I agree with Andrew. I think until we see evidence proving the alternative necessary, we continue operating as we have.

**Comment by dkoslicki** [comment]
RTX-KG2 by default always conflates the two; ARAX just returns whatever the KP gives, so if a KP conflates or not, ARAX will regurgitate that.

**Comment by cbizon** [comment]
Closing until we receive info that it is a problem for users.
