### ISSUE TITLE
Autocomplete - Gene 

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#547]
So I typed in SOX and got this:

<img width="659" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/54ac19d3-c1a4-4150-9422-863afe66e858">

at "1" and got this:
<img width="706" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/68a80541-d0d0-46ba-85c2-e9be712a0586">

not sure if this is by design for genes? same behavior in CI, Test and Prod

**Comment by sstemann** [comment]
i dont think this is a UI bug but I cant remember who does this and an hoping you can redirect it @dnsmith124

**Comment by dnsmith124** [comment]
@gaurav can you speak to this issue? The only reason the UI would return "No matching terms" would be if we received no results from the name resolver.

Possible that the name resolver might have a minimum character count before returning results (which the UI **does not** have)

**Comment by gaurav** [comment]
We don't have a minimum character count either! But this is definitely a NameRes issue: I think we're sending back a ton of non-model-organism `SOX` results, which the UI filters out. I'm tracking this at https://github.com/TranslatorSRI/NameResolution/issues/92, but I'm not sure there's a solution apart from incorporating taxon information into NameRes so that we can do the model organism filtering at our end. That'll take some time to do, but we can aim to try to fix this by end-October if that timeline works for everybody?

**Comment by sstemann** [comment]
@gaurav if it fits in that timeline i think that would be great.  it seems like users would expect a partial match.

**Comment by gaurav** [comment]
Just to give an update on this: I've written some code to add taxon information to NCBIGene entries on Babel (https://github.com/TranslatorSRI/Babel/pull/211). We're currently thinking a bit about how to model this information so that we can use the same mechanism for storing other clique-specific properties, and then I'll add a frontend to this that will allow us to filter genes based on the taxon name, which should make it easier to surface human SOX vs non-human SOX. I'm hoping to have that up on NodeNorm Dev sometime in Feb, and then we can figure out if that fixes this issue or not.

**Comment by sstemann** [comment]
@gaurav just confirming - this is not fixed in the Feb Release

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/cfd3cfe6-7613-4398-9e0a-10155d564cec)

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/25735b03-08d1-49ac-9463-a0254883a7e5)

**Comment by sstemann** [comment]
works in test!  
<img width="656" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/c8cefa4b-f95a-4c93-9cea-775c8c837d0b">

🎉
