### ISSUE TITLE
Reasoner Counts are Off in Test

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#581]
Counts seem off.  If it's related to merging do we need to take another look at hour the counts are done?

In some instances, I saw results tagged in the UI from BTE, but the final load, the results disappeared completely.

Rare Stickler	https://ui.test.transltr.io/main/results?l=Stickler%20Syndrome&i=MONDO:0019354&t=0&q=740fb674-e601-4a25-8cb0-bd87ee6d239b

  | Rare - UI | Rare - ARAX GUI
-- | -- | --
ARAGORN |   | 0
ARAX | 14 | 15
BTE | 499 | 500
Improving |   | N/A
Unsecret | 111 | 132

Diabetes - Four Runs Consecutively
First	https://ui.test.transltr.io/main/results?l=Diabetes%20Mellitus&i=MONDO:0005015&t=0&q=5fe9e9ec-cf55-4ce2-b6de-6a7606ac5f49

  | ARA | First - UI | Final Load New Result | UI Refresh | ARAX GUI
-- | -- | -- | -- | -- 
ARAGORN | 496 | 449 | 449 | 500
ARAX | 495 | 495 | 500
BTE | 379 | 292 | 0?
Improving |  295 | 237 | 238 | 300
Unsecret | 176	| 176 | 176 | 229

Second	https://ui.test.transltr.io/main/results?l=Diabetes%20Mellitus&i=MONDO:0005015&t=0&q=b5d5c529-9d25-4cdd-8c72-3b8577c49b70

  | ARA | First - UI | Final Load New Result | UI Refresh | ARAX GUI
-- | -- | -- | -- | -- 
ARAGORN | 497 | 497 | 497 | 500
ARAX | | 461 | 461 | 500
BTE | 478| 381 | | 0?
Improving | 174 | 174 | 249 | 300
Unsecret | 173	| 167 | 167 | 229

Third	https://ui.test.transltr.io/main/results?l=Diabetes%20Mellitus&i=MONDO:0005015&t=0&q=2bfc4546-3724-49c6-a0dc-3706db25237f

  | ARA | First - UI | Final Load New Result | UI Refresh | ARAX GUI
-- | -- | -- | -- | -- 
ARAGORN | 473 | 435 | 447 | 500
ARAX | | 499 | 499 | 500
BTE | 399 | 303 | | 0?
Improving | 297 | 173 | 240 | 300
Unsecret | 176	| 270 | 173 | 229

Fourth	https://ui.test.transltr.io/main/results?l=Diabetes%20Mellitus&i=MONDO:0005015&t=0&q=11d672b6-65d0-4ee6-b7a6-9137c0e5966d
  | ARA | First - UI |  UI Refresh | ARAX GUI
-- | -- | -- | -- 
ARAGORN | 497 | 449 | 500 
ARAX | | 499 | 500
BTE | 380 |  | 
Improving | 295 | 238 | 300 
Unsecret | 173	| 171 | 229 

Adding two more examples - 

**Test - Alzheimers**
BTE 
UI shows 102: https://ui.test.transltr.io/main/results?l=Alzheimer%20Disease&i=MONDO:0004975&t=0&q=61c03c7d-f1a4-4786-a1ac-d980804b83c1
ARAX GUI shows 500:  https://arax.ncats.io/beta/?r=61c03c7d-f1a4-4786-a1ac-d980804b83c1

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/8a31e18c-aa14-403a-a2c8-1ca0f3ca21ea)

I dont really understand how the Reasoner filter is calculated, I assume this mismatch could be:
- duplicate answers within BTE that the UI merged - seems a little odd 400 would be duplicates
- lookup result merges? but Rivastigmine does indicate ARAX and imProving Agent

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/4680deba-e5f7-495b-94a3-afb8f2193f69)

**Test - Stiff Person Syndrome**

Watch the video, you'll see that BTE results are displayed and then completely disappear.  Similar with ARAGORN, originally the UI shows 30 results then down to 16

https://drive.google.com/file/d/1C64EEUBa6LhxZp3HT7WLEXhqVXtDPHAM/view?usp=drive_link

https://ui.test.transltr.io/main/results?l=Stiff-person%20Syndrome&i=MONDO:0008491&t=0&q=0c1fc01c-bf74-4e31-9280-5721b0eb77e9

Not sure ho m

**Comment by gprice1129** [comment]
@sstemann I'll look into this today.

**Comment by MarkDWilliams** [comment]
I've taken a look at this and I believe I understand the issue.  Currently, the ARS has to do all of the merging and post processing work in the same place (and after the fact) of receiving the POSTed results from an ARA.  What this can cause, and I believe did cause at least in the case of BTE, is:

1. BTE sends results back to ARS
2. ARS takes too long to send back a 200, but has actually received and saved the results and is just doing additional processing
3. BTE, having heard nothing back from us for too long, sends a follow up saying `TimeoutError: Promise timed out after 300000 milliseconds"`, which overwrites the perfectly valid results that we already had.

So, the crux of the issue is really that the ARS is taking an unreasonable amount of time to respond with a 200 due to (effectively) unrelated stuff that we are doing.  I am going to push a quick change to simply disallow updates which lack results to overwrite ones which have them just to get the ball rolling through the environments with _a_ fix.  However, I will also work on fixing this the right way and having the ARS do the merging and post processing asynchronously.

**Comment by sstemann** [comment]
In Test, with upgrades from Aragorn, Aragorn Ranker, Strider, WF Runner, Answer Appraiser, MolePro and ARS, the numbers are off 

ADHD Inattentive
UI:  https://ui.test.transltr.io/main/results?l=Attention%20Deficit%20Hyperactivity%20Disorder,%20Inattentive%20Type&i=MONDO:0005302&t=0&q=d04bd4d8-b617-430f-b170-574082d8aea7
PK: d04bd4d8-b617-430f-b170-574082d8aea7
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/dfe540cf-ed6c-4ae9-91f1-dc39bad55e01)

Atomoxetine -
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/e7fab5c8-7b9c-4a96-bcd6-4e38fe82cc99)

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/ae7c942a-54c9-4576-8068-b31497e9711a)

Stimulant
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/53575579-e908-40cc-8cc7-3974ef11b30a)

**Comment by gprice1129** [comment]
@sstemann I believe @MarkDWilliams says this was an ARS issue unless I'm mistaken.

**Comment by sstemann** [comment]
OBE merging continues to evolve
