### ISSUE TITLE
Unprefixed CURIEs from Aragorn

### ISSUE THREAD

**Issue by gprice1129** [NCATSTranslator/Feedback#582]
**Environment:** Production
**PK:** bee1b6ca-3af4-4d39-8dc3-4cdea8fa2a58
**URL:** https://ui.transltr.io/main/results?l=Bethlem%20Myopathy&i=MONDO:0008029&t=0&q=bee1b6ca-3af4-4d39-8dc3-4cdea8fa2a58

**Issue**
While investigating why the annotator was not returning annotations on Production we found that it returns an error because of some strange looking CURIEs coming from Aragorn. Here is one example:
```
          "node_bindings": {
            "on": [
              {
                "id": "MONDO:0008029"
              }
            ],
            "sn": [
              {
                "id": "FOOD00178" // What am I?
              }
            ]
          },
```

**Comment by cbizon** [comment]
Thanks @gprice1129

**Comment by uhbrar** [comment]
It looks like all of the unprefixed CURIEs are being returned to ARAGORN by spoke-kp, with primary knowledge source "infores:fooddb". I have made an [issue](https://github.com/suihuanglab/spoke-kp/issues/13) on the spoke repo for this.

I do think that the annotator shouldn't fail to validate the entire message for one malformed CURIE and should just just avoid annotating that singular node, however. @newgene would that be possible?

**Comment by cbizon** [comment]
@uhbrar should Aragorn be validating CURIEs?

**Comment by uhbrar** [comment]
Yes, I will be adding CURIE validation.

**Comment by cbizon** [comment]
Yeah, that looks like the right prefix from biolink.

The `inforres:fooddb` is the right one for the primary source.  The other one is a KP that has repackaged the source.

**Comment by newgene** [comment]
When a TRAPI response reaches annotator, I think it's better to assume the returned TRAPI response already passes some level of validation. At annotator, missing-prefix is considered a serious issue, so it returns 400 for user input error. An unknown prefix (but at least in a valid CURIE format) will be skipped.

In this case, I think it's a good reminder when annotator returns 400 errors, so that Aragorn will be notified to fix.

**Comment by MarkDWilliams** [comment]
Let me double check if there is any behavior running on the ARS end that could be causing prefix issues.  If there is anything getting triggered, it would almost certainly be in addition to some issue in what we're receiving from Aragorn, because I believe the only things on our end that would ever edit the infores would be be node normalization or some attempt by the ARS to pre-scrub a problem that would otherwise cause us to have an issue like the one Chunlei described.

**Comment by MarkDWilliams** [comment]
I've taken a look, and I don't believe there's anything the ARS would be doing to cause this.  Ultimately, I think this is an issue that is best solved at the source level.

**Comment by sierra-moxon** [comment]
@uhbrar - I am assuming this can be closed - that aragorn is no longer returning foodb CURIEs without a prefix.  Is this right?

**Comment by sstemann** [comment]
i'm not able to reproduce. it looks resolved. https://ui.test.transltr.io/main/results?l=Bethlem%20Myopathy&i=MONDO:0008029&t=0&r=0&q=79ed45a9-350f-4811-9dd3-15d64e073b65
