### ISSUE TITLE
EPC does not seem complete - Vanadium compound may treat diabetes

### ISSUE THREAD

**Issue by Genomewide** [NCATSTranslator/Feedback#590]
Googling - these compounds do have insulin memetic properties
The epc is a link to SRI reference knowledge graph.  Is this the intended EPC? 

https://ui.transltr.io/main/results?l=Diabetes%20Mellitus&i=MONDO:0005015&t=0&q=4fe4e2b4-9761-443c-b535-71d97797d8f7

![image](https://github.com/NCATSTranslator/Feedback/assets/55069176/c0f967c1-f8e8-4792-8d80-321b23f89df0)

**Comment by sierra-moxon** [comment]
SRI reference knowledge graph is Monarch Initiative and I can imagine Monarch reporting this - is there more EPC that we expect here?

**Comment by cbizon** [comment]
Shouldn't there be a primary KS other than SRI KG?  I know that there has been some back and forth with @EvanDietzMorris and Kevin about it, but I'm not sure where it stands.

**Comment by EvanDietzMorris** [comment]
This is due to the (admittedly complicated) fact that we have a version of the monarch sri-reference-kg that we ingest for robokop, which is a subset of the real sri-reference-kg (but made from an older version of the graph that did not include the actual primary knowledge sources, so it gets infors:sri-reference-kg assigned as the primary source). So - it's a bit of a mess currently we have two redundant infores ids in the catalog for this content (infores:monarchinitiative and infores:sri-reference-kg) but neither should be returned as a primary knowledge source, it should always be an aggregator, assuming every edge in the content has it's own primary knowledge source. We'll need to rebuild our version of this graph, and to pick which infores we want to use as the proper aggregator knowledge source for this content.

**Comment by cbizon** [comment]
So is there a version of the graph that does have the actual PKS listed?

**Comment by EvanDietzMorris** [comment]
Yes, the most recent version of the graph has pks on edges which should come through in TRAPI, but ours doesn’t.

**Comment by EvanDietzMorris** [comment]
This issue was discussed further here #592  - we will be consolidating these infores ids to infores:monarch-kg and removing the renci version from automat.
