### ISSUE TITLE
confusing number of evidence : the same publication is counted twice

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#600]
## Steps to reproduce:
text filter for ergocalciferol
submitted by @sandrine-muller-research

**Comment by sandrine-muller-research** [comment]
The publication is counted twice (from TMKP):
<img width="997" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/22616936/56a95c3c-97e5-408e-991a-7bb28f04ba38">

**Comment by sandrine-muller-research** [comment]
Same here:
<img width="844" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/22616936/a29c7eb9-314a-44d4-a14a-6ed746cb2081">

**Comment by gprice1129** [comment]
Hi @sandrine-muller-research. This is a known issue that is caused when the same publication sent to us but one has a PMID and the other has a PMCID.

**Comment by sierra-moxon** [comment]
@cartmanbeck - this is still a low priority to fix from NCATs right?

**Comment by gprice1129** [comment]
The UI team does have a solution for this issue, but currently we believe that the priority is very low compared to the effort involved to implement. This will likely not be implemented in the current phase.

**Comment by sierra-moxon** [comment]
from TAQA via UI:
- this could impact scoring
- They will be duplicated if we have a PMID and PMCID from another source (for the same pub).
- One will show the abstract, one will show the full text
- We'd need some sort of node normalization for PMID and PMCID -- we have it in NN, we need to push that to the annotation service to use in the UI.  (all this might be too much for this phase). 
- enforce KPs only to provide PMIDs? PMCIDs?  - maybe.

**Comment by bill-baumgartner** [comment]
I don't know if KPs other than TMKP return PMCIDs, so this issue may be somewhat TMKP-specific. When we extract an assertion from the full text of a paper, we are reporting PMCIDs to signify that the assertion came from somewhere in the full text so that the user can go find the evidence sentence in the original document if desired.

One possible solution here would be to always return the PMID if there is one, and to have a secondary publication identifier, e.g., PMCID, when appropriate. That way, the UI would always have PMIDs to use to disambiguate publications.
