### ISSUE TITLE
Weak predicate patterns supported for Lactose Intolerance

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#601]
## Steps to reproduce:
select pesticides as ChEBI role (filter option)

**Comment by sandrine-muller-research** [comment]
Ergocalciferol
Mebendazole
Bithionol
Thiabendazole
Levamisole
Methamidophos
Potassium bicarbonate
Triclosan

They are all pesticides (not likely to treat a disease!), and their predicates chain pattern is:
... --> treats --> phenotype of --> ... 
That does not seem a very convincing reasoning (although ranked pretty high), particularly when it seems to treat a lot of diseases (and only that):
<img width="1043" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/22616936/e640cb0c-d311-4d69-9e71-8bd6ad106797">

**Comment by gglusman** [comment]
Egocalciferol is indeed used as a rat poison, but also as a synthetic vitamin D... it's not just a pesticide.
A drug being labeled a 'pesticide' doesn't immediately make it a wrong answer to every question.
I'd say that the issue here is the somewhat weak reasoning pattern of treating symptoms... though that is not infrequently the only thing left to do.

**Comment by sandrine-muller-research** [comment]
related to feedback from @khanspers on tacrolimus, same predicate pattern:
<img width="940" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/22616936/ed43f3f2-abd6-4a2a-97a1-e0447f18c157">

**Comment by sandrine-muller-research** [comment]
yes, fully agree with you @gglusman ! I use the ChEBI role "pesticides" as a surrogate to test those week patterns. I realized that in many queries it comes back and has weak predicates patterns.  Usually I only reports issues when the pattern is weak if I have a doubt either I have time to search the literature or I do not report it. 
I'll change the title though, good point.

**Comment by sierra-moxon** [comment]
for this one, I hope the review team can come up with a decision on a few key things in this issue:
1) is the reasoning path reasonable?
2) is the result of that reasoning path scored appropriately in the context of the evidence?
3) is this ticket a priority to handle and are the people assigned the right ones?

**Comment by sierra-moxon** [comment]
from TAQA:
- while logically sound, not great from SMEs, but still, is it a problem? 
- perhaps can be explained via scoring relay session
- this might be a "treats" is special problem.  Treats is really complex - its a hard question.  
- this is treating symptoms, its not necessarily wrong.  

Are these bad answers because the reasoning is bad, or just bad answers in general.  If they are just bad, we put in a test to fix that.  If the reasoning is bad, (they are ok answers, but some are uncomfortable with the reasoning paths, then this is a discussion topic and/or handle disagreements of what is good reasoning).

**Comment by sandrine-muller-research** [comment]
@sierra-moxon Like @gglusman pointed out, the compounds might not be bad per se. As a user, when I see that:
- (1) they are tagged as pesticides (I infer here that they are potentially triggering death e.g. excess of vitamine D causes death), 
- (2) the reasoning path is not necessarily true (basically it is inferring that if a compound C is a treating a phenotype P of the disease D it is treating the disease; while this inferrence could work, I do not think it is very probable without the other edge C-treats->D)
- (3) the compound is linked to many phenotypes (that are sufficiently far appart)
The association of all those 3 points makes me say it does not seem a good answer at all. I think it should be a question for the scoring session/team.

**Comment by sandrine-muller-research** [comment]
retested today.
None of the pesticides I found earlier show up now! (Ergocalciferol,Mebendazole, Bithionol,Thiabendazole,Levamisole, Methamidophos, Potassium bicarbonate, Triclosan
Closing
