### ISSUE TITLE
Autocomplete: normalize kinetin

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#633]
## Steps to reproduce:
MVP1 on 
submitted by @sandrine-muller-research

**Comment by sandrine-muller-research** [comment]
<img width="968" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/22616936/f4020feb-ff1f-48ec-86c2-551020083c49">

**Comment by sandrine-muller-research** [comment]
so it seems it is a display issue:
<img width="586" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/22616936/245b62ce-21c3-43ef-92b7-ca755f63f523">

**Comment by gprice1129** [comment]
Hi @sandrine-muller-research. This is a normalization issue, the UI cannot determine by the IDs that these are the same entity.

**Comment by sandrine-muller-research** [comment]
I put a UI also display because in when this occurs (and it will occur for some time as normalization of chemical is pretty hard), we get 2 tooltips that give different info (can we have just one?) and I suppose because we get 2 tooltips they disappear and we cannot click on any of the links.

**Comment by gaurav** [comment]
UMLS:C0049579 and PUBCHEM.COMPOUND:3830 are [back in the same clique on NodeNorm Test](https://nodenorm.test.transltr.io/1.4/get_normalized_nodes?curie=UMLS%3AC0049579&conflate=true&drug_chemical_conflate=false&description=false). Since that's the last bug remaining in this issue, I'll go ahead and close it.
