### ISSUE TITLE
cannot click on link

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#634]
## Steps to reproduce:
MVP1 on Hereditary Sensory And Autonomic Neuropathy
submitted by @sandrine-muller-research

**Comment by sandrine-muller-research** [comment]
The link disappear when I try to click on it:
https://github.com/NCATSTranslator/Feedback/assets/22616936/b2c6fc9a-f3df-4604-a262-1bbec5169096

**Comment by sandrine-muller-research** [comment]
I moved my screen and saw this:
<img width="586" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/22616936/9fdbdd13-88f1-4a2f-8015-2182292402f0">

**Comment by dnsmith124** [comment]
Now this is a very strange bug I haven't seen before! Here's my diagnosis of the issue:

There are two instances of Kinetin in the results, one of them is a small molecule and the other is a drug. The tooltips operate based on an id that is generated based on the name of the entity in question (in this case Kinetin), along with a set of numbers based on where the node is listed in the paths. So for both this node and the first node of the first path of the _other_ Kinetin result, the generated tooltip id is `Kinetin0_0`. This means that when you hover over the first node of either Kinetin result it shows _both_ tooltips. 

Since the small molecule version of Kinetin shows up first, that means the tooltip for the drug version is rendered after the small molecule version's tooltip, so that when the application checks to see if you're hovering over the small molecule tooltip to see if it needs to hide it, you technically aren't since the drug version's tooltip is rendered on top of it. This explains the behavior in the above video. 

I'm working on a change now to the tooltip generation to ensure that they are always unique, even in these edge cases, which will solve the problem.

**Comment by dnsmith124** [comment]
This issue has been resolved and deployed to CI, though both instances of Kinetin don't return in that environment, only the small molecule one. I was able to recreate both instances returning in my local environment, and can confirm the fix works there. 

Closing.
