### ISSUE TITLE
Normalization of Esomeprazole

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#647]
## Steps to reproduce:
search for Esomeprazole

**Comment by sandrine-muller-research** [comment]
<img width="1247" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/22616936/d581b24d-80b8-49a4-8cf3-9007fb489d75">

**Comment by sandrine-muller-research** [comment]
affected CURIES:
- [PUBCHEM.COMPOUND:9568614](http://identifiers.org/pubchem.compound/9568614)
- [UMLS:C1127610](http://identifiers.org/umls/C1127610)
- [UMLS:C1146111](http://identifiers.org/umls/C1146111)

**Comment by gaurav** [comment]
This is now fixed in [NodeNorm Prod](https://nodenorm.transltr.io/get_normalized_nodes?curie=PUBCHEM.COMPOUND%3A9568614&curie=UMLS%3AC1127610&curie=UMLS%3AC1146111&conflate=true&drug_chemical_conflate=true&description=false) as well.

I [re-ran the query](https://ui.transltr.io/main/results?l=Gastroesophageal%20Reflux%20Disease&i=MONDO:0007186&t=0&r=218d548c&q=815d5b24-8da8-4163-bf70-6faf57b9b92b) and the "Esomeprazole 20mg" and "Esomeprazole 40mg" are now gone. So it looks like we can close this.

<img width="1992" alt="Screenshot 2024-07-19 at 2 21 43 AM" src="https://github.com/user-attachments/assets/6abdcfde-501d-4850-8676-8d118acae699">
