### ISSUE TITLE
Searching for "Glucose" yields ~40 related chemicals but does not find D-glucose

### ISSUE THREAD

**Issue by khanspers** [NCATSTranslator/Feedback#659]
I tried the "Find genes regulated by a particular chemical" query, and tried finding Glucose by typing in "glucose". About 40 chemicals come up, but none of them are D-glucose. In order to find genes regulated by glucose, the user has to search for "D-glucose".

**Comment by khanspers** [comment]
This appears to have been fixed, searching for "glucose" now just results in one option (Glucose, CHEBI:15903). Searching for "D-glucose" also results in one results (D-glucose, CHEBI:4167). Tested in ui.transltr.io and https://ui.test.transltr.io/. This can probably be closed.

**Comment by gaurav** [comment]
The good news is that this is indeed fixed in Test and Prod! However, the newly deployed CI conflates CHEBI:15903 "glucose" into CHEBI:4167 "D-glucose", which results in CHEBI:29042 "glucose-1-phosphate" being the best match (CHEBI:4167 is the second best match, but as UI currently only shows a single result for chemicals, that's not good enough).

I'm currently working on an improved NameRes query that might be able to fix this issue without changing the conflation. If there's a lot of issues like this, I'll delay pushing the current CI to Test and Prod until we've fixed this issue.

**Comment by gaurav** [comment]
Current status:
- TEST has D-glucose as the second best match (and UI now shows multiple results), so that's not too bad.
- CI has D-glucose as the best match.

I'll go ahead and close this, but please reopen if it continues to be an issue!

**Comment by sstemann** [comment]
test went to Prod last night.  so this is fixed with the Fugu release to Prod

![image](https://github.com/user-attachments/assets/65dd8ee8-867f-44cb-8ca5-d146cb63b25c)
