### ISSUE TITLE
Evidence Totals vs Path  Totals

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#669]
In Test UI, run what drugs may treat Monkeypox

https://ui.test.transltr.io/main/results?l=Monkeypox&i=MONDO%3A0002594&t=0&r=3a1ca84f&q=dc67c9ee-a689-461a-99f7-22bff7f28697

The first result is Ethanol with 5336 Publications, 5 sources
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/a10777ab-c3d1-48b2-99e7-2bb6dd72cf94)

But when I click through the five paths, the total publications I can view are about 116.  

It also looks like there are about 3 unique KS's 
Unsecret
TMKP
Diseases

A second example is what drugs may treat Eclampsia
https://ui.test.transltr.io/main/results?l=Eclampsia&i=MONDO%3A0001754&t=0&r=333144e2&q=23c80785-d1b5-477b-9c30-40f280c591a2

The first result says 213 Pubs and 4 sources but the only path says 128
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/96da4a5e-ebff-4c34-b3ad-1406cb3a0c1e)

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/954e003f-8552-421b-a45c-2d8862882edb)

1 KS
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/e3b549bc-7242-4d9b-8eaf-993f27f28a10)

**Comment by dnsmith124** [comment]
Currently investigating this issue

**Comment by dnsmith124** [comment]
Apparently there was an issue with the counts being calculated improperly on some results, such that publications of the same ID could occur twice in the count. This resulted in the count on the result being off, but all the publications still displayed properly in the modal. I've addressed this issue as well as another with regard to the knowledge sources for an edge sometimes only displaying the first KS rather than all of them. The fix is live in CI, here's an example: 

https://ui.ci.transltr.io/main/results?l=Eclampsia&i=MONDO:0001754&t=0&r=0&q=669a0874-f2c6-46e3-8d53-d98e60b4960b

**Comment by dnsmith124** [comment]
Complete, closing.
