### ISSUE TITLE
'no title available'

### ISSUE THREAD

**Issue by gglusman** [NCATSTranslator/Feedback#681]
https://ui.test.transltr.io/main/results?l=Pityriasis+Rubra+Pilaris&i=MONDO%3A0100017&t=0&r=94e5d39e&q=cfcdc63b-f49f-4ebd-bda1-c2510bd353f1

<img width="880" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/3977332/f0b22a72-4c79-496d-9d9f-9b6da05f8c33">
6th reference:
<img width="1216" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/3977332/3bee3a07-5a01-4993-ae66-6b7fa0152c77">
In PubMed, it does show a title:
<img width="686" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/3977332/e811ed06-c5a2-48bb-9b90-9ad473acb3a3">

**Comment by gaurav** [comment]
I'm not sure where this missing title is coming from, but I'm [working on adding PubMed and PMC IDs with titles](https://github.com/TranslatorSRI/Babel/issues/204) to NodeNorm, to be deployed sometime in Feb. So there should be another source of PMID/PMCID titles in Translator by the next release.

**Comment by dnsmith124** [comment]
In this instance it appears the publication server at docmetadata.transltr.io doesn't return a title for PMID:32546899. Here's the request: `https://docmetadata.transltr.io/publications?pubids=PMID:32546899&request_id=26394fad-bfd9-4e32-bb90-ef9d5044f593`

and the returned data: 
`{"_meta":{"n_results":1,"processing_time_ms":1,"request_id":"26394fad-bfd9-4e32-bb90-ef9d5044f593","timestamp":"2024-01-23T15:5156Z"},"results":{"PMID:32546899":{"abstract":"Purpose: Biotechnological substances (BSs) are strongly relied upon to prevent rejection of transplanted organs, and to treat oncological, allergological, and other inflammatory diseases. Allergic reactions to partly foreign biologics can occur due to their potential immunogenicity. The severity of an immune response to a biological drug may range from no clinical significance to a severe, life-threatening anaphylactic reaction.Methods: Detailed searches were performed on Pubmed, Web of Science, and Google Scholar to include all available publications. In addition, the Food and Drug Administration, the European Medicines Agency, and British Columbia Cancer Agency Drug Manual databases were screened for hypersensitivity reaction (HSR), infusion reaction, injection site reaction, urticaria, and anaphylaxis for individual BSs.Results: Treatment with BSs can cause various types of HSR. These are mentioned in the literature with definitions such as allergic reactions, anaphylactoid reactions, anaphylaxis, HSR, infusion reactions, injection site reactions, cytokine release syndrome, and urticaria. Due to the overlap in signs and symptoms in the reported descriptions, it is not always possible to differentiate these reactions properly according to their pathomechanism. Similarly, many data reported as anaphylaxis actually describe severe anaphylactic reactions (grades III or IV).Conclusion: There is an urgent need for a simpler symptom- or system-based classification and scoring system to create an awareness for HSRs to BSs. A better understanding of the pathophysiology of HSRs and increased clinical experience in the treatment of side effects will provide timely control of unexpected reactions. As a result, immunotherapy with BSs will become safer in the future.Cite this as G\u00fclsen A, Wedi B, Jappe U. Hypersensitivity reactions to biologics (part I): allergy as an important differential diagnosis in complex immune-derived adverse events. Allergo J Int 2020; 29:97-125https://doi.org/10.1007/s40629-020-00126-6.\n","article_title":"","issue":"","journal_abbrev":"Allergo J","journal_name":"Allergo Journal : interdisziplinare Zeitschrift fur Allergologie und Umweltmedizin : Organ der Deutschen Gesellschaft fur Allergie- und Immunitatsforschung","pub_day":"24","pub_month":"Jun","pub_year":"2020","volume":"29"},"not_found":[]}}
`

The important part of that JSON in our case being: `"article_title":""`

**Comment by sierra-moxon** [comment]
@bill-baumgartner - is this a service from TMKP?  Is it possible that this publication needs a title update?
The UI does eventually show the title and it is available at PubMed.

**Comment by bill-baumgartner** [comment]
@edgargaticaCU -- would you mind taking a look at this issue? It appears that no title is being returned from the publication metadata service for `PMID:32546899`.

**Comment by edgargaticaCU** [comment]
![image](https://github.com/NCATSTranslator/Feedback/assets/88678635/8a4ea5ff-3ce5-4a90-a5ff-da13bce7d6b1)
@bill-baumgartner 
The API returns an entry for this PMID, but the `article_title` field is blank. I will track down the original processed file to see if this an upload issue.

**Comment by sstemann** [comment]
@gglusman I can't recreate this one.  can you?

On Prod https://ui.transltr.io/main/results?l=Pityriasis%20Rubra%20Pilaris&i=MONDO:0100017&t=0&r=0&q=9100072c-3864-4b80-86c7-d5c3f4642825

Or On Test
https://ui.test.transltr.io/main/results?l=Pityriasis%20Rubra%20Pilaris&i=MONDO:0100017&t=0&r=0&q=11c31e0e-c504-410f-bba4-efc085f4d04b

**Comment by gglusman** [comment]
Can't really figure out if it was fixed, since CD4 is pretty much absent from the results. Only one result (nevirapine) mentions "increases CD4 counts" in the description, but there's no CD4 node anywhere to be found...

**Comment by sstemann** [comment]
my only other thought is, would that pub show up for any other connection that might be in the results?

**Comment by gglusman** [comment]
I think we can safely close this for now. :)
