### ISSUE TITLE
linkout URLs that fail (identifiers.org->linkedlifedata.com)

### ISSUE THREAD

**Issue by gglusman** [NCATSTranslator/Feedback#685]
One example for a failure I've seen a number of times:

Revisiting ["what drugs may treat hypotensive disorder" on 2024/1/11](https://ui.test.transltr.io/main/results?l=Hypotensive+Disorder&i=MONDO%3A0005468&t=0&r=f96fbcf4&q=62f1f551-f0ac-4423-b23a-c5e7f836e2e9).

The 'cocoa bean allergenic extract' result links to http://identifiers.org/umls/C2722034, which resolves to http://linkedlifedata.com/resource/umls/id/C2722034, which fails with a 502 Bad Gateway error.

**Comment by gaurav** [comment]
The absolutely correct URL to see the definition of UMLS C2722034 is https://uts.nlm.nih.gov/uts/umls/concept/C2722034, but you need to confirm your identity to see that. Some UMLS identifiers are also available on the NCI Metathesaurus (in this case, https://ncim.nci.nih.gov/ncimbrowser/ConceptReport.jsp?dictionary=NCI%20Metathesaurus&code=C2722034, which does work), but I'm not sure if every UMLS identifier is present on the NCI Metathesaurus website (this is roughly the identifier that Wikidata uses, see https://www.wikidata.org/wiki/Property:P2892). LinkedLifeData.com appears to be [run by Ontotext](https://www.ontotext.com/knowledgehub/demoservices/linked-life-data/), so it might be worth reaching out to them and asking if they can get their website working again.

Incidentally, we normalize this identifier to a UMLS ID because [biolink:ChemicalEntity](https://biolink.github.io/biolink-model/ChemicalEntity/#valid-id-prefixes) doesn't include DrugBank (or RXCUI) as valid prefixes for ChemicalEntity -- if that was the case, we would use [DRUGBANK:DB10977](https://go.drugbank.com/drugs/DB10977) as the preferred ID for [this clique](https://nodenormalization-sri.renci.org/get_normalized_nodes?curie=UMLS:C2722034&conflate=true) instead in NodeNorm. I've filed issues for this [on Biolink Model](https://github.com/biolink/biolink-model/issues/1448) and [on Babel](https://github.com/TranslatorSRI/Babel/issues/222).

**Comment by cbizon** [comment]
It's unclear where the URL expansion from UMLS:XXXX to http://identifiers... is occuring

**Comment by gprice1129** [comment]
@cbizon This is the CURIE prefix map the UI uses to generate URLs: https://github.com/biolink/biolink-model/blob/v3.6.0/prefix-map/biolink-model-prefix-map.json which is where http://identifiers... is coming from.

**Comment by cbizon** [comment]
Gotcha, so the basic issue here is that the URL expansion for UMLS in biolink model sometimes produces non-resolvable URLs.   The URL that is guaranteed to be resolvable, on the other hand, is not accessible.  Isn't UMLS great?

@sierra-moxon is this a problem for identifiers.org to fix or biolink or ???

**Comment by sierra-moxon** [comment]
saw this ticket this morning one action item: get Drugbank into the prefix list (Gaurav's issue)
I don't know how to resolve unresolvable or private identifiers.

**Comment by cbizon** [comment]
I'm not sure about drugbank, it seems like the identifiers are resolvable?  e.g. https://go.drugbank.com/drugs/DB00619
My reading of the https://dev.drugbank.com/guides/faqs indicates that we should be fine using their identifiers.

But for UMLS there will still be issue because the real URI for the concept is only resolvable behind a login.  The open version of the URI (the linkedlife) doesn't always work.

So I think that the options for UMLS entries are
* Try very hard to point somewhere else besides UMLS, even if UMLS is the first entry.
* Try to find a different source of UMLS resolutions
* Never provide linkouts for UMLS
* Provide linkouts for UMLS and accept that sometimes they will fail
* Somewhere (UI?) try to hit the resolved URL and if it 502's then don't include it

My personal preference is for a combination of the first (minimize UMLS linkouts) and the last (intercept bad linkouts).
@gprice1129 @sierra-moxon what do you think?

**Comment by gprice1129** [comment]
@cbizon I think implementing the first bullet is a good place to start. I don't want to commit to doing the last one yet :)

**Comment by sierra-moxon** [comment]
I tried testing this again today; I think this issue is either resolved or sufficiently hidden with the hiding of generic results.  The top 10 answers I saw were not linked to UMLS. 

Our solution to try here, was to use non-UMLS identifiers with preference. I am very tempted to close this as I don't know how else to define done here.  

@maximusunc - do you have any thoughts on a test runner to confirm links of our nodes?  Maybe that is worth it at some point?

For now I am going to close; of course reopen if I am being too premature here.
