### ISSUE TITLE
BTE as a Curated Source in the Evidence Modal?

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#696]
In UI Test > Run MVP1 for Myopathy, Lactic Acidosis, And Sideroblastic Anemia

https://ui.test.transltr.io/main/results?l=Myopathy,%20Lactic%20Acidosis,%20And%20Sideroblastic%20Anemia&i=MONDO:0000863&t=0&r=0&q=15b85852-f5f5-4fac-8561-802519c105d9

Take a look at result: Docetaxel > in the first inferred path > second row:
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/b8b578dd-0b26-4253-b459-51eb471ea263)

- it's a little odd that the Inferred Edge Treats is also tagged as Curated at the super-level 
- make it read like - these path are inferred via this curated one-hop (which seems similar to the definition of a lookup)

The evidence from Dysphagia to Myopathy, Lactic Acidosis, And Sideroblastic Anemia, is tagged with the ribbon (curated) and lists BTE:
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/e252c0d4-83c7-44db-8a49-c53a8678fa5e)

In the ARAX viewer, this link doesn't seem to have proper EPC - so I'm not sure if this is on BTE, ARS, or UI
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/b48b71cf-2c71-48e8-abd6-ed78662c96bb)

I wouldn't think that an ARA would be a primary source for a curated edge?  I could be misunderstanding the curated edge meaning or the scope of BTE.

**Comment by sstemann** [comment]
@MarkDWilliams can you check on the second part of David's comment?

**Comment by MarkDWilliams** [comment]
@dnsmith124 I'm not sure I understand what you mean about the merge process removing this edge.  Could you elaborate?

**Comment by dnsmith124** [comment]
Been a while since I reviewed this, but I believe I was referring to the fact that the edge in question (Myopathy, Lactic Acidosis... => has Phenotype => Dysphagia) has no primary knowledge source (or any EPC at all it seems). I was operating under the assumption that the ARS merging would remove such an edge, is that correct? @MarkDWilliams 

The edge I was referring to:
![Screenshot 2024-04-02 at 11 55 17 AM](https://github.com/NCATSTranslator/Feedback/assets/54226761/09eb3eaf-061f-4016-ab35-4bfaacfc99e7)

**Comment by MarkDWilliams** [comment]
Ah, thank you for the clarification and apologies for the late reply.  I must have missed the notification.  I understand now, and yes if there are no sources for the edge because we removed them with the blocklist, then ARS should have removed it edge when it had no sources left.  I will look into what caused that to not happen in this case.

**Comment by sstemann** [comment]
i'm seeing HPOs instead of BTE in that Phenotype Of EPC
