### ISSUE TITLE
Multiple Inferred "Super" Paths

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#718]
There's one inferred edge in the graph view and three inferred "super" paths

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/eebbabcd-031d-431a-b075-644bfe17cd82)

The middle path says its inferred from manual curation within BTE:

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/2848b768-525f-466b-92d3-7521253f81ba)

The last path seems to have the specified predicate qualifiers while the first two do not:
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/3494a42f-821e-441e-b970-33a2ddcbb45e)

Mostly though, its just a lot of noise - I dont know if this is a UI, merge, or ARA issue

What chemicals may upregulate TFPI

https://ui.test.transltr.io/main/results?l=TFPI%20(Human)&i=NCBIGene:7035&t=1&r=0&q=72ec18aa-caee-4e39-8929-19c7cf70e718

**Comment by dnsmith124** [comment]
@gprice1129 can you take a look at this?

**Comment by mbrush** [comment]
Wanted to note the specific issues I see in this example (I think some overlap with what sarah pointed out):

1. The second inferred result has a dashed arrow implying it is inferred, but also a 'curated' icon on the affects predicate. Clicking the predicate reveals BTE to be the only source - suggesting this is indeed an ARA-predicted/inferred result.  Seems like there shouldn’t be a 'curated' icon on this edge, or inferred edges generally.   
 
![image](https://github.com/NCATSTranslator/Feedback/assets/5184212/1b3afb81-6190-48fb-84b7-533a2de25b33)
 
The second edge in the support path for this second inferred result is 'upregulated' . . . is this 
what the UI parses the 'causes upregulated activity or expression of'  combination of qualifiers into (for purposes of a snappier label)? 

 
 
 
The third inferred edge shows the predicate 'affects increased activity or abundance of' - instead of 'causes increased activity or abundance of' . . . not sure if the issue is in the underlying data or a mis-parse on the UI end. This is an ARAGORN-inferred edge @chrisbizon
 
 
Finally, the final support path for this third inferred result seems problematic in both hops.  The first hop says that a Drug 'causes' a Gene . . . my guess here is that there are qualifiers missing from the underlying data, or that are in the data but not properly parsed into a composed predicate here (e.g. 'causes increased activity of').  The second hop says that a Gene 'has increased activity or abundance caused by' a Gene in the second hop  . . . seems like the causal direction at this hop is wrong here to infer a Oxaliplatin 'causes increased activity of abundance of' Gene prediction.

**Comment by gprice1129** [comment]
For the UI portion of this:
1. The graph does not handle the new inferred/lookup paradigm very well yet. My guess is that multiple inferred edges are laying on top of each other on the graph so it is impossible to distinguish them. Is that right @dnsmith124?
2. The BTE/curated problem is due to a mislabeling in the infores-catalog v3.6.0
3. Qualifiers come back inconsistently from ARAs as far as I can tell. Especially for MVP1.

**Comment by gprice1129** [comment]
@mbrush 
1. This is a bug caused by BTE having the wrong knowledge level in the infores-catalog v3.6.0
2. That is right, the UI does some extra work here to make things pretty
3. This means that the ARA did not send back the qualified predicate `causes`
4. The first edge is missing the qualifiers. The directionality shown in the second edge is correct based on the underlying data. This is one of those times where the graph has some connection between the search term and answer, but it does not seem causal... In these cases the path display is probably not he best way to visualize the data.

**Comment by dnsmith124** [comment]
@gprice1129 That's correct

**Comment by sstemann** [comment]
I believe 1. is resolved.

It seems like @mbrush @gprice1129  are saying 3. and 4. are issues with the underlying answer graph - which is coming from ARAGORN @cbizon @uhbrar 

https://ui.test.transltr.io/main/results?l=TFPI%20(Human)&i=NCBIGene:7035&t=1&r=0&q=dbcc0ce7-f6fd-4764-9b93-8fd3fc8d582e

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/7fd03c4f-3906-4808-979c-3e17eb94b2eb)

3. on the ARAX GUI:
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/7441c445-581a-495a-bfef-ac0566a88e4e)

4. on the ARAX GUI:
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/b0a2fe81-9b75-4cc8-bfdd-7bd82ccdbda5)

New 5. this support graphs - i'm not sure i understand how it supports the result
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/6e52a19e-053a-44b1-93e9-4a83ad57177d)

**Comment by cbizon** [comment]
Within ARAGORN, this is being tracked here: https://github.com/ranking-agent/aragorn/issues/234
The original Feedback issue: https://github.com/NCATSTranslator/Feedback/issues/744

I think that there's still an open question about whether this qualified_predicate should be sent as part of the query.

**Comment by sstemann** [comment]
i know we have the fully qualified predicate in CI.  i think we should plan for this for Guppy, because I think there were issues with the fully qualified and it's not in Fugu yet.

**Comment by sstemann** [comment]
upon retesting this is resolved in Fugu
