### ISSUE TITLE
UI does not display all available edge attributes, e.g., probabilities and relatedness metrics between genes

### ISSUE THREAD

**Issue by karafecho** [NCATSTranslator/Feedback#72]
One of the QotM SMEs requested that Translator returns probabilities or relatedness metrics with associations in answer sets to support relationships between, e.g., _ALAS1_ and related genes. This request is being addressed, or is at least recognized, by the O&O, EPC, and UI teams. Moreover, the clinical KPs return metrics such as probabilities in edge attributes. However, the clinical KPs would not be able to respond to the specific use case that arose during the QotM, and so, this issue is open for comment.

**Comment by sandrine-muller-research** [comment]
MolePro provides CMAP, DepMAP, and STRING for gene--gene relationships. 
[Here](https://github.com/broadinstitute/molecular-data-provider/blob/molepro-master/MoleProAPI/java-play-framework-server/conf/dockerTransformers-prod.txt) you will find our deployed services from which gene -- gene relationships under _profile similarity_ (lines 81-82 and 107):
# profile similarity
[...]
https://molepro-cmap-transformer.transltr.io/cmap/gene/gene
https://molepro-depmap-transformer.transltr.io/depmap/correlation

# protein-protein interactions
https://molepro-string-transformer.transltr.io/string/links

**Comment by sandrine-m** [comment]
I agree for closing if the answer was sufficient? Because I saw "KP**s**", in the title I never closed the issue thinking that other KPs needed to weigh in. This issue is wrong label to me, as Sarah suggested it is just the UI not showing the "biolink:correlated-with" edges that are exposed to translator. This is linked with one of the issue I posted about having "correlated_with" edge reported by UI but no value shown. Only biolink:publication is shown for the moment if I am correct? This is a UI display IMO. @sstemann, I saw you changed label. what was your impression?

The info is available to Translator through MolePro ([here](https://translator.broadinstitute.org/molecular_data_provider/transformers) is a list of all MolePro transformers). If you search for the transformer urls I shared above you will get all the info you need to hit MolePro with the correct json object. Most importantly it will tell you _which predicates_ the info you are looking for is attached to.

As a user I think the easiest would be to submit this json object through [ARAX UI](https://arax.ci.transltr.io/?r=1a965d74-7a25-48c3-a646-d00f70d61989):
```
{
  "edges": {
    "e00": {
      "attribute_constraints": [],
      "object": "n01",
      "predicates": [
        "biolink:correlated_with"
      ],
      "qualifier_constraints": [],
      "subject": "n00"
    }
  },
  "nodes": {
    "n00": {
      "constraints": [],
      "ids": [
        "NCBIGene:775"
      ],
      "is_set": false
    },
    "n01": {
      "categories": [
        "biolink:Gene"
      ],
      "constraints": [],
      "is_set": false
    }
  }
}
```
In this example you can see that MolePro returned 136 edges, here is an example for CMAP:
<img width="1166" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/66342541/a2b96012-7eb1-4cbd-803d-bfe6619c064d">

I hope it helps!

**Comment by karafecho** [comment]
The requested metrics are now being captured as edge attributes and returned in results. These are visible via the ARAX UI, but I don't think these are visible in the Translator UI. 

I agree with Sandrine that this is really a UI issue. As such, I've renamed the title and changed the label. Let's leave this issue open for now, but probably in the post Sept bucket.

**Comment by gprice1129** [comment]
@karafecho @sandrine-m @sstemann the UI team needs some clarification on what exactly is being requested. We understand there is some data being sent that we are not capturing but some discussion with examples would be tremendously helpful.

**Comment by karafecho** [comment]
Sure thing, @gprice1129. You can find a few examples from the clinical KPs here: https://github.com/NCATSTranslator/Clinical-Data-Committee-Tracking-Voting/tree/main/Clinical%20KPs/Example_TRAPI_Queries_Edge_Attributes.

Note that the examples may not be entirely up to date, but you'll get the idea.

This issue was triggered by a request from one SME, but I've since had requests from others. Essentially, folks want to see some basic quantitative metrics to support claims such as `correlated_with`, especially for edges derived from non-curated primary sources such as the clinical KPs.

**Comment by sandrine-muller-research** [comment]
+1 on this one. Related to #177

**Comment by gprice1129** [comment]
@karafecho @sandrine-muller-research do these edges show up in the current UI inferred queries?
