### ISSUE TITLE
Daily Med Links in EPC are Duplicative

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#746]
Run MVP 1 for Common Cold in Test https://ui.test.transltr.io/main/results?l=Common%20Cold&i=MONDO:0005709&t=0&r=0&q=52650956-f0dd-43f8-a7df-7b60d6f0cb29
Expand the paths for Aspirin
In the Lookup Path > select Treats > Miscellaneous
There are five daily med pairs
<img width="670" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/96e16ac6-2816-4e9d-8abf-051e789174ba">

Also note: Clinicals Trials are linked on both the Clinical Trials tab and the Miscellaneous tabs

<img width="1064" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/ff7f1fa1-649f-4afa-b433-ddacefd3f004">

ARAX and ARAGORN returns the same DailyMed links twice in the same result, sometimes both ARAs return the same EPC twice:
1. Primary KS: Chembl, Aggregator: mychem-info, aggregator: service-provider-trapi
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/c69eb94d-0f14-41e3-9ad5-b16f701a8dfd)

2. Primary KS: Chembl, Aggregator: molepro, aggregator: arax/aragorn
<img width="800" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/bd7e7f57-9b56-4a69-bf7b-3891bb1312f0">

**Comment by edeutsch** [comment]
Am I tagged because some behavior change is expected from ARAX? This seems like a merging/UI issue, right? The same information is arriving via different paths and it contains the same dailymed attributes. It is the same CHEMBL record that has the information, but it arrives via molepro or BTE or ARAX or Aragorn. Which I think is all good, right? It just needs some refinement at the merging or UI level?

**Comment by sstemann** [comment]
@edeutsch I guess I was looking for confirmation that this is expected behavior - to return two triples with identical primary knowledge sources for the same result.  I'm not sure I understand value is added when a different aggregator aggregates the same primary knowledge source via the same triple.

**Comment by gprice1129** [comment]
@sstemann it appears that the links in the screenshot are not exact duplicates. One has a protocol of `http` and the other has a protocol of `https`. However given that semantically they are the same we have decided to convert all `http` links to `https` which should remove the dailymed duplicates.

The clinical trials show up in in both tabs because we are given both the clinical trial ID and the link to the clinical trial by different sources. We will resolve this on our end by converting the clinical trial link to an ID.

I'll message again once the change is live and can be tested.

**Comment by gprice1129** [comment]
I couldn't prove this was fixed in CI because we're getting different paths back that do not have this example. I was able to prove this was fixed with the specific link. Closing.
