### ISSUE TITLE
Graph View - Paths of Selected Node - the Graying is maybe too subtle?

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#756]
https://ui.test.transltr.io/main/results?l=Common%20Cold&i=MONDO:0005709&t=0&r=0&q=6ec26de1-69ff-44bb-a80e-2ff2c35b97f7

Result: Epoprostenol > I selected CAMP in the graph view and these paths popped to the "top" but:

1. why is there a lookup path in inferred, which does not have CAMP in it?
2. the visual difference is VERY subtle.  not sure i would have even realized there was a difference if i wasn't looking for it:
<img width="844" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/85493a97-db68-4a3a-a994-70fce02e20e8">
3.  Not sure why Lookup paths are still shown, could they be collapsed?
<img width="855" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/10e6c409-6174-4042-bc98-516143ae86a5">

**Comment by dnsmith124** [comment]
1. As far as I know there's nothing that keeps a lookup path from being sent in a support graph for an inferred edge, I don't think the UI is doing anything here beyond displaying what we're given, but @gprice1129 can confirm. 
2. It appears to be that this is a bug in the graph selection algorithm, where due to the position of the selected node in the graph and in the support paths those edges with CAMP are being marked as both _highlighted_ and _unhighlighted_, which results in those paths appearing only slightly different from the entirely unhighlighted ones. I'll get to work on a fix for that asap. 
3. The lookup paths are still shown because there's no way for the user to directly select a 1 hop path in the graph, since clicking on a node is required to make a selection. Right now the default behavior is to show them, though we could look into changing that.

**Comment by gprice1129** [comment]
@sstemann @dnsmith124 is correct. We display the paths we're given and its possible for a lookup edge to also appear as support for an inferred edge. There are a couple possibilities we should consider:

* The UI explicitly removes lookup edges from supporting paths.
* It becomes Translator policy not to include lookup edges as a supporting path.

My opinion is that what Translator doing here is not logically incorrect, so we should do it at the UI level if we decide we want to remove them. The UI team would definitely like feedback from several knowledgeable users that removing them is the correct decision before committing to making this change.
