### ISSUE TITLE
Pubchem Name - Can another name be used once its too long?

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#759]
As an example, in MVP1 for Breast Cancer on Test: https://ui.test.transltr.io/main/results?l=Breast%20Cancer&i=MONDO:0007254&t=0&r=0&q=bbbc4bf4-8ad8-4d6f-9a37-6aa1c5658d3a

This result:  6-(2,5-dioxo-3-sulfanylpyrrolidin-1-yl)-N-[2-[[2-[[(2S)-1-[[2-[[2-[[(10S,23S)-10-ethyl-18-fluoro-10-hydroxy-19-methyl-5,9-dioxo-8-oxa-4,15-diazahexacyclo[14.7.1.02,14.04,13.06,11.020,24]tetracosa-1,6(11),12,14,16,18,20(24)-heptaen-23-yl]amino]-2-oxoethoxy]methylamino]-2-oxoethyl]amino]-1-oxo-3-phenylpropan-2-yl]amino]-2-oxoethyl]amino]-2-oxoethyl]hexanamide

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/755ef8ea-e667-4d9d-855d-f1595462c235)

When I use the CURIE PUBCHEM.COMPOUND:132508503 in NodeNorm, a few other systems give return easier to read labels

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/b82bd16d-3522-4c10-9ee6-eeaf1aeb9082)

     {
        "identifier": "CHEMBL.COMPOUND:CHEMBL4297844",
        "label": "TRASTUZUMAB DERUXTECAN"
      },
      {
        "identifier": "UNII:5384HK7574",
        "label": "TRASTUZUMAB DERUXTECAN"
      },

**Comment by dnsmith124** [comment]
@sstemann is your intention for the UI to resolve this problem? Such as when the UI gets a result that has a name greater than a certain number of characters, it hits node norm to look for a more readable name? Given the number of results that tend to return with these sorts of names we'd be looking at doing this processing on >20 results on any given query. 

Or should this problem be resolved upstream from the UI?

**Comment by gprice1129** [comment]
@gaurav what do you think about ranking labels lower if they fit certain criteria (a lot of non-alpha characters for example)

**Comment by gprice1129** [comment]
UI team needs to discuss internally before assigning a release.

**Comment by gaurav** [comment]
PUBCHEM.COMPOUND:132508503 now has a label of "trastuzumab deruxtecan" on [NodeNorm CI](https://nodenorm.ci.transltr.io/get_normalized_nodes?curie=PUBCHEM.COMPOUND%3A132508503&curie=CHEMBL.COMPOUND%3ACHEMBL4297844&curie=UNII%3A5384HK7574&conflate=true&drug_chemical_conflate=false&description=false), [NodeNorm Test](https://nodenorm.test.transltr.io/get_normalized_nodes?curie=PUBCHEM.COMPOUND%3A132508503&curie=CHEMBL.COMPOUND%3ACHEMBL4297844&curie=UNII%3A5384HK7574&conflate=true&drug_chemical_conflate=false&description=false) and [NodeNorm Prod](https://nodenorm.transltr.io/get_normalized_nodes?curie=PUBCHEM.COMPOUND%3A132508503&curie=CHEMBL.COMPOUND%3ACHEMBL4297844&curie=UNII%3A5384HK7574&conflate=true&drug_chemical_conflate=false&description=false). This is because we [prioritize DrugCentral labels above the other available labels](https://github.com/TranslatorSRI/Babel/blob/1650282025f9b3aa099dc1598fc2dda9571b24a8/config.json#L73-L84)

(Oddly enough, when drug-chemical conflation is turned on, we get [PUBCHEM.COMPOUND:132508503 "trastuzumab emtansine"](https://nodenorm.ci.transltr.io/get_normalized_nodes?curie=PUBCHEM.COMPOUND%3A132508503&curie=CHEMBL.COMPOUND%3ACHEMBL4297844&curie=UNII%3A5384HK7574&conflate=true&drug_chemical_conflate=true&description=false) -- I hope that is close enough!)

Label prioritization by prefix should have eliminated a lot of these issues, but there are still MANY identifiers with very long labels (especially from PubChem). I like @gprice1129's idea of ranking long labels lower (I've created an issue for it at https://github.com/TranslatorSRI/Babel/issues/313). For a quick fix, UI could replace a label that is longer than a particular length (somewhere around 35 characters or so) with the identifier itself (i.e. display "PUBCHEM.COMPOUND:132508503" instead of "6-(2,5-dioxo-3-sulfanylpyrrolidin-1-yl)-N-[...]". Would that be worth implementing?

**Comment by gprice1129** [comment]
The UI team has discussed this and we will be implementing a short term solution.

**Comment by sstemann** [comment]
this result isnt returning any longer.  of the long name compounds, i'm not seeing any that are examples of this where a shorter name is available so i'm closed this.

https://ui.transltr.io/results?l=Breast%20Cancer&i=MONDO:0007254&t=0&r=0&q=5b4ce30a-b1ae-4c82-9e33-9e1881ae3d75
