### ISSUE TITLE
biolink:regulates for chemical-to-gene relationships

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#761]
## Steps to reproduce:
search for SERPINF2

**Comment by sierra-moxon** [comment]
@kaiwenho - is this something you could investigate as part of the Unsecret team?  :) -- we aren't sure quite where the problem lies.

**Comment by kaiwenho** [comment]
This has been fixed in [CI](https://ui.ci.transltr.io/main/results?l=Lepirudin&i=CHEBI:142437&t=4&r=0&q=6673cc99-e4f4-4933-aac2-fd5d37777341), [TEST](https://ui.test.transltr.io/main/results?l=Lepirudin&i=CHEBI:142437&t=4&r=0&q=444c22d1-9084-4ad3-b2c1-44ae8e330fd0), and [PROD](https://ui.transltr.io/main/results?l=Lepirudin&i=PUBCHEM.COMPOUND:118856773&t=4&r=0&q=6d3a3e4a-ba45-49e1-8e64-ec58feea66cd) by utilizing the updated KGs.
