### ISSUE TITLE
Include using susceptibility nodes in example for use cases looking for risk factors

### ISSUE THREAD

**Issue by jh111** [NCATSTranslator/Feedback#81]
Unexpectedly, MONDO has [748 CURIEs for susceptibility](https://www.ebi.ac.uk/ols/search?q=susceptibility&groupField=iri&start=0&ontology=mondo). One was used in the [QotM 5](https://github.com/NCATSTranslator/testing/issues/220) and was very useful for answering questions about risk factors including genes.

[ARS Query](https://arax.ncats.io/?r=a19ac4fd-3211-4a55-bfe1-88582dcfec87)

![image](https://user-images.githubusercontent.com/25163472/186549631-295e42e4-ed81-4233-a75c-db6fdb1f7134.png)

We have discussed templates for risk factors which include a range of predicates, including "associated_with_increased_likelihood_of". It will be helpful for users to include susceptibility nodes in examples/templates, as well as diseases themselves.

**Comment by sierra-moxon** [comment]
@jh111 - are you still interested in keeping this ticket open in the Feedback repo?  I imagine we don't have the right people in this repo, to decide on the next MVP template, especially with the progress we're making on Pathfinder and MCQ.  

Please reopen if you do, otherwise I will close this in favor of surfacing this query via Pathfinder?
