### ISSUE TITLE
Being able to upload word doc or at least pdf would be useful. Only png etc, is possible at the moment, with other file formats would more likely capture more feedback from users (examples etc more than just screenshots.)

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#810]
## Screenshots:
![screenshot](https://raw.githubusercontent.com/TranslatorSRI/IssueScreenshots/main/screenshot_20240701154526048903.jpeg)

**Comment by sstemann** [comment]
i think this is related to the feedback collector, which i dont' think UI created, but i can't remember who did and am hoping you could work them if needed.

**Comment by dnsmith124** [comment]
I'm not sure what the value is exactly for being able to attach text-based files when submitting feedback, since we already have fields where text can be input. What is the sort of feedback from users that would only be sharable in a doc or pdf, and not enterable/reasonable to enter in the text fields? 

I suppose a user might want to include a doc or CSV file with many results from some other source, which they are comparing to UI results, but I'm not sure how common such feedback would be.

**Comment by gprice1129** [comment]
Utility is not clear at this time. If we get more user feedback that supports the feature we will revisit.

**Comment by gprice1129** [comment]
Closing issue. Will revisit if brought up again.
