### ISSUE TITLE
Query Selection Requires User to select from Auto-complete which is not entirely intuitive

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#827]
## Steps to reproduce:
type in query. return not working

**Comment by sstemann** [comment]
not sure how to troubleshoot this - i typed in Bethlem Myopathy and it ran.  I copied and paste and the type ahead still popped up and ran.

**Comment by dnsmith124** [comment]
It sounds like this user didn't click on one of the items in the autocomplete, instead they just typed in a search term and hit Enter, which doesn't actually submit anything. 

We could possibly update the functionality such that hitting the Enter/Return key auto-selects the first term that returns in the autocomplete and then fires off the query. It would solve this user's problem, but also could result in an outcome that might be even more odd, namely typing in something and then hitting enter, only to be greeted by results for a query that you didn't intend to make. This could happen in the case of Heart Disease, which actually returns "Congenital Heart Disease" as the first result in the autocomplete. 

@Genomewide thoughts on the above? Is it a worthy trade-off?

**Comment by gprice1129** [comment]
The UI team needs to discuss internally before assigned to a release.

**Comment by Genomewide** [comment]
yes, we need to discuss this. My first bad idea is that a popup could show if they hit return that explains that due to the breadth of answers possible that have to be tied to a specific id to run the query, they must select from the autocomplete dropdown. Unless there is another interaction out there on the interwebs that makes sense? 

OR - second bad idea - we send them to a page that says this does not match any named entity in translator. and that we recommend selecting from the drop down. BUT if their phrase matches exactly some node then just run it?

**Comment by gprice1129** [comment]
The UI team will be discussing a number of autocomplete bar improvements but will not implement for the next release.

**Comment by sstemann** [comment]
![image](https://github.com/user-attachments/assets/5c50f3c1-1a3b-497d-aa97-de57607b4c94)

if you copy and paste a term, you may not notice or understand the message in red.

**Comment by dnsmith124** [comment]
Pressing the enter key after typing a term now submits a query using the first item in the autocomplete. Feature is live in test, closing
