### ISSUE TITLE
Display Nested Support Paths (BTE) 

### ISSUE THREAD

**Issue by uhbrar** [NCATSTranslator/Feedback#831]
Query is: What drugs may treat Bethlem Myopathy

https://ui.transltr.io/results?l=Bethlem%20Myopathy&i=MONDO:0008029&t=0&r=0&q=0e1c5008-cf66-49b0-b0fc-e5ba31a3a4f0

In result for Dimethyl Sulfoxide, there is a path with an edge who's only knowledge source is BTE.

<img width="1301" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/85633484/bb1ea979-55ea-494f-98e2-97b5d35e08e4">

**Comment by sstemann** [comment]
this can be replicated on Test:

https://ui.test.transltr.io/main/results?l=Bethlem%20Myopathy&i=MONDO:0008029&t=0&r=0&q=b851031e-658e-4d44-a231-08a80f732674

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/756cce0a-4a1a-475a-abe0-60d2521a27ce)

**Comment by Genomewide** [comment]
Adding @dnsmith124 and @gprice1129 to see what they see.

**Comment by Genomewide** [comment]
@tokebe So, this is an example of nested support edges? And those should be shown below the 'phenotype of' predicate?

**Comment by andrewsu** [comment]
Sorry, meant to add some more details when I tagged @Genomewide but got pulled away. 

This is the ARAX visualization of the BTE response:

![image](https://github.com/user-attachments/assets/af154040-7539-4092-b47c-3e88b0f06d51)

and on second look, the UI looks like it has a pretty good visualization of that:

![image](https://github.com/user-attachments/assets/fea88647-5094-43d1-a7bf-583e06f8d3d8)

And the provenance on the inferred edge and subgraphs seem good to me.  I'm not quite sure what the issue is, so maybe I'd turn this back to @uhbrar and @sstemann to describe what they'd expect to see?

**Comment by mbrush** [comment]
As @tokebe noted above, I too suspect this a case where the source actually reports that Flexion Contracture is a phenotype_of some subtype of Bethlem Myopathy, not Bethlem Myopathy directly.  Looking into the HPOA priamry source, this is indeed the case:

![image](https://github.com/user-attachments/assets/6bf20ce8-b057-430b-ba24-1bf3af721b37)

Since it is BTE who is making the subclass inference/logical entailment that Flexion Contraction must also be a phenotype_of Bethlem Myopathy, BTE is credited as the primary source for this edge.  It appears that neither the UI or ARAX GUI are able to show this nested support path that would live under the "Bethlem Myopathy has_phenotype Flexion Contracture" edge. 

This support path nesting approach was how it was decided to implement/report subclass-based inference/entailment a long while back, but only BTE implemented it.  It has been on our list to revisit this decision in light of the current UI / landscape.  at the very least, we should be sure that all ARAs are doing tings consistently ASAP.

**Comment by gprice1129** [comment]
@andrewsu @sstemann @Genomewide I looked into this and the issue occurs because:
1. The UI does not currently show support paths of edges that are themselves in a supporting path. The `phenotype_of` edge is inferred by BTE but the supporting paths do not show.
2. Even if we implemented (1) the UI path generation code will not work for the `phenotype_of` edge above. I will have to look into making it more sophisticated to support this type of example.

**Comment by Genomewide** [comment]
Yeah. I agree with @gprice1129 . Looking at the json, there are support graphs for this edge. 
    {
      "value": [
        "support0-MONDO:0008029-has_phenotype-HP:0001371-via_subclass",
        "support1-MONDO:0008029-has_phenotype-HP:0001371-via_subclass"
      ],
      "attribute_type_id": "biolink:support_graphs"
    }

I don't have an easy way to see what the EPC would be for these. @andrewsu do you know what that would look like?


We need a fully implemented plan to show nested inferred edges.  

@andrewsu would this be this way if we allowed 4 hops?

**Comment by gprice1129** [comment]
Personally I think the way BTE represents this is perfectly valid, its just a matter of supporting it in the UI.

**Comment by sstemann** [comment]
i'm not sure anything is being done here for "guppy" and cannot reproduce the issue in Test or Prod, so assuming this is closed with Fugu #776
