### ISSUE TITLE
Cow milk allergenic extract decreases the activity of NGLY1

### ISSUE THREAD

**Issue by rhubal** [NCATSTranslator/Feedback#838]
### Image 01: The II should be capitalized.

![01 should be II capitalized](https://github.com/NCATSTranslator/Feedback/assets/67760207/57f41fe4-11b9-4f29-8d02-09140f2e9f74)

### Image 02: Should be on block list?

![02 q should be on block list](https://github.com/NCATSTranslator/Feedback/assets/67760207/21b847cb-a3af-4d65-8902-274cffee6043)

**Comment by sstemann** [comment]
@dnsmith124 for image 1 - i've noticed these capitalization issues also, can this be looked at?

for image 2 - @andrewsu @bill-baumgartner it looks like the snippets have "milk", i'm not sure why its mapped to RXCUI:892666. it may be intentional - @MarkDWilliams should it go on the block list?

i re-ran the query today - its here:  https://ui.test.transltr.io/main/results?l=NGLY1%20(Human)&i=NCBIGene:55768&t=2&r=0&q=cef9431a-9f6f-420d-915e-6e38b3a36bc6

**Comment by dnsmith124** [comment]
@sstemann I've modified the UI's node name formatting function to detect the presence of roman numerals and capitalize them accordingly. The fix is live in CI and can be seen here: https://ui.ci.transltr.io/main/results?l=NGLY1&i=NCBIGene:55768&t=2&r=0&q=14948210-8b07-4c59-a1e0-67aa57fd93a3

quickest way to find the result is to search for "II" in the text filter. 
![Screenshot 2024-07-09 at 12 14 28 PM](https://github.com/NCATSTranslator/Feedback/assets/54226761/c4ac271f-5b2f-4556-bc28-2171ce51470f)

**Comment by gprice1129** [comment]
The UI fix for the naming issue is in Test and will make it into the Eel release.

**Comment by andrewsu** [comment]
I no longer see the "cow milk" response in test, so I suggest not holding this issue open for that reason.
* https://ui.test.transltr.io/main/results?l=NGLY1%20(Human)&i=NCBIGene:55768&t=2&r=0&q=48453a10-c841-402a-9e8d-3a8db315ee43
* https://arax.ci.transltr.io/?r=48453a10-c841-402a-9e8d-3a8db315ee43

I also *do* see the UI fix that @gprice1129 mentioned above in test.  (I'll leave it to someone else to determine whether that's sufficient to close the issue, or whether we wait until it's on prod...)
