### ISSUE TITLE
DrugBank IDs as Names

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#899]
I ran MVP2 for what chemicals may decrease the activity of PTGDR2.  There seem to be a series of DrugBank IDs instead of names

https://ui.test.transltr.io/main/results?l=PTGDR2%20(Human)&i=NCBIGene:11251&t=2&r=0&q=8e5cfe6e-b9f8-4a78-83ed-73e07ba1fdf6

Looks like all 64 results of this text filter are "DrugBank:db#####" in the UI.  Some seem to have names, and some are DrugBank stubs

![image](https://github.com/user-attachments/assets/e2f73ede-1aa2-4dfb-be20-68a7c38cfbcc)

**Comment by gaurav** [comment]
Great catch! It turns out that some (all?) DrugBank identifiers are being added to the correct clique, and then are being silently dropped in the output file for some reason (https://github.com/TranslatorSRI/Babel/issues/332). These were being inserted into the previous release without any problems, so it must be a pretty recent change that broke this. I'll try to figure out what went wrong in the last release and try to get it fixed by Guppy, and I'll add this to my tests to make sure we catch it sooner in the future.

**Comment by khanspers** [comment]
I see the same thing for some ChEBI compounds, for example **1,25-dihydroxyvitamin D3** returned in the query "What drugs may treat conditions related to:[Osteopetrosis](https://monarchinitiative.org/MONDO:0017198)": 

<img width="961" alt="Screen Shot 2024-08-12 at 3 51 36 PM" src="https://github.com/user-attachments/assets/49ffd019-6cb1-4455-b47f-9c4e6e120a11">

Following the link, the ChEBI Name is **Calcitriol**. 

This is on test: https://ui.test.transltr.io/main/results?l=Osteopetrosis&i=MONDO:0017198&t=0&r=0&q=da9f830b-5633-429c-a1c9-0915b5439444

**Comment by sstemann** [comment]
@gaurav both of these look resolve in CI.  looking forward to moving it forward to Test.

**Comment by gaurav** [comment]
> The ChEBI Name is Calcitriol.

We haven't fully resolved this, in that we didn't change the order of the preferred prefixes for chemicals yet (as under discussion at https://github.com/TranslatorSRI/Babel/issues/306). However, it is fixed for now, in that we now have DrugBank labels, which under our current preferred prefixes overrides GTOPDB labels. I'll add it to my tests to make sure it stays fixed in the future.
